### ISSUE TITLE
"unknown error" when turn on light with Transition set

### ISSUE THREAD

**Issue by heyeshuang** [AlexxIT/XiaomiGateway3#1007]
Hello,

Today I tried to make [adaptive lighting](https://github.com/basnijholt/adaptive-lighting) with my bulb `lumi.light.acn014`. When I mannually call the service `light.turn_on` with `transition` set, I get an `unknown error` with logs:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 647, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 572, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/xiaomi_gateway3/light.py", line 98, in async_turn_on
    await self.device_send(kwargs)
  File "/config/custom_components/xiaomi_gateway3/core/entity.py", line 230, in device_send
    payload = self.device.encode(value)
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 407, in encode
    conv.encode(self, payload, v)
  File "/config/custom_components/xiaomi_gateway3/core/converters/base.py", line 128, in encode
    value = round(value / 255.0 * self.max)
TypeError: unsupported operand type(s) for /: 'tuple' and 'float'
```

In [light.py](https://github.com/AlexxIT/XiaomiGateway3/blob/65308cbbddeebba28a9ce41ed797bcdd16cced1c/custom_components/xiaomi_gateway3/light.py#L93), I find `ATTR_BRIGHTNESS` can be a tuple, maybe it causes the problem?

By the way, I'm using Home Assistant 2023.3.3 and I called the service in yaml below. Thanks in advance.

```yaml
service: light.turn_on
data:
  transition: 10
target:
  entity_id: light.0x54_light
```

**Comment by AlexxIT** [comment]
Check latest master version

**Comment by heyeshuang** [comment]
Thank you to pointing out the problem, now I can control it by `turn on` service.

However, while the actual color changes smoothly, the color temp in dashboard always shows 370, and in developer tools it looks like:

```YAML
min_color_temp_kelvin: 2702
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 370
supported_color_modes:
  - color_temp
color_mode: color_temp
brightness: 255
color_temp_kelvin: 370
color_temp: 2702
hs_color:
  - 15.981
  - 100
rgb_color:
  - 255
  - 67
  - 0
xy_color:
  - 0.674
  - 0.322
device_class: light
```

And the [log.txt](https://github.com/AlexxIT/XiaomiGateway3/files/11084873/log.txt) attaches here.

**Comment by AlexxIT** [comment]
If the gateway returns this value, there's nothing I can do about it

**Comment by heyeshuang** [comment]
It looks like that using `decode` function in [ColorTempKelvin](https://github.com/AlexxIT/XiaomiGateway3/blob/0664f000f726d2c776e7a84d301d51a6cc96957c/custom_components/xiaomi_gateway3/core/converters/base.py#L147) converter and `encode` in [ZXiaomiColorTempConv](https://github.com/AlexxIT/XiaomiGateway3/blob/eb44d986958c98e933b9266eb420874ac5a06334/custom_components/xiaomi_gateway3/core/converters/zigbee.py#L474) is the best approach for this device. That's weird.

However, at least I can control these lamps, thanks again for your help 😸

**Comment by AlexxIT** [comment]
Default gateway logic can't control light with transition. That's why Zigbee converter used here
