### ISSUE TITLE
Fix download device diagnostics for Xiaomi Multimode Gateway 2

### ISSUE THREAD

**Issue by garry0garry** [AlexxIT/XiaomiGateway3#1014]
Home Assistant 2023.3.6, Frontend 20230309.1
Xiaomi Gateway 3 for Home Assistant v3.1.0
Gateway DMWG03LM by Xiaomi (MGW2) Firmware: 1.0.6_0016 

After (or during) downloading diagnostics.
![изображение](https://user-images.githubusercontent.com/95581374/227798992-c0a77050-3a6a-4025-ae43-380f2097cacd.png)

```
This error originated from a custom integration.

Logger: custom_components.xiaomi_gateway3.core.gateway
Source: custom_components/xiaomi_gateway3/core/shell/__init__.py:36
Integration: xiaomi_gateway3 (documentation, issues)
First occurred: 10:02:54 PM (1 occurrences)
Last logged: 10:02:54 PM

192.168.50.33 | Can't update gateway stats
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw2.py", line 64, in mgw2_update_stats
    async with shell.Session(self.host) as sh:
  File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 29, in __aenter__
    await self.connect()
  File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 36, in connect
    self.reader, self.writer = await asyncio.wait_for(self.coro, 5)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

```

```
This error originated from a custom integration.

Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:328
Integration: xiaomi_gateway3 (documentation, issues)
First occurred: 10:03:20 PM (1 occurrences)
Last logged: 10:03:20 PM

192.168.50.33 | Device offline
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.2.0
