### ISSUE TITLE
Downgraded to v3.1.0 because v3.2.x simply does not work (timeout in prepare_gateway)

### ISSUE THREAD

**Issue by slydiman** [AlexxIT/XiaomiGateway3#1044]
HA 2023.04.0
Two gateways ZNDMWG03LM, firmware 1.5.4_0090
Few ZigBee devices, no BLE.
Everything worked fine with 3.1.0
After upgrading to 3.2.1 HA just cannot connect to gateways.
HA shows all ZigBee devices but all these devices including gateway are unavailable.
I tried to reboot gateways swtching the power off/on, tried to reboot HA, tried to delete and add gateways again - nothing helped.
The log is useless: a TimeoutError in prepare_gateway, then Device offline.
I have downgraded back to 3.1.0 and everything works just fine again.
I can help to investigate the issue. Just tell me what to do.
```
Logger: custom_components.xiaomi_gateway3.core.gateway
Source: custom_components/xiaomi_gateway3/core/shell/base.py:40
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 03:42:47 (2 occurrences)
Last logged: 03:42:57

192.168.3.252 | Can't prepare gateway
192.168.3.253 | Can't prepare gateway
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 616, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 201, in prepare_gateway
    return await self.gw3_prepare_gateway(sh)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw.py", line 54, in gw3_prepare_gateway
    msg = await sh.run_openmiio_agent()
  File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 125, in run_openmiio_agent
    ok = await self.check_openmiio_agent()
  File "/config/custom_components/xiaomi_gateway3/core/shell/shell_mgw.py", line 113, in check_openmiio_agent
    return await self.check_bin(
  File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 93, in check_bin
    await self.write_file(filepath, raw)
  File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 59, in write_file
    await self.exec(f"echo -n {b} | base64 -d >> {filename}")
  File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 40, in exec
    raw = await asyncio.wait_for(coro, timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

```

```
Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:328
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 04:00:33 (4 occurrences)
Last logged: 04:00:48

192.168.3.252 | Device offline
192.168.3.253 | Device offline
```

**Comment by slydiman** [comment]
I have upgraded from v3.1.0 to v3.2.0, then to v3.2.1 and it is connected now. Weird.
