### ISSUE TITLE
Can't Prepare Gateway

### ISSUE THREAD

**Issue by Porkoltszaft** [AlexxIT/XiaomiGateway3#1080]
I have two gateways, one of them is working great. On the other hand, one has stopped working, and I have no idea why. They have the same modified firmware (1.5.4), can access both of them on telnet, and both of them are working in the Xioami app. I see there were similar issues and they are resolved by fully resetting the gateway and adding all the devices again. But id possible I want to skip that, because I have a lot of temp and door sensors to pair again. 
This error originated from a custom integration. I tried to turn off (unplug) the gateway and then plugging back in, but the error is the same. It was working yesterday. What went wrong?

```
Logger: custom_components.xiaomi_gateway3.core.gateway
Source: custom_components/xiaomi_gateway3/number.py:39
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 08:43:32 (7 occurrences)
Last logged: 08:49:36

192.168.0.206 | Can't prepare gateway
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 188, in prepare_gateway
    return await self.gw3_prepare_gateway(sh)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw.py", line 49, in gw3_prepare_gateway
    await self.dispatcher_send(SIGNAL_PREPARE_GW, sh=sh)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/base.py", line 108, in dispatcher_send
    await handler(**kwargs)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/lumi.py", line 43, in lumi_prepare_gateway
    await self.lumi_read_devices(sh)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/lumi.py", line 39, in lumi_read_devices
    self.add_device(did, device)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/base.py", line 134, in add_device
    device.setup_entitites(self, stats=self.stats_enable)
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 281, in setup_entitites
    gateway.setup_entity(domain, self, conv)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/base.py", line 118, in setup_entity
    handler(self, device, conv)
  File "/config/custom_components/xiaomi_gateway3/core/entity.py", line 385, in setup
    entity = new_entity(gateway, device, conv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/number.py", line 19, in new_entity
    return XiaomiNumber(gateway, device, conv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/number.py", line 39, in __init__
    multiply = getattr(conv, "multiply") or 1
               ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ZOccupancyTimeoutConv' object has no attribute 'multiply'
```
Thank you in advance.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.2
