### ISSUE TITLE
Cannot be added a second time (BLE)

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/XiaomiGateway3#1090]
```
2023-06-27 14:09:17.520 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 818, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.e4aaec4e35cc_light cannot be added a second time to an entity platform
```

**Comment by sephrioth** [comment]
Now it's getting worse, I have removed my second gateway from Mi Home and HA, so there is only one gateway.

If I modify(e.g. rename a entity) any Gateway3 entity settings , all entities in Gateway3 goes unavailable immediately.  
I have to reboot the whole HA to get them back.

Is there anything I can do before the fix?

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.0
