### ISSUE TITLE
Can't add configuration

### ISSUE THREAD

**Issue by Mostalk** [AlexxIT/XiaomiGateway3#1105]
Hub firmware: 1.5.0
HA:  2023.7.1

Can't add configuration, I tried both ways (key, IP)

In both cases, the same error, here are the screenshots and the log of each error

![Screenshot_1](https://github.com/AlexxIT/XiaomiGateway3/assets/9198186/6a434569-fa40-4f42-9866-aa615d4e21dd)
![Screenshot_3](https://github.com/AlexxIT/XiaomiGateway3/assets/9198186/07b21abe-adf5-4367-bc84-102410909786)
![Screenshot_2](https://github.com/AlexxIT/XiaomiGateway3/assets/9198186/f424909c-aa60-4b6c-928c-0a14a5ef0895)
![Screenshot_4](https://github.com/AlexxIT/XiaomiGateway3/assets/9198186/bcccfb7e-c426-4ad8-b81b-bd2c5c20cba9)

```
Logger: homeassistant.setup
Source: util/json.py:74
First occurred: 08:42:47 (1 occurrences)
Last logged: 08:42:47

Error during setup of component xiaomi_gateway3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 68, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 99, in async_setup
    await utils.load_devices(hass, config.get(CONF_DEVICES))
  File "/config/custom_components/xiaomi_gateway3/core/utils.py", line 115, in load_devices
    devices = await store.async_load()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 122, in async_load
    return await self._load_task
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 131, in _async_load
    return await self._async_load_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 149, in _async_load_data
    data = await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 74, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: Input is a zero-length, empty document: line 1 column 1 (char 0)
```

```
Logger: homeassistant.util.json
Source: util/json.py:68
First occurred: 08:42:45 (1 occurrences)
Last logged: 08:42:45

Could not parse JSON content: /config/.storage/xiaomi_gateway3/devices.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 68, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
```

**Comment by Mostalk** [comment]
Tried several times to completely remove the integration from HASC and restarted HA. Same error.

The most interesting thing is that when I first installed it, it worked fine. Then I started playing with the firmware of the LYWSD03MMC sensor and suddenly the integration broke down and no longer starts

**Comment by AlexxIT** [comment]
Delete this file manually `/config/.storage/xiaomi_gateway3/devices.json`.
