### ISSUE TITLE
 Can't load devices list

### ISSUE THREAD

**Issue by chrisvvkeith** [AlexxIT/XiaomiGateway3#112]
when i log in  mi account ,can;t load devices list

this is log:
2020-11-18 22:07:57 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.xiaomi_cloud] Can't load devices list
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/xiaomi_cloud.py", line 145, in get_devices
assert resp['code'] == 0, resp
AssertionError: {'code': 4, 'message': 'auth err'}
2020-11-18 22:07:57 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.xiaomi_cloud] Can't load devices list
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/xiaomi_cloud.py", line 145, in get_devices
assert resp['code'] == 0, resp
AssertionError: {'code': 4, 'message': 'auth err'}
2020-11-18 22:07:57 ERROR (MainThread) [custom_components.xiaomi_gateway3] Can't load devices from MiCloud

**Comment by AlexxIT** [comment]
Maybe wrong user/pass

**Comment by chrisvvkeith** [comment]
the user/pass is correct.

**Comment by retrostrobe** [comment]
I was getting this error too until I discovered that the gateway had changed IP. 

So, if you go to Integrations > Add integration > Gateway 3 > Select Action dialogue window. From the list, you'll hopefully see your gateway with a new IP, e.g. Add Gateway 3 (10.0.1.22).

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
