### ISSUE TITLE
Uncaught thread exception

### ISSUE THREAD

**Issue by alex-rb338** [AlexxIT/XiaomiGateway3#114]
It firstly happens after update to Home Assistant 0.118.0 & HassOS 4.17. It was never happens before at ha 0.117.* and hassos 4.15
But now - it happens 1-2 times a day. All zigbee devices became uncontrollable. 
Home Assistant restart fix that but only temporarly.

Logs attached:

Logger: root
Source: custom_components/xiaomi_gateway3/core/gateway3.py:555
First occurred: 12:45:10 PM (1 occurrences)
Last logged: 12:45:10 PM
```
Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 95, in run
    self.mqtt.loop_forever()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 354, in on_message
    self.process_ble_event(msg.payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 555, in process_ble_event
    pdid = data['dev'].get('pdid')
TypeError: list indices must be integers or slices, not str
```

**Comment by maybeloveu** [comment]
hass.io the same problerm.

**Comment by to4ko** [comment]
same here. 118.2 one of my gateways got disconnected in 6.5h after HA start (Supervised install on Ubuntu 20.04). Other two gateways working just fine. 

Not sure if it's connected, but there is BLE device connected to gateway went offline.


![image](https://user-images.githubusercontent.com/45161980/99876160-f4e46700-2c05-11eb-8239-d168db99a0e5.png)

**Comment by to4ko** [comment]
@AlexxIT ping

**Comment by charles0103** [comment]
> hass.io the same problerm.

me too.

**Comment by alex-rb338** [comment]
Ive surrounded string with error in **gateway3.py** with try-catch:

`        try:
            pdid = data['dev'].get('pdid')
        except:
            self.debug(f"Some shit occured!")
            return
`
And since that it works ok. I understand that this is a dirty fix.
**AlexxIT**  commit some changes https://github.com/AlexxIT/XiaomiGateway3/commit/35421e917c5ba0b1d9e54ad807296a5604840eb1
But i havent tried to use master version yet.

**Comment by AlexxIT** [comment]
Master version has fix. Will be in next release. Or you can update to master now.

**Comment by alex-rb338** [comment]
Seems everything is ok now.
Thank you!
