### ISSUE TITLE
 Aqara E1 Can't prepare gateway

### ISSUE THREAD

**Issue by felixkang** [AlexxIT/XiaomiGateway3#1198]
can't find any Device , reboot、reset not work.

error log:
```
2023-11-02 21:02:44.976 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.50.42 | Can't prepare gateway
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 190, in prepare_gateway
    return await self.e1_prepare_gateway(sh)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_e1.py", line 31, in e1_prepare_gateway
    await self.dispatcher_send(SIGNAL_PREPARE_GW, sh=sh)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/base.py", line 108, in dispatcher_send
    await handler(**kwargs)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/openmiio.py", line 30, in openmiio_prepare_gateway
    await sh.download_openmiio()
  File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 145, in download_openmiio
    raw = await download(self.openmiio_url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 184, in download
    async with session.get(url_or_path) as resp:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
```

device info:
```
{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2023.10.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Asia/Shanghai",
    "os_name": "Linux",
    "os_version": "5.10.0-21-amd64",
    "supervisor": "2023.10.1",
    "host_os": "Debian GNU/Linux 11 (bullseye)",
    "docker_version": "23.0.0",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "midea_dehumidifier_lan": {
      "version": "0.8.13",
      "requirements": [
        "midea-beautiful-air==0.9.15"
      ]
    },
    "xiaomi_gateway3": {
      "version": "3.3.4",
      "requirements": [
        "zigpy>=0.44.1"
      ]
    },
    "adaptive_lighting": {
      "version": "1.19.0",
      "requirements": [
        "ulid-transform"
      ]
    },
    "ble_monitor": {
      "version": "12.6.1",
      "requirements": [
        "pycryptodomex>=3.18.0",
        "janus>=1.0.0",
        "aioblescan>=0.2.14",
        "btsocket>=0.2.0",
        "pyric>=0.1.6.3"
      ]
    },
    "midea_ac_lan": {
      "version": "v0.3.22",
      "requirements": []
    },
    "xiaomi_miot": {
      "version": "0.7.13",
      "requirements": [
        "construct>=2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    },
    "hacs": {
      "version": "1.30.1.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "codeowners": [
      "@AlexxIT"
    ],
    "config_flow": true,
    "dependencies": [
      "http"
    ],
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/AlexxIT/XiaomiGateway3/issues",
    "requirements": [
      "zigpy>=0.44.1"
    ],
    "version": "3.3.4",
    "is_built_in": false
  },
  "data": {
    "version": "68fe340",
    "options": {
      "host": "***",
      "token": "***",
      "key": "***"
    },
    "errors": [],
    "devices": {
      "54ef4457ea91": {
        "type": "gateway",
        "model": "lumi.gateway.aqcn02",
        "fw_ver": "4.0.1_0001",
        "available": true,
        "entities": {
          "command": {
            "state": "unknown",
            "value": null
          },
          "data": {
            "state": "unknown",
            "value": null
          },
          "gateway": {
            "state": "unknown",
            "value": null
          }
        },
        "gateways": [
          "54ef4457ea91"
        ],
        "stats": {}
      }
    }
  }
}
```

**Comment by AlexxIT** [comment]
Some problems with your internet. It tries to download openmiio

**Comment by felixkang** [comment]
> Some problems with your internet. It tries to download openmiio

Thank you very much for your reply. I tried to reset and restart it many times and it can be used normally. However, this error still occasionally appears in the log. I don’t know whether it will affect subsequent normal use.

**Comment by felixkang** [comment]
I have three E1 gateways, and only this one keeps getting errors.



2023-11-11 16:21:43.619 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.50.135 | Can't prepare gateway
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 179, in prepare_gateway
    async with shell.Session(self.host) as sh:
  File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 31, in __aenter__
    return await self.login()
           ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 54, in login
    raise Exception(f"Unknown response: {resp}")
Exception: Unknown response: b'\xff\xfd\x01\xff\xfd\x1f\xff\xfb\x01\xff\xfb\x03\r\r\nAqara_Hub_E1-EA91 login: '

**Comment by felixkang** [comment]
Find the dealer to replace the equipment with new equipment and solve the problem.
