### ISSUE TITLE
Can't change 'Power On State' for ZNCZ02LM (lumi.plug)

### ISSUE THREAD

**Issue by DJTerentjev** [AlexxIT/XiaomiGateway3#1235]
XiaomiGateway3 last release v3.3.4, Home assistant last release (v2023.12.1). ZigBee device: ZNCZ02LM (lumi.plug).
Property 'Power On State' is hidden by default in HA. Once I enable this property and all integration got stuck (all sensors was not available). After restart HA all sensor were back. But trying to change  'Power On State' I got error in HA and can't change the setting.
Please have a look.

```
[547558527936] coroutine raised StopIteration
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/entity.py", line 255, in device_send
    payload = self.device.encode(value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 407, in encode
    conv.encode(self, payload, v)
  File "/config/custom_components/xiaomi_gateway3/core/converters/base.py", line 98, in encode
    value = next(k for k, v in self.map.items() if v == value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/switch.py", line 43, in async_turn_off
    await self.device_send({self.attr: False})
RuntimeError: coroutine raised StopIteration
```

**Comment by DJTerentjev** [comment]
The problem is still present in Home Assistant 2024.2.1

XiaomiGateway3 v.3.3.6
Hub v. 1.0.7_0021

**Comment by AlexxIT** [comment]
Should be fixed https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.0

**Comment by DJTerentjev** [comment]
Yes. It was fixed. Thank you!
