### ISSUE TITLE
Can't prepare gateway:Timeout Error

### ISSUE THREAD

**Issue by WeichenLi2020** [AlexxIT/XiaomiGateway3#1267]
**Description:**

After updating both Home Assistant and the integration version, I encountered the following errors. I attempted to reinstall the integration multiple times, but it did not resolve the issue.

**Environment:**

- Device: Gateway ZNDMWG03LM (Firmware 1.5.0_0026)
- Home Assistant Version: 2023.9.3

**Issues Encountered:**

1. **XiaomiGateway3 Version 3.3.5 & Version 3.3.4:**
   - Gateway states are unavailable.
   - No connected devices are displayed.
   
   **Log Output:**
   ```
   Logger: custom_components.xiaomi_gateway3.core.gateway
   Source: custom_components/xiaomi_gateway3/core/shell/base.py:184
   Integration: Xiaomi Gateway 3 (documentation, issues)
   First occurred: 15:35:57 (13 occurrences)
   Last logged: 15:59:18

   192.168.0.19 | Can't prepare gateway
   Traceback (most recent call last):
     File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 188, in prepare_gateway
       return await self.gw3_prepare_gateway(sh)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw.py", line 49, in gw3_prepare_gateway
       await self.dispatcher_send(SIGNAL_PREPARE_GW, sh=sh)
     File "/config/custom_components/xiaomi_gateway3/core/gateway/base.py", line 108, in dispatcher_send
       await handler(**kwargs)
     File "/config/custom_components/xiaomi_gateway3/core/gateway/openmiio.py", line 30, in openmiio_prepare_gateway
       await sh.download_openmiio()
     File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 145, in download_openmiio
       raw = await download(self.openmiio_url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 184, in download
       async with session.get(url_or_path) as resp:
     File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
       self._resp = await self._coro
                    ^^^^^^^^^^^^^^^^
     File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 467, in _request
       with timer:
     File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
       raise asyncio.TimeoutError from None
   TimeoutError
   ```

2. **XiaomiGateway3 Version v3-3.0-alpha.1:**
   - All connected devices are visible, but their states are unavailable.
   
   **Log Output:**
   ```
   2024-01-21 04:08:27.040 DEBUG (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.0.19 [BASE] 54ef4436d26b (lumi.gateway.mgl03) setup gateway ZNDMWG03LM: alarm, command, data, led, gateway
   2024-01-21 04:08:27.041 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error adding entities for domain alarm_control_panel with platform xiaomi_gateway3
   Traceback (most recent call last):
     File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
       await asyncio.gather(*tasks)
     File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
       entity.add_to_platform_start(
     File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1250, in add_to_platform_start
       raise HomeAssistantError(
   homeassistant.exceptions.HomeAssistantError: Entity 'alarm_control_panel.54ef4436d26b_alarm' cannot be added a second time to an entity platform
   2024-01-21 04:08:27.041 ERROR (MainThread) [homeassistant.components.select] Error adding entities for domain select with platform xiaomi_gateway3
   Traceback (most recent call last):
     File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
       await asyncio.gather(*tasks)
     File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
       entity.add_to_platform_start(
     File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1250, in add_to_platform_start
       raise HomeAssistantError(
   homeassistant.exceptions.HomeAssistantError: Entity 'select.54ef4436d26b_command' cannot be added a second time to an entity platform
   2024-01-21 04:08:27.042 ERROR (MainThread) [homeassistant.components.select] Error adding entities for domain select with platform xiaomi_gateway3
   Traceback (most recent call last):
     File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
       await asyncio.gather(*tasks)
     File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
       entity.add_to_platform_start(
     File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1250, in add_to_platform_start
       raise HomeAssistantError(
   homeassistant.exceptions.HomeAssistantError: Entity 'select.54ef4436d26b_data' cannot be added a second time to an entity platform
   2024-01-21 04:08:27.042 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform xiaomi_gateway3
   Traceback (most recent call last):
     File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
       await asyncio.gather(*tasks)
     File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
       entity.add_to_platform_start(
     File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1250, in add_to_platform_start
       raise HomeAssistantError(
   homeassistant.exceptions.HomeAssistantError: Entity 'switch.54ef4436d26b_led' cannot be added a second time to an entity platform
   ……

   ```

Please let me know if you need any further information or logs to diagnose and address this problem.

**Comment by will-huang9531** [comment]
I have reason to believe that we have encountered similar issues #1268

**Comment by Slovator** [comment]
I confirm the problem.
Home Assistant: 2023.2.5
Gateway 3 firmware: custom 1.5.4_0090
Telnet: opened (admin/admin) but in "MiCloud Device Information" after adding integration using login and password to download tokens and names for devices from the cloud, "Telnet: wrong_telnet" is displayed.
Integration version: v3.3.5

When I try to add a gateway with a token, I get the error: "The Telnet open command is invalid" (I leave the "key" field blank).

**Comment by WeichenLi2020** [comment]
The error disappeared after a few days.
