### ISSUE TITLE
None of the devices under the gateway can be obtained

### ISSUE THREAD

**Issue by zuobianfy** [AlexxIT/XiaomiGateway3#1275]
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 192, in prepare_gateway
    return await self.mgw2_prepare_gateway(sh)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw2.py", line 36, in mgw2_prepare_gateway
    await self.dispatcher_send(SIGNAL_PREPARE_GW, sh=sh)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/base.py", line 108, in dispatcher_send
    await handler(**kwargs)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/openmiio.py", line 30, in openmiio_prepare_gateway
    await sh.download_openmiio()
  File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 145, in download_openmiio
    raw = await download(self.openmiio_url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 184, in download
    async with session.get(url_or_path) as resp:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 500, in _request
    with timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError  

Is it downloading something?

**Comment by zuobianfy** [comment]
The devices under the gateway have been unable to be obtained. The entity of gateway3 is also in an unknown state. If this entity is overloaded, it will also become unavailable.

**Comment by AlexxIT** [comment]
Yes. It is trying to download
https://github.com/AlexxIT/XiaomiGateway3/blob/566d1737f5e9d19a127001631f6d74157f4764bd/custom_components/xiaomi_gateway3/core/shell/base.py#L17
And can't. Check your internet.

**Comment by zuobianfy** [comment]
> Yes. It is trying to download
> 
> https://github.com/AlexxIT/XiaomiGateway3/blob/566d1737f5e9d19a127001631f6d74157f4764bd/custom_components/xiaomi_gateway3/core/shell/base.py#L17
> 
> 
> And can't. Check your internet.

After all, in China to access github, the network is not smooth. If manually downloaded, how to install? Thank you very much for your reply

**Comment by AlexxIT** [comment]
There is undocumented feature for pushing local openmiio. Change these settings to fit your needs:

```yaml
xiaomi_gateway3:
  openmiio:
    md5_mips: 6b914ea2967438cda7120853472b1340
    md5_arm: 867645409f437e739f3e914b23aacedd
    url_mips: ./openmiio_agent/openmiio_agent_mips
    url_arm: ./openmiio_agent/openmiio_agent_arm
```

MIPS - Multimode 1, ARM - multimode 2.
