### ISSUE TITLE
Error setting up devices

### ISSUE THREAD

**Issue by fishbone-git** [AlexxIT/XiaomiGateway3#13]
The log stops after starting setup of the first device:

`2020-09-09 00:01:17  DEBUG    gateway3      192.168.178.184 | Read devices
2020-09-09 00:01:17  DEBUG    gateway3      192.168.178.184 | Setup device lumi.sensor_switch.v2`

In the home assistant log, I see the component errors out:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 228, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 67, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 140, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 298, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 394, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/sensor.py", line 13, in <module>
    DEVICE_CLASS_HUMIDITY: UNIT_PERCENTAGE,
NameError: name 'UNIT_PERCENTAGE' is not defined
`

I changed UNIT_PERCENTAGE to % and it works.

Home assistant version is 0.115b1

**Comment by fishbone-git** [comment]
updated to latest, now getting this repeatedly:

`2020-09-09 00:46:41  DEBUG    gateway3      Can't read devices: Invalid base64-encoded string: number of data characters (57) cannot be 1 more than a multiple of 4
2020-09-09 00:46:41  DEBUG    gateway3      192.168.178.184 | Try enable telnet
2020-09-09 00:46:41  DEBUG    gateway3      192.168.178.184 | Read devices`

**Comment by AlexxIT** [comment]
Fix % in latest master version.
"Invalid base64" duplicate #14
