### ISSUE TITLE
Can't read mesh devices

### ISSUE THREAD

**Issue by StetskoSergey** [AlexxIT/XiaomiGateway3#130]
Logger: custom_components.xiaomi_gateway3.core.gateway3
Source: custom_components/xiaomi_gateway3/core/unqlite.py:176
Integration: Xiaomi Gateway 3 (documentation) 
First occurred: 8:05:27 (1 occurrences) 
Last logged: 8:05:27

Can't read mesh devices
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 272, in _get_devices
    rows = db.read_table('mesh_group')
  File "/config/custom_components/xiaomi_gateway3/core/unqlite.py", line 176, in read_table
    page = next(t[3] - 1 for t in self.tables if t[1] == name)
StopIteration

**Comment by w27** [comment]
The same problem.

**Comment by AlexxIT** [comment]
Fix in master version. Soon will be in release
