### ISSUE TITLE
Exception " KeyError: 'networkPanId' " after running for hours

### ISSUE THREAD

**Issue by w27** [AlexxIT/XiaomiGateway3#131]
After running for hours, the following exception are shown, and all sensors stop updating. The gateway pairing switch still works.
```
2020-12-05 05:45:18 ERROR (Thread-5) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 950, in _bootstrap_inner
self.run()
File "/home/username/.homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 94, in run
self.mqtt.loop_forever()
File "/home/username/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
rc = self.loop(timeout, max_packets)
File "/home/username/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1181, in loop
rc = self.loop_read(max_packets)
File "/home/username/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1572, in loop_read
rc = self._packet_read()
File "/home/username/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
rc = self._packet_handle()
File "/home/username/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
return self._handle_publish()
File "/home/username/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
self._handle_on_message(message)
File "/home/username/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
self.on_message(self, self._userdata, message)
File "/home/username/.homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 366, in on_message
self.process_gw_message(payload)
File "/home/username/.homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 527, in process_gw_message
'network_pan_id': payload['networkPanId'],
KeyError: 'networkPanId'
```

Connected devices:
Bluetooth temperature sensor(LYWSD03MMC) *4
Wireless button(WXKG01LM) *1

**Comment by AlexxIT** [comment]
Fix in master version. Soon will be in release
