### ISSUE TITLE
Lights opened itself constantly

### ISSUE THREAD

**Issue by wz69699** [AlexxIT/XiaomiGateway3#1345]
I see the issue ‘Bluetooth mesh does not get the status correctly #1335’. The conversation mentioned the adaptive-lighting integration.
 
I also use the adaptive-lighting integration. Here's my issue: During my trip, I found my mesh-group light (I got only one mesh group) opened itself constantly. I'm sure the open status is correct because I can see the light through the camera. And my mom asked me what happened to the 3 lights.
 
The mesh-group(筒灯) includes 3 lights, which is 筒灯1,筒灯2 and 筒灯3. All 4 entities are added to gateway3, and only 1 entity(the mesh group) is added to Homekit Bridge and adaptive-lighting. 
 
By the way, the gateway3 version is 4.0.5.

[home-assistant_xiaomi_gateway3_2024-05-04T15-05-19.456Z.log](https://github.com/AlexxIT/XiaomiGateway3/files/15210076/home-assistant_xiaomi_gateway3_2024-05-04T15-05-19.456Z.log)
<img width="664" alt="1" src="https://github.com/AlexxIT/XiaomiGateway3/assets/155177891/23d37b0e-bcf3-4d9c-8838-a5ef4beca228">
<img width="442" alt="2" src="https://github.com/AlexxIT/XiaomiGateway3/assets/155177891/957186ac-d9af-4679-a4dd-982815c6c841">
<img width="662" alt="3" src="https://github.com/AlexxIT/XiaomiGateway3/assets/155177891/95e92a8c-a894-4355-85a3-f66088ce5862">
<img width="464" alt="4" src="https://github.com/AlexxIT/XiaomiGateway3/assets/155177891/66af42c3-fe1f-468c-86aa-1303bcc7f49d">
<img width="675" alt="5" src="https://github.com/AlexxIT/XiaomiGateway3/assets/155177891/7af3007a-e93b-4562-9797-3ffc4e606784">
<img width="507" alt="6" src="https://github.com/AlexxIT/XiaomiGateway3/assets/155177891/26d292d7-04ff-46f8-9180-a8934710ba9a">
<img width="507" alt="7" src="https://github.com/AlexxIT/XiaomiGateway3/assets/155177891/fd7384c5-8d18-40e0-98fd-f2720768ac0b">

**Comment by wz69699** [comment]
Device information:
3 same lights
Mesh: YLTS02YL/YLTS04YL, yeelink.light.ml1

**Comment by wz69699** [comment]
it happened again. Here's the log.

Is the issue caused by xiaomi_miot? My ha's Core version is 2024.5.0 currently (The latest is 5.1) .

日志: homeassistant.core
来源: core.py:2758
首次发生: 2024年5月3日 08:15:11 (136 全部发生)
上次记录: 02:28:36

Error executing service: <ServiceCall light.turn_on (c:01HX2DFWF0:al:5CD2:ntrv:H3): entity_id=['light.yeelink_ceil26_2404_light'], params=transition=45.0, brightness=3, color_temp=370, color_temp_kelvin=2702>
Error executing service: <ServiceCall light.turn_on (c:01HX2DJMV7:al:5CD2:ntrv:H4): entity_id=['light.yeelink_ceil26_2404_light'], params=transition=45.0, brightness=3, color_temp=370, color_temp_kelvin=2702>
Error executing service: <ServiceCall light.turn_on (c:01HX2DND7F:al:5CD2:ntrv:H5): entity_id=['light.yeelink_ceil26_2404_light'], params=transition=45.0, brightness=3, color_temp=370, color_temp_kelvin=2702>
Error executing service: <ServiceCall light.turn_on (c:01HX2DR5KM:al:5CD2:ntrv:H6): entity_id=['light.yeelink_ceil26_2404_light'], params=transition=45.0, brightness=3, color_temp=370, color_temp_kelvin=2702>
Error executing service: <ServiceCall light.turn_on (c:01HX2DTXZT:al:5CD2:ntrv:H8): entity_id=['light.yeelink_ceil26_2404_light'], params=transition=45.0, brightness=3, color_temp=370, color_temp_kelvin=2702>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2758, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 627, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1680, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/light.py", line 187, in turn_on
    ret = self.send_miio_command('set_bright', [val, 'smooth', trs])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1340, in send_miio_command
    return super().send_miio_command(method, params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/__init__.py", line 989, in send_miio_command
    self.hass.bus.async_fire(f'{DOMAIN}.send_miio_command', {
  File "/usr/src/homeassistant/homeassistant/core.py", line 1508, in async_fire
    self._hass.verify_event_loop_thread("async_fire")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'xiaomi_miot' calls async_fire from a thread at custom_components/xiaomi_miot/__init__.py, line 989: self.hass.bus.async_fire(f'{DOMAIN}.send_miio_command', {. Please report it to the author of the 'xiaomi_miot' custom integration.


日志: homeassistant.helpers.frame
来源: helpers/frame.py:190
首次发生: 2024年5月3日 02:44:23 (143 全部发生)
上次记录: 02:28:36

Detected that custom integration 'xiaomi_miot' accesses hass.helpers.service. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from service directly at custom_components/xiaomi_miot/__init__.py, line 560: hass.helpers.service.async_register_admin_service(, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'xiaomi_miot' calls async_fire from a thread at custom_components/xiaomi_miot/__init__.py, line 989: self.hass.bus.async_fire(f'{DOMAIN}.send_miio_command', {, please report it to the author of the 'xiaomi_miot' custom integration
Detected that custom integration 'adaptive_lighting' accesses hass.helpers.entity_component. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from entity_component directly at custom_components/adaptive_lighting/switch.py, line 2471: await self.hass.helpers.entity_component.async_update_entity(light), please create a bug report at https://github.com/basnijholt/adaptive-lighting/issues
Detected that custom integration 'xiaomi_miot' calls async_write_ha_state from a thread at custom_components/xiaomi_miot/__init__.py, line 1906: self.async_write_ha_state(), please report it to the author of the 'xiaomi_miot' custom integration

<img width="506" alt="8" src="https://github.com/AlexxIT/XiaomiGateway3/assets/155177891/124d70d9-061f-448d-b91b-2ec1c2580223">
<img width="1284" alt="9" src="https://github.com/AlexxIT/XiaomiGateway3/assets/155177891/e8863ebe-cc2e-4f31-8944-b79ceb8f3617">

**Comment by AlexxIT** [comment]
1. There is nothing in your logs about this component
2. Your error about the component `xiaomi_miot`
3. Your screenshots are useless because I don't understand your language

**Comment by wz69699** [comment]
My mesh-group (light1, light2 and light3) just turned on by itself. I screenshotted the log and translated it. I'm pretty sure the translation is correct (I checked it 3 times).It says 'triggered by service'. what service indeed? What service may it be?

I did not add this mesh-group (light1, light2 and light3) into xiaomi_miot. In my understanding, the issue can't be caused by xiaomi_miot.

And I only add the group into Gateway3. (I did not add light1, light2 or light3 into Gateway3)

<img width="629" alt="x" src="https://github.com/AlexxIT/XiaomiGateway3/assets/155177891/36268e3a-5c80-4f10-8b9a-1a8ff9b377bc">

I'm really confused.

[home-assistant_adaptive_lighting_2024-05-05T15-57-19.654Z.log](https://github.com/AlexxIT/XiaomiGateway3/files/15213662/home-assistant_adaptive_lighting_2024-05-05T15-57-19.654Z.log)
[home-assistant_xiaomi_gateway3_2024-05-05T15-59-21.613Z.log](https://github.com/AlexxIT/XiaomiGateway3/files/15213664/home-assistant_xiaomi_gateway3_2024-05-05T15-59-21.613Z.log)
