### ISSUE TITLE
Detected blocking call to open inside the event loop by custom integration 'xiaomi_gateway3'

### ISSUE THREAD

**Issue by dmitkam** [AlexxIT/XiaomiGateway3#1380]
Debian GNU/Linux 12 (bookworm), Home Assistant Supervise,  core-2024.6.2, XiaomiGateway3 - master
```
Уровень: ПРЕДУПРЕЖДЕНИЕ
Регистратор: homeassistant.util.loop
Источник: util/loop.py:84
Первое сообщение: 07:16:12 (74238 сообщений)
Последнее сообщение: 14:44:50

Detected blocking call to open inside the event loop by custom integration 'xiaomi_gateway3' at custom_components/xiaomi_gateway3/core/gate/base.py, line 72: self.base_log.debug(msg | kwargs, exc_info=exc_info) (offender: /usr/local/lib/python3.12/logging/__init__.py, line 1263: return open_func(self.baseFilename, self.mode,), please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/xiaomi_gateway3/core/gateway.py", line 58, in run_forever await self.handle_mqtt_messages() File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 147, in handle_mqtt_messages self.on_mqtt_message(msg) File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 177, in on_mqtt_message self.dispatch_event(EVENT_MQTT_PUBLISH, msg) File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 91, in dispatch_event handler(*args, **kwargs) File "/config/custom_components/xiaomi_gateway3/core/gate/ble.py", line 26, in ble_on_mqtt_publish self.ble_process_event(msg.json["params"]) File "/config/custom_components/xiaomi_gateway3/core/gate/ble.py", line 59, in ble_process_event device.on_report(data["evt"], self, ts) File "/config/custom_components/xiaomi_gateway3/core/device.py", line 462, in on_report gw.debug("on_report", device=self, data=payload) File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 72, in debug self.base_log.debug(msg | kwargs, exc_info=exc_info)
Detected blocking call to open inside the event loop by custom integration 'xiaomi_gateway3' at custom_components/xiaomi_gateway3/core/gate/silabs.py, line 82: self.zigb_log.debug({"uid": uid, "nwk": nwk, "data": data["decode"]}) (offender: /usr/local/lib/python3.12/logging/__init__.py, line 1263: return open_func(self.baseFilename, self.mode,), please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/xiaomi_gateway3/core/gateway.py", line 58, in run_forever await self.handle_mqtt_messages() File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 147, in handle_mqtt_messages self.on_mqtt_message(msg) File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 177, in on_mqtt_message self.dispatch_event(EVENT_MQTT_PUBLISH, msg) File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 91, in dispatch_event handler(*args, **kwargs) File "/config/custom_components/xiaomi_gateway3/core/gate/silabs.py", line 59, in silabs_on_mqtt_publish self.silabs_process_recv(msg.json) File "/config/custom_components/xiaomi_gateway3/core/gate/silabs.py", line 82, in silabs_process_recv self.zigb_log.debug({"uid": uid, "nwk": nwk, "data": data["decode"]})
Detected blocking call to open inside the event loop by custom integration 'xiaomi_gateway3' at custom_components/xiaomi_gateway3/core/gate/base.py, line 72: self.base_log.debug(msg | kwargs, exc_info=exc_info) (offender: /usr/local/lib/python3.12/logging/__init__.py, line 1263: return open_func(self.baseFilename, self.mode,), please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/xiaomi_gateway3/core/gateway.py", line 58, in run_forever await self.handle_mqtt_messages() File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 147, in handle_mqtt_messages self.on_mqtt_message(msg) File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 177, in on_mqtt_message self.dispatch_event(EVENT_MQTT_PUBLISH, msg) File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 91, in dispatch_event handler(*args, **kwargs) File "/config/custom_components/xiaomi_gateway3/core/gate/silabs.py", line 59, in silabs_on_mqtt_publish self.silabs_process_recv(msg.json) File "/config/custom_components/xiaomi_gateway3/core/gate/silabs.py", line 128, in silabs_process_recv device.on_report(data, self, ts) File "/config/custom_components/xiaomi_gateway3/core/device.py", line 462, in on_report gw.debug("on_report", device=self, data=payload) File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 72, in debug self.base_log.debug(msg | kwargs, exc_info=exc_info)
Detected blocking call to open inside the event loop by custom integration 'xiaomi_gateway3' at custom_components/xiaomi_gateway3/core/gate/base.py, line 175: self.mqtt_log.debug({"topic": msg.topic, "data": msg.payload}) (offender: /usr/local/lib/python3.12/logging/__init__.py, line 1263: return open_func(self.baseFilename, self.mode,), please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/xiaomi_gateway3/core/gateway.py", line 58, in run_forever await self.handle_mqtt_messages() File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 147, in handle_mqtt_messages self.on_mqtt_message(msg) File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 175, in on_mqtt_message self.mqtt_log.debug({"topic": msg.topic, "data": msg.payload})
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.8
