### ISSUE TITLE
Detected blocking call

### ISSUE THREAD

**Issue by to4ko** [AlexxIT/XiaomiGateway3#1422]
Latest master version of integration and HA 2024.8.1.
Not supercritical but...
 
```
2024-08-14 11:40:28.168 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/xiaomi_gateway3.log', 'a') inside the event loop by custom integration 'xiaomi_gateway3' at custom_components/xiaomi_gateway3/core/logger.py, line 64: handler = RotatingFileHandler( (offender: /usr/local/lib/python3.12/logging/__init__.py, line 1263: return open_func(self.baseFilename, self.mode,), please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "", line 198, in _run_module_as_main
  File "", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in 
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 61, in async_setup
    logger.init(__name__, logger_config, hass.config.config_dir)
  File "/config/custom_components/xiaomi_gateway3/core/logger.py", line 64, in init
    handler = RotatingFileHandler(
```

**Comment by rama31244** [comment]
Does this error break use of the integration? The integration stopped functioning as of recently for me and that's the first error I see in the log

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.7

**Comment by Enzokot** [comment]
With 4.0.7
<details><summary>Error details</summary>

```
2024-11-27 09:44:54.495 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/xiaomi_gateway3.log', 'a') inside the event loop by custom integration 'xiaomi_gateway3' at custom_components/xiaomi_gateway3/core/gate/base.py, line 175: self.mqtt_log.debug({"topic": msg.topic, "data": msg.payload}) (offender: /usr/local/lib/python3.12/logging/__init__.py, line 1263: return open_func(self.baseFilename, self.mode,), please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/xiaomi_gateway3/core/gateway.py", line 58, in run_forever
    await self.handle_mqtt_messages()
  File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 147, in handle_mqtt_messages
    self.on_mqtt_message(msg)
  File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 175, in on_mqtt_message
    self.mqtt_log.debug({"topic": msg.topic, "data": msg.payload})
```

</details>

**Comment by to4ko** [comment]
same here. ha 2024.11.3, integration 4.0.7

```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 03:57:20 (1 occurrences)
Last logged: 03:57:20

Detected blocking call to open with args ('/config/xiaomi_gateway3.log', 'a') inside the event loop by custom integration 'xiaomi_gateway3' at custom_components/xiaomi_gateway3/core/gate/base.py, line 175: self.mqtt_log.debug({"topic": msg.topic, "data": msg.payload}) (offender: /usr/local/lib/python3.12/logging/__init__.py, line 1263: return open_func(self.baseFilename, self.mode,), please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/xiaomi_gateway3/core/gateway.py", line 58, in run_forever await self.handle_mqtt_messages() File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 147, in handle_mqtt_messages self.on_mqtt_message(msg) File "/config/custom_components/xiaomi_gateway3/core/gate/base.py", line 175, in on_mqtt_message self.mqtt_log.debug({"topic": msg.topic, "data": msg.payload})
```

**Comment by AlexxIT** [comment]
Well. This is another issue. But we could go on in this one

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.8
