### ISSUE TITLE
Error after update HA 2024.9.0

### ISSUE THREAD

**Issue by EvgenyBash** [AlexxIT/XiaomiGateway3#1439]
Регистратор: homeassistant.setup
Источник: setup.py:334
Первое сообщение: 20:57:11 (1 сообщений)
Последнее сообщение: 20:57:11

Setup failed for custom integration 'xiaomi_gateway3': Unable to import component: cannot import name 'DATA_TYPES' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.12/site-packages/zigpy/zcl/foundation.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 14, in <module>
    from .core.device import XDevice
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 9, in <module>
    from .converters import silabs
  File "/config/custom_components/xiaomi_gateway3/core/converters/silabs.py", line 4, in <module>
    from zigpy.zcl.foundation import (
ImportError: cannot import name 'DATA_TYPES' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.12/site-packages/zigpy/zcl/foundation.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 14, in <module>
    from .core.device import XDevice
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 9, in <module>
    from .converters import silabs
  File "/config/custom_components/xiaomi_gateway3/core/converters/silabs.py", line 4, in <module>
    from zigpy.zcl.foundation import (
ImportError: cannot import name 'DATA_TYPES' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.12/site-packages/zigpy/zcl/foundation.py)

**Comment by AlexxIT** [comment]
#1434

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.6
