### ISSUE TITLE
blocking call - ha 2024.9.0

### ISSUE THREAD

**Issue by to4ko** [AlexxIT/XiaomiGateway3#1440]
blocking call detected

```
2024-09-04 21:18:08.244 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/xiaomi_gateway3.log', 'a') inside the event loop by custom integration 'xiaomi_gateway3' at custom_components/xiaomi_gateway3/core/logger.py, line 64: handler = RotatingFileHandler( (offender: /usr/local/lib/python3.12/logging/__init__.py, line 1263: return open_func(self.baseFilename, self.mode,), please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "", line 198, in _run_module_as_main
  File "", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in 
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 61, in async_setup
    logger.init(__name__, logger_config, hass.config.config_dir)
  File "/config/custom_components/xiaomi_gateway3/core/logger.py", line 64, in init
    handler = RotatingFileHandler(
```

**Comment by AlexxIT** [comment]
#1422
