### ISSUE TITLE
Gateway 3 not work with RPi 5

### ISSUE THREAD

**Issue by kyc1338** [AlexxIT/XiaomiGateway3#1471]
I tried to upgrade my  RPi4 to RPi5, after full restore, GW 3 showed (not loaded), can't delete it from Devices. Remove it from HACS but still can't delete it from Devices. 

Deleted GW3 at RPi4 and created backup. After restored to RPi5 and redownload GW3, it still showed (not loaded) in Devices.

Below is the log file:
```
Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 9:27:53 AM (1 occurrences)
Last logged: 9:27:53 AM

Detected blocking call to import_module with args ('custom_components.xiaomi_gateway3 backuo',) in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)
```

**Comment by AlexxIT** [comment]
I don't know what this means `'custom_components.xiaomi_gateway3 backuo'`. Some space and word `backuo`... You installation broken. Only you can find out why.
