### ISSUE TITLE
Unable to import component: cannot import name 'Converter'

### ISSUE THREAD

**Issue by sephrioth** [AlexxIT/XiaomiGateway3#1474]
Just upgraded to Homeassistant 10.1

Setup failed for custom integration 'xiaomi_gateway3': Unable to import component: cannot import name 'Converter' from 'custom_components.xiaomi_gateway3.core.converters.base' (/config/custom_components/xiaomi_gateway3/core/converters/base.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 14, in <module>
    from .core.device import XDevice
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 9, in <module>
    from .converters import silabs
  File "/config/custom_components/xiaomi_gateway3/core/converters/__init__.py", line 6, in <module>
    from .base import Converter, LUMI_GLOBALS, parse_time
ImportError: cannot import name 'Converter' from 'custom_components.xiaomi_gateway3.core.converters.base' (/config/custom_components/xiaomi_gateway3/core/converters/base.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 14, in <module>
    from .core.device import XDevice
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 9, in <module>
    from .converters import silabs
  File "/config/custom_components/xiaomi_gateway3/core/converters/__init__.py", line 6, in <module>
    from .base import Converter, LUMI_GLOBALS, parse_time
ImportError: cannot import name 'Converter' from 'custom_components.xiaomi_gateway3.core.converters.base' (/config/custom_components/xiaomi_gateway3/core/converters/base.py)

**Comment by sephrioth** [comment]
Sovled
