### ISSUE TITLE
Can't Connect to HomeKit

### ISSUE THREAD

**Issue by areyoufserious** [AlexxIT/XiaomiGateway3#177]
I want to connect Gateway to iPhone in order to get independent from Home Assistant way of controlling devices. 

Tried a lot of times by different options -- no luck

1. If I try to from Mi Home or Home App Using Camera  -- I get Not Found Error
Screenshot and video here
https://drive.google.com/drive/folders/1AVB0X8_H7YYhBsb7o5TSmRv2DhdM6ND5?usp=sharing
2. If I Add by providing HomeKit Code -- I get Wrong Code Error

Then i tried to add Gateway to Home Assistant HomeKit Controller Integration and that's i found i logs:
```
2021-01-15 22:54:18 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 310, in async_step_pair
pairing = await self.finish_pairing(code)
File "/usr/local/lib/python3.8/site-packages/aiohomekit/controller/ip/discovery.py", line 99, in finish_pairing
request, expected = state_machine.send(response)
File "/usr/local/lib/python3.8/site-packages/aiohomekit/protocol/__init__.py", line 179, in perform_pair_setup_part2
raise InvalidError("M5: not an error or a proof")
aiohomekit.exceptions.InvalidError: M5: not an error or a proof
```

**Comment by AlexxIT** [comment]
If you already connected gateway via HomeKit somethere (example Home Asisstant) - you need reset your gateway to factory default. 10 clicks on button.
