### ISSUE TITLE
Missing devices

### ISSUE THREAD

**Issue by leximester** [AlexxIT/XiaomiGateway3#247]
HI.
I successfully added XiaomiGateway3 to my HA. But can't find any device. 
My system: 
2021-03-01 17:12:42  DEBUG    main          SysInfo: {'installation_type': 'Home Assistant Container', 'version': '2020.12.2', 'dev': False, 'hassio': False, 'virtualenv': False, 'python_version': '3.8.6', 'docker': True, 'arch': 'x86_64', 'os_name': 'Linux', 'os_version': '5.8.0-41-generic'}
Gateway fw: 1.4.7_0115

Error in logs:
<img width="688" alt="Képernyőfotó 2021-03-01 - 17 31 40" src="https://user-images.githubusercontent.com/5308151/109527489-00241a00-7ab4-11eb-8c50-e170df389a3f.png">

[
<img width="299" alt="Képernyőfotó 2021-03-02 - 10 18 09" src="https://user-images.githubusercontent.com/5308151/109626309-a9b0ed00-7b40-11eb-91f4-001883ca026f.png">
](url)

**Comment by themiguelamador** [comment]
Same error here:

Logger: root
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:139
First occurred: 20:28:48 (6 occurrences)
Last logged: 20:32:30

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 407, in run
    if not self._check_port(23) and not self._enable_telnet():
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 452, in _enable_telnet
    if self.miio.send(raw['method'], raw.get('params')) != 'ok':
  File "/config/custom_components/xiaomi_gateway3/core/mini_miio.py", line 139, in send
    return json.loads(data.rstrip(b'\x00'))['result']
KeyError: 'result'

**Comment by themiguelamador** [comment]
Check solution here: https://gist.github.com/zvldz/1bd6b21539f84339c218f9427e022709
Requires updated telnet commands.

**Comment by kss20ismine** [comment]
same problem here and I already used updated telnet commands. Anyone know how to fix it?

**Comment by EntingChou** [comment]
same problem for me could anyone help?

**Comment by zvldz** [comment]
you might be entering command with  error

**Comment by EntingChou** [comment]
as i want to open telent i input this command to filed : 
{"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}
i need to change syntax any where?

**Comment by EntingChou** [comment]
I using the TAIWAN server that internet said chooseSg' server

**Comment by EntingChou** [comment]
I running Home assistant on Windows10 using the virtual box ( other Linux), i've no idea how to usingpython-miio to open Telnet. currently i using home kit controller to access Xiaomi gateway 3

**Comment by EntingChou** [comment]
> as i want to open telent i input this command to filed :
> {"method":"set_ip_info","params":{"ssid":"""","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}
> i need to change syntax any where?

my gateway version is v1.4.6_0043

**Comment by EntingChou** [comment]
I found the Xiaomi Gateway 3 Debug log:

2021-03-07 16:31:53  DEBUG    main          SysInfo: {'installation_type': 'Home Assistant OS', 'version': '2021.3.2', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.7', 'docker': True, 'arch': 'x86_64', 'os_name': 'Linux', 'os_version': '5.4.99', 'supervisor': '2021.03.4', 'host_os': 'Home Assistant OS 5.12', 'docker_version': '19.03.13', 'chassis': 'vm'}
2021-03-07 16:31:53  DEBUG    gateway3      192.168.68.120 | Start main thread
2021-03-07 16:31:53  DEBUG    gateway3      192.168.68.120 | Prepare Gateway

**Comment by zvldz** [comment]
> i need to change syntax any where?

correct command:
```
{"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}
```

**Comment by EntingChou** [comment]
> > i need to change syntax any where?
> 
> correct command:
> 
> ```
> {"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}
> ```

but even I pasted the command also got this error: 
2021-03-07 16:33:53  DEBUG    gateway3      192.168.68.120 | Can't read devices: telnet connection closed

**Comment by zvldz** [comment]
try reboot gw

**Comment by EntingChou** [comment]
thank you very very much. it's running!!
