### ISSUE TITLE
Error after Upgrading to core-2021.4.0 Source: custom_components/xiaomi_gateway3/climate.py:41

### ISSUE THREAD

**Issue by mcfly2283-ai** [AlexxIT/XiaomiGateway3#306]
After Migration to core-2021.4.0 i found this Error in my Log-Files.
I Can`t find any Problems, everything seems to work at the moment.

Xiaomi Gateway 3 - ZNDMWG03LM (soldered with flashed custom Firmware)

INFO: I have an zhimi.humidifier.ca4 Humidifier with another Custom integration before, after upgrading it is deprecated and i moved from config.yaml to the MIIO-integration. Everything works fine at the Moment.

![image](https://user-images.githubusercontent.com/77355612/114079757-dfb55f80-98aa-11eb-957b-b5b809a70a7e.png)

![image](https://user-images.githubusercontent.com/77355612/114079080-02934400-98aa-11eb-9463-ae706e9ceb55.png)

Lumi Linux version 3.0
  _               _    _  _
 | |             |_|  | ||_|
 | | _  _  _____  _   | | _ ____  _   _  _  _
 | || || ||     \| |  | || |  _ \| | | |\ \/ /
 | || || || | | || |  | || | | | | |_| |/    \
 |_|\____||_|_|_||_|  |_||_|_| |_|\____|\_/\_/

For further information check:
https://www.aqara.com

BusyBox v1.22.1 (2020-03-19 12:38:22 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

======================================================
FIRMWARE........: 1.4.6_0012 #20201223

Logger: homeassistant.config_entries
Source: custom_components/xiaomi_gateway3/climate.py:41
First occurred: 20:12:48 (1 occurrences)
Last logged: 20:12:48

Error setting up entry 192.168.0.XX for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 162, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 142, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 325, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 35, in <module>
    class XiaomiClimate(XiaomiEntity, ClimateEntity):
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 41, in XiaomiClimate
    _state: Optional[bytearray] = None
NameError: name 'Optional' is not defined

**Comment by Soolita** [comment]
+1

**Comment by niceboygithub** [comment]
Before official release, use master release.

**Comment by AlexxIT** [comment]
Fixed in master version

**Comment by mcfly2283-ai** [comment]
fixed after update to 1.2.1 Thank you!
