### ISSUE TITLE
Error while parsing new BLE devices

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/XiaomiGateway3#318]
```
Logger: custom_components.xiaomi_gateway3.core.gateway3
Source: custom_components/xiaomi_gateway3/core/gateway3.py:1025
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 12:17:12 (84 occurrences)
Last logged: 13:05:43

Processing MQTT: log/ble b'{"did":"blt.3.xxx","eid":15,"edata":"640000","pdid":2038,"seq":5}'
Processing MQTT: log/ble b'{"did":"blt.3.xxx","eid":15,"edata":"640000","pdid":2038,"seq":8}'
Processing MQTT: log/ble b'{"did":"blt.3.xxx","eid":4119,"edata":"00000000","pdid":2038,"seq":9}'
Processing MQTT: log/ble b'{"did":"blt.3.xxx","eid":15,"edata":"640000","pdid":2038,"seq":14}'
Processing MQTT: log/ble b'{"did":"blt.3.xxx","eid":4119,"edata":"00000000","pdid":2038,"seq":15}'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 765, in on_message
    self.process_ble_event_fix(payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1007, in process_ble_event_fix
    self._process_ble_event(device, payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1025, in _process_ble_event
    for entity in device['entities'].values():
KeyError: 'entities'
```

**Comment by AlexxIT** [comment]
Fixed in latests release
