### ISSUE TITLE
Many errors of the same type in the log

### ISSUE THREAD

**Issue by adisik** [AlexxIT/XiaomiGateway3#323]
2021-05-04 12:20:17 ERROR (192.168.107.157_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: log/ble b'{"did":"blt.3.15tjk63kolk00","eid":4102,"edata":"5e01","pdid":1115,"seq":15}'
Traceback (most recent call last):
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 765, in on_message
self.process_ble_event_fix(payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1007, in process_ble_event_fix
self._process_ble_event(device, payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1025, in _process_ble_event
for entity in device['entities'].values():
KeyError: 'entities'
2021-05-04 12:20:18 ERROR (192.168.107.157_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: log/ble b'{"did":"blt.3.15tjk63kolk00","eid":4100,"edata":"f000","pdid":1115,"seq":16}'
Traceback (most recent call last):
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 765, in on_message
self.process_ble_event_fix(payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1007, in process_ble_event_fix
self._process_ble_event(device, payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1025, in _process_ble_event
for entity in device['entities'].values():
KeyError: 'entities'
2021-05-04 12:20:19 ERROR (192.168.107.157_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: log/ble b'{"did":"blt.3.15tjk63kolk00","eid":4106,"edata":"2c","pdid":1115,"seq":17}'
Traceback (most recent call last):
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 765, in on_message
self.process_ble_event_fix(payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1007, in process_ble_event_fix
self._process_ble_event(device, payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1025, in _process_ble_event
for entity in device['entities'].values():
KeyError: 'entities'
2021-05-04 12:20:19 ERROR (192.168.107.157_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: log/ble b'{"did":"blt.3.15dojf2soeg00","eid":4102,"edata":"4a01","pdid":1115,"seq":170}'
Traceback (most recent call last):
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 765, in on_message
self.process_ble_event_fix(payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1007, in process_ble_event_fix
self._process_ble_event(device, payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1025, in _process_ble_event
for entity in device['entities'].values():
KeyError: 'entities'
2021-05-04 12:20:20 ERROR (192.168.107.157_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: log/ble b'{"did":"blt.3.15tjk63kolk00","eid":4102,"edata":"5e01","pdid":1115,"seq":18}'
Traceback (most recent call last):
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 765, in on_message
self.process_ble_event_fix(payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1007, in process_ble_event_fix
self._process_ble_event(device, payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1025, in _process_ble_event
for entity in device['entities'].values():
KeyError: 'entities'
2021-05-04 12:20:20 ERROR (192.168.107.157_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: log/ble b'{"did":"blt.3.15dojf2soeg00","eid":4100,"edata":"e500","pdid":1115,"seq":171}'
Traceback (most recent call last):
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 765, in on_message
self.process_ble_event_fix(payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1007, in process_ble_event_fix
self._process_ble_event(device, payload)
File "/etc/homeassistant/custom_components/xiaomi_gateway3/core/gateway3.py", line 1025, in _process_ble_event
for entity in device['entities'].values():
KeyError: 'entities'

**Comment by kamingchan** [comment]
same here

```
2021-05-17 00:21:49 ERROR (10.0.10.40_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: log/ble b'{"did":"blt.3.1604ufpqolo00","eid":4102,"edata":"a802","pdid":2888,"seq":244}'
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 765, in on_message
self.process_ble_event_fix(payload)
File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1007, in process_ble_event_fix
self._process_ble_event(device, payload)
File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1025, in _process_ble_event
for entity in device['entities'].values():
KeyError: 'entities'
```

**Comment by chex01** [comment]
Logger: custom_components.xiaomi_gateway3.core.gateway3
Source: custom_components/xiaomi_gateway3/core/gateway3.py:1036
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 15:57:30 (437 occurrences)
Last logged: 21:06:57

Processing MQTT: log/ble b'{"did":"blt.3.11t69frbsls00","eid":4109,"edata":"05018802","pdid":426,"seq":152}'
Processing MQTT: log/ble b'{"did":"blt.3.11t69frbsls00","eid":4109,"edata":"05016d02","pdid":426,"seq":165}'
Processing MQTT: log/ble b'{"did":"blt.3.11t69frbsls00","eid":4109,"edata":"05016e02","pdid":426,"seq":170}'
Processing MQTT: log/ble b'{"did":"blt.3.11t69frbsls00","eid":4109,"edata":"05017602","pdid":426,"seq":171}'
Processing MQTT: log/ble b'{"did":"blt.3.11t69frbsls00","eid":4109,"edata":"04017802","pdid":426,"seq":175}'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 775, in on_message
    self.process_ble_event_fix(payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1018, in process_ble_event_fix
    self._process_ble_event(device, payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1036, in _process_ble_event
    for entity in device['entities'].values():
KeyError: 'entities'

**Comment by AlexxIT** [comment]
Fixed in latest release
