### ISSUE TITLE
ZHA mode

### ISSUE THREAD

**Issue by frabar55** [AlexxIT/XiaomiGateway3#338]
Hi to everybody,
after passing to ZHA mode, the hub doesen't work properly: it results offline and therefore I cannot add anything. Where i'm wronging?
Thanks

Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:157
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 13:54:09 (2 occurrences)
Last logged: 13:54:15

192.168.178.49 | Device offline

**Comment by frabar55** [comment]
Just for info, Inoticed this error too. 

Logger: aiohttp.server
Source: custom_components/xiaomi_gateway3/util/elelabs_ezsp_utility.py:182
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 13:47:58 (2 occurrences)
Last logged: 13:48:14

Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 213, in post
    return await super().post(request, flow_id)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 199, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 257, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_gateway3/config_flow.py", line 233, in async_step_user
    if not await utils.update_zigbee_firmware(
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_gateway3/core/utils.py", line 192, in update_zigbee_firmware
    return await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_gateway3/core/utils.py", line 176, in _update_zigbee_firmware
    resp = utils.probe()
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_gateway3/util/elelabs_ezsp_utility.py", line 324, in probe
    ezsp_status = ezsp.initEzspProtocol()
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_gateway3/util/elelabs_ezsp_utility.py", line 300, in initEzspProtocol
    ash_status = self.ash.sendResetFrame()
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_gateway3/util/elelabs_ezsp_utility.py", line 182, in sendResetFrame
    status, response = self.getResponse()
ValueError: too many values to unpack (expected 2)

**Comment by frabar55** [comment]
Other usefull info, the following are the info give by ZHA about the coordinator:

EZSP = Silicon Labs EmberZNet protocol: Elelabs, HUSBZB-1, Telegesis
da ZHA
Zigbee info
IEEE: 84:2e:14:ff:fe:53:7c:b9
Nwk: 0x0000
Device Type: Coordinator
LQI: Unknown
RSSI: Unknown
Ultima visualizzazione: 2021-04-09T17:54:57
Sorgente di alimentazione: Mains
Quirk: bellows.zigbee.application.EZSPCoordinator

I believe that the Unknown values for LQI and RSSI are very strange!

**Comment by AlexxIT** [comment]
Reboot gateway

**Comment by frabar55** [comment]
Done! Nothing changed, info related to LQI and RSSI are the same

**Comment by AlexxIT** [comment]
Maybe you have wrong wifi router setting or unstabile connection. Maybe you have zigbee2mqtt that breakes ZHA mode

**Comment by AlexxIT** [comment]
Is the problem still relevant?

**Comment by frabar55** [comment]
I do not know because I do not use the GW3 for zigbee devices: it is inpossible to pair with it!
