### ISSUE TITLE
Processing MQTT error flood the log

### ISSUE THREAD

**Issue by MaoZ1993** [AlexxIT/XiaomiGateway3#365]
Hi there

After the recent HA update, 2021.6, I found this error show up in log every second. However, all functions of this integrator looks good, only this annoying error message keep showing up.

2021-06-14 21:42:16 ERROR (192.168.2.15_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: log/ble b'{"did":"blt.3.12tuogrgo5g01","eid":4100,"edata":"aa00","pdid":1115,"seq":131}'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 775, in on_message
    self.process_ble_event_fix(payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1018, in process_ble_event_fix
    self._process_ble_event(device, payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1036, in _process_ble_event
    for entity in device['entities'].values():
KeyError: 'entities'

**Comment by AlexxIT** [comment]
Duplicate #323
