### ISSUE TITLE
ZHA fails to load after Gateway reboot

### ISSUE THREAD

**Issue by akunia** [AlexxIT/XiaomiGateway3#368]
Hi,
I wanted to try ZHA intergration as I have some issues with zigbee2mqtt integration. At the beginning it worked well but when I rebooted the gateway, the ZHA integration is not working anymore. The BT devices still works OK.
Instead, I've noticed that when I enable Mosquitto and zigbee2mqtt Edge, I can control the devices from  zigbee2mqtt integration.
Does it means that XiaomiGateway3 changes the integration back to zigbee2mqtt from ZHA after reboot?
XiaomiGateway3 config page still indicates Zigbee Home Automation (ZHA) mode as active
Here the log after reboot:

```2021-06-27 18:49:02 ERROR (MainThread) [zigpy.application] Couldn't start application
2021-06-27 18:49:02 ERROR (MainThread) [homeassistant.components.zha.core.gateway] Couldn't start EZSP = Silicon Labs EmberZNet protocol: Elelabs, HUSBZB-1, Telegesis coordinator
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/serial/urlhandler/protocol_socket.py", line 63, in open
    self._socket = socket.create_connection(self.from_url(self.portstr), timeout=POLL_TIMEOUT)
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 157, in async_initialize
    self.application_controller = await app_controller_cls.new(
  File "/usr/local/lib/python3.8/site-packages/zigpy/application.py", line 69, in new
    await app.startup(auto_form)
  File "/usr/local/lib/python3.8/site-packages/bellows/zigbee/application.py", line 109, in startup
    self._ezsp = await bellows.ezsp.EZSP.initialize(self.config)
  File "/usr/local/lib/python3.8/site-packages/bellows/ezsp/__init__.py", line 78, in initialize
    await ezsp.connect()
  File "/usr/local/lib/python3.8/site-packages/bellows/ezsp/__init__.py", line 88, in connect
    self._gw = await bellows.uart.connect(self._config, self)
  File "/usr/local/lib/python3.8/site-packages/bellows/uart.py", line 363, in connect
    protocol, connection_done = await thread.run_coroutine_threadsafe(
  File "/usr/local/lib/python3.8/site-packages/bellows/uart.py", line 340, in _connect
    transport, protocol = await serial_asyncio.create_serial_connection(
  File "/usr/local/lib/python3.8/site-packages/serial_asyncio/__init__.py", line 445, in create_serial_connection
    serial_instance = serial.serial_for_url(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/serial/__init__.py", line 90, in serial_for_url
    instance.open()
  File "/usr/local/lib/python3.8/site-packages/serial/urlhandler/protocol_socket.py", line 66, in open
    raise SerialException("Could not open port {}: {}".format(self.portstr, msg))
serial.serialutil.SerialException: Could not open port socket://192.168.3.132:8888: [Errno 111] Connection refused
2021-06-27 18:49:02 WARNING (MainThread) [homeassistant.config_entries] Config entry 'socket://192.168.3.132:8888' for zha integration not ready yet: Could not open port socket://192.168.3.132:8888: [Errno 111] Connection refused; Retrying in background
```
I'm on FIRMWARE........: 1.5.0_0026 #20210518

**Comment by AlexxIT** [comment]
If you using ZHA and z2m simultaniosly - they can break each over

**Comment by akunia** [comment]
So what do you suggest @AlexxIT  to change from z2m to ZHA? 
Remove the integration, factory reset the gateway, add integration in MiHome mode and then change to ZHA ?
This way ZHA mode will be persistent over the reboots ?
Or something else?

**Comment by AlexxIT** [comment]
You need to shop z2m addon. Reboot gateway and Hass

**Comment by AlexxIT** [comment]
I think there are no more questions on this issue.
