### ISSUE TITLE
Can't render attributes

### ISSUE THREAD

**Issue by 0703005** [AlexxIT/XiaomiGateway3#383]
此错误来自自定义集成。

Logger: custom_components.xiaomi_gateway3.core.helpers
Source: custom_components/xiaomi_gateway3/core/utils.py:215
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 18:21:27 (144 occurrences)
Last logged: 18:21:28

Can't render attributes
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/helpers.py", line 210, in render_attributes_template
    attrs = attributes_template(self.hass).async_render({
  File "/config/custom_components/xiaomi_gateway3/core/utils.py", line 215, in attributes_template
    template.hass = hass
AttributeError: 'NoneType' object has no attribute 'hass'

**Comment by AlexxIT** [comment]
Fixed in latest master
