### ISSUE TITLE
not working after ha reboot 

### ISSUE THREAD

**Issue by chestarss** [AlexxIT/XiaomiGateway3#387]
2021-07-08 23:10:00 ERROR (192.168.124.22_main) [custom_components.xiaomi_gateway3.core.gateway3] 192.168.124.22 | Can't read devices: Telnet with password don't supported
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 546, in _get_devices
    shell = TelnetShell(self.host)
  File "/config/custom_components/xiaomi_gateway3/core/shell.py", line 56, in __init__
    raise Exception("Telnet with password don't supported")
Exception: Telnet with password don't supported

**Comment by AlexxIT** [comment]
Duplicate #370
