### ISSUE TITLE
Integration 'xiaomi_gateway3' does not support device automation triggers

### ISSUE THREAD

**Issue by Too51oll** [AlexxIT/XiaomiGateway3#394]
Logger: homeassistant.config
Source: components/device_automation/__init__.py:91
First occurred: 21:50:27 (8 occurrences)
Last logged: 21:50:27

Invalid config for [automation]: Integration 'xiaomi_gateway3' does not support device automation triggers (See /config/configuration.yaml, line 23).
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 85, in async_get_device_automation_platform
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/device_trigger.py", line 2, in <module>
    from homeassistant.components.device_automation import TRIGGER_BASE_SCHEMA
ImportError: cannot import name 'TRIGGER_BASE_SCHEMA' from 'homeassistant.components.device_automation' (/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/config.py", line 104, in _try_async_validate_config_item
    config = await async_validate_config_item(hass, config, full_config)
  File "/usr/src/homeassistant/homeassistant/components/automation/config.py", line 72, in async_validate_config_item
    config[CONF_TRIGGER] = await async_validate_trigger_config(
  File "/usr/src/homeassistant/homeassistant/helpers/trigger.py", line 49, in async_validate_trigger_config
    conf = await platform.async_validate_trigger_config(hass, conf)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/trigger.py", line 17, in async_validate_trigger_config
    platform = await async_get_device_automation_platform(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 91, in async_get_device_automation_platform
    raise InvalidDeviceAutomationConfig(
homeassistant.components.device_automation.exceptions.InvalidDeviceAutomationConfig: Integration 'xiaomi_gateway3' does not support device automation triggers

**Comment by Too51oll** [comment]
Hi,
I'm getting this error with the 2021.7.1 and 2021.7.2 of home assistant. All of the automations related to any devices attached to gateway are disabled. Devices attached to gateway do show up in home assistant with all of theirs properties showing as well as actions registering.

**Comment by palhaca** [comment]
me too!

**Comment by gentoair** [comment]
i have this Problem too

**Comment by nathbullen** [comment]
Having the same issue, just had to roll back to an older snapshot of HA because the Xiaomi sensors drive many of my automations!

**Comment by sthorley** [comment]
Same problem here.

**Comment by deco3690** [comment]
Same here. Previously, I I used many Device- . I have changed all to State based triggers (see below ref example), and my automations now work, but I still see the above warning on bootup. Any ideas?

(example from https://github.com/AlexxIT/XiaomiGateway3)
automation:
- alias: Turn off all lights
  trigger:
  - platform: state
    entity_id: sensor.0x158d0002fa99fd_action  # change to your button
    to: button_1_single  # change to your button state

**Comment by AlexxIT** [comment]
Duplicate #385
