### ISSUE TITLE
LYWSDCGQ

### ISSUE THREAD

**Issue by viiy** [AlexxIT/XiaomiGateway3#397]
К сожалению не отследил, начиная с какой версии перестали работать оба LYWSDCGQ
В MiHome они работают, подключение к x3 есть
В логе:
Processing MQTT: log/miio b'[20210718 11:04:51] [D] ot_agent_recv_handler_one(): fd:11, msg:{"method":"_async.ble_event","params":{"dev":{"did":"blt.3.124jain0g5s00","mac":"58:2D:34:39:23:57","pdid":426},"evt":[{"eid":4109,"edata":"e700a901"}],"frmCnt":53,"gwts":1626595491},"id":196277} length:195 bytes'

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 761, in on_message
    self.process_ble_event(data)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1001, in process_ble_event
    self._process_ble_event(device, payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1034, in _process_ble_event
    self.add_entity(domain, device, k)
  File "/config/custom_components/xiaomi_gateway3/core/helpers.py", line 45, in add_entity
    if self not in device['gateways']:
KeyError: 'gateways'

**Comment by AlexxIT** [comment]
Используется не последний релиз компонента
