### ISSUE TITLE
Loock（鹿客）Door lock Classic 2X state is incorrect

### ISSUE THREAD

**Issue by chenquanhao** [AlexxIT/XiaomiGateway3#446]
The door is closed at this time, but the bolt is not stuck.
——————————————————————————————————————————
```
Logger: custom_components.xiaomi_gateway3.core.gateway3
Source: custom_components/xiaomi_gateway3/core/bluetooth.py:339
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 09:10:15 (1 occurrences)
Last logged: 09:10:15

Processing MQTT: log/ble b'{"did":"1020068876","eid":7,"edata":"f37a812d61","pdid":1285,"seq":149}'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 889, in on_message
    self.process_ble_event_fix(payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 410, in process_ble_event_fix
    payload = bluetooth.parse_xiaomi_ble(data, data['pdid'])
  File "/config/custom_components/xiaomi_gateway3/core/bluetooth.py", line 339, in parse_xiaomi_ble
    'message': BLE_DOOR_ACTION[data[0]]
IndexError: list index out of range
```

**Comment by AlexxIT** [comment]
This is corrupted data from the gateway. I have added error checking in v1.4.0
