### ISSUE TITLE
Error: Unrecognized nodeId:6227

### ISSUE THREAD

**Issue by dumbodumbos** [AlexxIT/XiaomiGateway3#466]
Добрый. Есть проблема со шлюзом xiaomi gateway 3 ( ZNDMWG03LM Прошивка: 1.5.0_0026 )-  он переведен в режим z2m при помощи вашей интеграции. Версии всех аддонов последние. Переодически в логах z2m вылазит следующая ошибка. 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[13:26:07] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[13:26:08] INFO: MQTT available, fetching server detail ...
[13:26:08] INFO: Previous config file found, checking backup
[13:26:08] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[13:26:08] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:26:09] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.21.1 start
> node index.js
Assertion failed
Assertion failed
Assertion failed
(node:330) UnhandledPromiseRejectionWarning: Error: Unrecognized nodeId:6227
    at Driver.networkIdToEUI64 (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:454:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Driver.handleRouteError (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:319:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:330) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:330) UnhandledPromiseRejectionWarning: Error: Unrecognized nodeId:6227
    at Driver.networkIdToEUI64 (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:454:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at EZSPAdapter.processMessage (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:50:33)
(node:330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

При этом работа зигби парализует на 30-60 секунд. 

Так же иногда в процессе работы вылазит в логах Assertion failed - при это так же наблюдаются стоит сети зигби. 

Если надо еще какие то логи и тп - напишите -я выложу. Я очень заинтересован что бы все работало без сбоев ) 

Разместил данную проблему в телеграмм канале https://t.me/homassistant  - один из ответов у кого так же "Да, всё аналогично. Я вчера только поставил z2m и повесил пару устройств, остальные на zha работают без проблем."

**Comment by AlexxIT** [comment]
Это известная проблема z2m. Просите в проекте z2m доработать EZSP драйвер до устойчивой работы в режиме большого количества ошибок от Zigbee-чипа. К сожалению, у этого шлюза их очень много.

Например, драйвер ZHA гораздо устойчив к ошибкам.
