### ISSUE TITLE
ZNQBKG16LM switch  error?

### ISSUE THREAD

**Issue by hn315** [AlexxIT/XiaomiGateway3#480]
Xiaomi Gateway 3 for Home Assistant  V1.51
homeassistant     core-2021.10.4

2021-10-14 08:50:59 ERROR (192.168.1.19_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: zigbee/send b'{"cmd":"heartbeat","id":2000004690,"time":1634172881965,"rssi":-70,"params":[{"did":"lumi.158d0007952bce","time":1634172881965,"zseq":90,"res_list":[{"res_name":"8.0.2006","value":26},{"res_name":"8.0.2002","value":1},{"res_name":"8.0.2022","value":90},{"res_name":"8.0.2023","value":1},{"res_name":"8.0.2228","value":256},{"res_name":"8.0.2230","value":0},{"res_name":"4.1.85","value":0},{"res_name":"4.2.85","value":0},{"res_name":"4.3.85","value":0},{"res_name":"0.13.85","value":6.11},{"res_name":"0.11.85","value":237715},{"res_name":"0.12.85","value":0.02},{"res_name":"8.0.2231","value":0},{"res_name":"8.0.2007","value":120}]}]}'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 860, in on_message
    self.process_zigbee_message(payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1015, in process_zigbee_message
    elif prop == 'fw_ver' and param['value'] != device['fw_ver']:
KeyError: 'fw_ver'
2021-10-14 08:52:57 ERROR (MainThread) [frontend.js.latest.202110071] :0:0 Script error.
2021-10-14 08:56:11 ERROR (192.168.1.19_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: zigbee/send b'{"cmd":"heartbeat","id":2000004697,"time":1634173194049,"rssi":-70,"params":[{"did":"lumi.158d0007952bce","time":1634173194049,"zseq":91,"res_list":[{"res_name":"8.0.2006","value":26},{"res_name":"8.0.2002","value":1},{"res_name":"8.0.2022","value":90},{"res_name":"8.0.2023","value":1},{"res_name":"8.0.2228","value":256},{"res_name":"8.0.2230","value":0},{"res_name":"4.1.85","value":0},{"res_name":"4.2.85","value":0},{"res_name":"4.3.85","value":0},{"res_name":"0.13.85","value":6.11},{"res_name":"0.11.85","value":237583},{"res_name":"0.12.85","value":0.02},{"res_name":"8.0.2231","value":0},{"res_name":"8.0.2007","value":120}]}]}'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 860, in on_message
    self.process_zigbee_message(payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1015, in process_zigbee_message
    elif prop == 'fw_ver' and param['value'] != device['fw_ver']:
KeyError: 'fw_ver'
2021-10-14 09:03:59 ERROR (192.168.1.19_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: zigbee/send b'{"cmd":"heartbeat","id":2000004712,"time":1634173662310,"rssi":-70,"params":[{"did":"lumi.158d0007952bce","time":1634173662310,"zseq":99,"res_list":[{"res_name":"8.0.2006","value":26},{"res_name":"8.0.2002","value":1},{"res_name":"8.0.2022","value":90},{"res_name":"8.0.2023","value":1},{"res_name":"8.0.2228","value":256},{"res_name":"8.0.2230","value":0},{"res_name":"4.1.85","value":0},{"res_name":"4.2.85","value":0},{"res_name":"4.3.85","value":0},{"res_name":"0.13.85","value":6.34},{"res_name":"0.11.85","value":237741},{"res_name":"0.12.85","value":0.01},{"res_name":"8.0.2231","value":0},{"res_name":"8.0.2007","value":120}]}]}'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 860, in on_message
    self.process_zigbee_message(payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1015, in process_zigbee_message
    elif prop == 'fw_ver' and param['value'] != device['fw_ver']:
KeyError: 'fw_ver'

**Comment by binakot** [comment]
@hn315 Hello. Why did you closed both issue #480 and #482?

I have the same errors in logs:

```text
2021-11-01 20:27:12 ERROR (192.168.88.5_main) [custom_components.xiaomi_gateway3.core.gateway3] Processing MQTT: zigbee/send b'{"cmd":"heartbeat","id":2000000045,"time":1635798431515,"rssi":-32,"params":[{"did":"lumi.158d000488a28d","time":1635798431515,"zseq":63,"res_list":[{"res_name":"8.0.2008","value":3255},{"res_name":"8.0.2001","value":100},{"res_name":"8.0.2011","value":1},{"res_name":"8.0.2010","value":3},{"res_name":"8.0.2012","value":10},{"res_name":"8.0.2013","value":1},{"res_name":"8.0.2002","value":9},{"res_name":"8.0.2003","value":1},{"res_name":"8.0.2004","value":0},{"res_name":"8.0.2005","value":0},{"res_name":"8.0.2033","value":0},{"res_name":"0.1.85","value":2755},{"res_name":"0.2.85","value":5122},{"res_name":"0.3.85","value":100977},{"res_name":"8.0.2036","value":""},{"res_name":"8.0.2022","value":0},{"res_name":"8.0.2023","value":0},{"res_name":"8.0.2007","value":255}]}]}'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 860, in on_message
    self.process_zigbee_message(payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1015, in process_zigbee_message
    elif prop == 'fw_ver' and param['value'] != device['fw_ver']:
KeyError: 'fw_ver'
```

How did you fix that and what is this meaning?

HA 2021.10.6 (docker)
Xiaomi Gateway 3 ZNDMWG03LM (China version)
XiaomiGateway3 intergration v1.5.1 (latest)

**Comment by AlexxIT** [comment]
Issue may happens if you just add device to gate. You need to restart Hass

**Comment by binakot** [comment]
It means that we can just ignore that error? May be change code to down the level of error to warn or info?
