### ISSUE TITLE
Cannot switch zigbee2mqtt mode

### ISSUE THREAD

**Issue by hong9life** [AlexxIT/XiaomiGateway3#484]
Hi, 
First of all, thank you for your efforts.

I tried to switch zigbee2mqtt mode for deep dive into HA.
But I have a problem with switching Mode.

Please find attached image and sys info.
I had a look there was no log for switching mode.

Please have a look and help me.

![image](https://user-images.githubusercontent.com/40843092/137588705-46e5ddf6-4cbd-4122-85e5-cce0f549774f.jpeg)

2021-10-16 21:58:24  DEBUG    main          SysInfo: {'installation_type': 'Home Assistant Container', 'version': '2021.10.5', 'dev': False, 'hassio': False, 'virtualenv': False, 'python_version': '3.9.7', 'docker': True, 'user': 'root', 'arch': 'x86_64', 'timezone': 'Asia/Seoul', 'os_name': 'Linux', 'os_version': '4.4.180+'}

**Comment by AlexxIT** [comment]
Try to reboot gateway and switch mode multiple times.

**Comment by hong9life** [comment]
I found log from HA log

Logger: aiohttp.server
Source: custom_components/xiaomi_gateway3/util/elelabs_ezsp_utility.py:80 
Integration: Xiaomi Gateway 3 (documentation, issues) 
First occurred: 09:51:48 (3 occurrences) 
Last logged: 09:55:08

Error handling request
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/util/elelabs_ezsp_utility.py", line 73, in open
    self.serial = serial.Serial(port=self.port,
  File "/config/custom_components/xiaomi_gateway3/util/elelabs_ezsp_utility.py", line 33, in __init__
    self.s.connect(port)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 215, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 198, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 256, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/xiaomi_gateway3/config_flow.py", line 233, in async_step_user
    if not await utils.update_zigbee_firmware(
  File "/config/custom_components/xiaomi_gateway3/core/utils.py", line 216, in update_zigbee_firmware
    return await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_gateway3/core/utils.py", line 199, in _update_zigbee_firmware
    resp = utils.probe()
  File "/config/custom_components/xiaomi_gateway3/util/elelabs_ezsp_utility.py", line 320, in probe
    serialInterface.open()
  File "/config/custom_components/xiaomi_gateway3/util/elelabs_ezsp_utility.py", line 80, in open
    raise Exception("PORT ERROR: %s" % str(e))
Exception: PORT ERROR: [Errno 111] Connection refused

**Comment by AlexxIT** [comment]
Stay tuned for updates. Right now z2m is not working well. It can freeze. I'm working on it.
