### ISSUE TITLE
Zigbee2Mqtt mode errors

### ISSUE THREAD

**Issue by Slejpnir** [AlexxIT/XiaomiGateway3#486]
Hi, 
I use my gateway 3 in z2m mode. Everything works fine, but when I try to add the energy monitor, after a while all zigbee devices stop working, and this error continuously arises in the log:
```
(node:366) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'makeZDOframe' of undefined
    at Driver.makeZDOframe (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:467:26)
    at Driver.zdoRequest (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:421:30)
    at Object.func (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:271:50)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:42)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:22)
(node:366) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 986)
```

**Comment by AlexxIT** [comment]
zigbee2mqtt support the EFR32 chip in experimental mode. It is not recommended to use the gateway in this mode. Write to the zigbee2mqtt project about any issues
https://www.zigbee2mqtt.io/guide/adapters/#experimental
