### ISSUE TITLE
After update to v1.6.0-rc.2 component can lose connection to gateway

### ISSUE THREAD

**Issue by almazikv** [AlexxIT/XiaomiGateway3#497]
After update twice during one day component lost connection to gateway making all connected devices "unavailable". Integration reload immediately fixes the problem. Rolling back to stable 1.5.1

**Comment by AlexxIT** [comment]
You need to attach any details that may help to fix the problem

**Comment by rauko27** [comment]
Тоже столкнулся с похожей/подобной проблемой:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/xiaomi_gateway3/switch.py", line 34, in async_turn_on
    await self.device_send({self.attr: True})
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 540, in device_send
    await self.gw.lumi_send(self.device, payload)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/lumi.py", line 73, in lumi_send
    await self.mqtt.publish('zigbee/recv', payload)
  File "/config/custom_components/xiaomi_gateway3/core/mini_mqtt.py", line 205, in publish
    await self.writer.drain()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 375, in drain
    raise exc
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 105, in run_forever
    await self.mqtt.disconnect()
  File "/config/custom_components/xiaomi_gateway3/core/mini_mqtt.py", line 185, in disconnect
    await self.writer.drain()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 375, in drain
    raise exc
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 102, in run_forever
    async for msg in self.mqtt:
  File "/config/custom_components/xiaomi_gateway3/core/mini_mqtt.py", line 282, in __anext__
    raise e
  File "/config/custom_components/xiaomi_gateway3/core/mini_mqtt.py", line 259, in __anext__
    msg: MQTTMessage = await asyncio.wait_for(
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/config/custom_components/xiaomi_gateway3/core/mini_mqtt.py", line 208, in read
    raw = await self.reader.read(1)
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 684, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

После перезагрузки интеграции все работает какое-то время.

**Comment by AlexxIT** [comment]
@rauko27 соблюдаются все требования по настройке сети из документации

**Comment by rauko27** [comment]
@AlexxIT  - канал wifi зафиксирован на 11, 20 Мгц, ip статичен, одна подсеть. Прошивка хаба - 1.5.1_0032, HA 2021.9.6

На версии интеграции 1.5.* такого не наблюдалось - хотя в историях датчиков могли быть статусы Недоступны (примерно 1 раз в 2 часа), но они сами восстанавливались

**Comment by AlexxIT** [comment]
Да, на 1.5 другой код переподключения при обрывах, поэтому таких ошибок и нет. Вполне возможно обрывы были, но 1.5 просто о них не сообщала. В любом случае это обрыв соединения. Я попробую починить обработку ошибок при обрыве, но от самих обрывов это не спасёт
