### ISSUE TITLE
Empty device indentifiers

### ISSUE THREAD

**Issue by Zuz666** [AlexxIT/XiaomiGateway3#50]
Hi @AlexxIT!

After successful update to version v0.4.0 - 2020-09-27 got some errors like this:
```
2020-10-06 15:02:48 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "C:\p\HassWP\config\custom_components\xiaomi_gateway3\__init__.py", line 79, in device_registry_updated
    domain, mac = next(iter(hass_device.identifiers))
StopIteration

The above exception was the direct cause of the following exception:

RuntimeError: coroutine raised StopIteration
2020-10-06 15:02:48 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "C:\p\HassWP\config\custom_components\xiaomi_gateway3\__init__.py", line 79, in device_registry_updated
    domain, mac = next(iter(hass_device.identifiers))
StopIteration
```
On version "v0.5.0 - 2020-10-04" the problem also repeats.

These errors do not seem to affect the functionality of the component.
The component runs on the HassWP / W10Pro / Python 3.7.7 / fully updated.

**Comment by Zuz666** [comment]
@AlexxIT thanks! Just test it, works fine.
