### ISSUE TITLE
Aqara E1 Door & Window Sensor (MCCGQ14LM) - error adding entities

### ISSUE THREAD

**Issue by vtkach7** [AlexxIT/XiaomiGateway3#522]
Hi!

Home Assistant 2021.11.5 
Gateway: ZNDMWG03LM v1.6.1 Fw: 1.5.0_0102
Device: Aqara E1 Door & Window Sensor (MCCGQ14LM)

After pairing device, gateway beeps twice and notify of successful pairing. 
But no entities were created and error appears in the log:
The sensor works fine with MiHome. 

<img width="440" alt="Снимок экрана 2021-11-19 в 23 49 36" src="https://user-images.githubusercontent.com/73759689/142786562-bb50d94a-f04d-4450-b5cc-ba5dbfcbb82c.png">

```
Logger: homeassistant.components.sensor
Source: custom_components/xiaomi_gateway3/core/helpers.py:217
Integration: Sensor (documentation, issues)
First occurred: 21 November 2021, 17:41:01 (2 occurrences)
Last logged: 21 November 2021, 17:41:01

Error adding entities for domain sensor with platform xiaomi_gateway3
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 457, in _async_add_entity
    device_info = entity.device_info
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_gateway3/core/helpers.py", line 217, in device_info
    'model': self.device['device_model'],
KeyError: 'device_model'
```
```
2021-11-22 22:31:46,226 192.168.1.100 | lumi.54ef44100027f501 lumi.magnet.acn001 retain: {'1.4': '0.0.0_0004', '2.1': False, '3.1': 1, '3.2': 2995, 'alive': 1}
2021-11-22 22:31:46,307 192.168.1.100 | Setup zigbee device {'did': 'lumi.54ef44100027f501', 'mac': '0x54ef44100027f501', 'nwk': '0xb9a3', 'model': 'lumi.magnet.acn001', 'type': 'zigbee', 'fw_ver': 4, 'hw_ver': 0, 'mod_ver': 4, 'init': {'1.4': '0.0.0_0004', '2.1': False, '3.1': 1, '3.2': 2995, 'alive': 1}, 'online': True}
```

**Comment by AlexxIT** [comment]
Will add support to 2.0 version

**Comment by AlexxIT** [comment]
Added support. Will be in next beta/release version

**Comment by vtkach7** [comment]
Great news! Thanks a lot AlexxIT!
