### ISSUE TITLE
Issue with pairing QBKG39LM

### ISSUE THREAD

**Issue by artgru** [AlexxIT/XiaomiGateway3#526]
Hello,

Home Assistant 2021.11.2
Gateway: ZNDMWG03LM Fw: 1.5.0_0102 
I've reached a dead end here.
After performing an update of Xiaomi Gateway module in HA, I was kindly asked to update my firmware to the best supported version(zb stopped working) .
So I've updated my lumi gateway to the 1.5.0_0102, gateway is set to sg region if that matters.
But after I did this, I can't pair my Aqara E1 switch QBKG39LM
Pairing results in three beeps, the device is being added (my old entities for it are active) for a second or two, then the device is being removed again...

This is how it looks like in the logs
```
2021-11-23 22:12:47  DEBUG    gateway3      10.69.1.200 | 332643664 lumi.gateway.mgl03 <= {'added_device': {'did': 'lumi.54ef44100017eeb8', 'mac': '54ef44100017eeb8', 'model': 'lumi.switch.b2lc04', 'version': '0.0.0_0020', 'zb_ver': '3.0', 'joined_type': 1}} [?]
2021-11-23 22:12:47  DEBUG    gateway3      10.69.1.200 | Setup zigbee device {'did': 'lumi.54ef44100017eeb8', 'mac': '0x54ef44100017eeb8', 'model': 'lumi.switch.b2lc04', 'version': '0.0.0_0020', 'zb_ver': '3.0', 'joined_type': 1, 'type': 'zigbee', 'init': {'added_device': {...}}, 'nwk': '0xffff', 'fw_ver': 0, 'online': True}
2021-11-23 22:12:47  DEBUG    gateway3      10.69.1.200 | 332643664 lumi.gateway.mgl03 <= {'device_model': 'lumi.switch.b2lc04'} [0.04]
2021-11-23 22:12:47  DEBUG    gateway3      10.69.1.200 | lumi.54ef44100017eeb8 lumi.switch.b2lc04 <= {'8.0.2086': '00000000191821a2'} [0.0]
2021-11-23 22:12:48  DEBUG    gateway3      10.69.1.200 | 332643664 lumi.gateway.mgl03 <= {'8.0.2104': {'model': 'lumi.switch.b2lc04', 'pdid': 71637, 'template_id': ''}} [0.01]
2021-11-23 22:12:48  DEBUG    gateway3      10.69.1.200 | lumi.54ef44100017eeb8 lumi.switch.b2lc04 <= {'channel 2': False} [0.0]
2021-11-23 22:12:48  DEBUG    gateway3      10.69.1.200 | lumi.54ef44100017eeb8 lumi.switch.b2lc04 <= {'8.0.2087': '8006FEA38B20014D6978040A54A05043'} [0.0]
2021-11-23 22:12:48  DEBUG    gateway3      10.69.1.200 | 332643664 lumi.gateway.mgl03 <= {'pairing_start': 0} [0.0]
2021-11-23 22:12:48  DEBUG    gateway3      10.69.1.200 | lumi.54ef44100017eeb8 lumi.switch.b2lc04 <= {'8.0.2088': 'a8ac21ef9d7ab0e6536026f774ba0a0a'} [0.05]
2021-11-23 22:12:49  DEBUG    gateway3      10.69.1.200 | 332643664 lumi.gateway.mgl03 <= {'removed_did': 'lumi.54ef44100017eeb8'} [0.01]
```

I tried to manually pair with the remote.send_command but without success.

What else can I do here?
Edit found more logs (but got them just once) 
Processing MQTT: zigbee/send b'{"cmd":"report","id":2000000207,"did":"lumi.54ef44100017eeb8","dev_src":"0","time":1637712400355,"rssi":-48,"mi_spec":[{"siid":8,"eiid":1,"arguments":[]}]}'
Processing MQTT: zigbee/send b'{"cmd":"report","id":2000000217,"did":"lumi.54ef44100017eeb8","dev_src":"0","time":1637712429415,"rssi":-47,"mi_spec":[{"siid":8,"eiid":1,"arguments":[]}]}'

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 620, in on_message
    await self.process_zigbee_message(msg.json)
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 1063, in process_zigbee_message
    for entity in device['entities'].values():
RuntimeError: dictionary changed size during iteration

**Comment by zvldz** [comment]
What version of component ?

**Comment by artgru** [comment]
I've updated it to the newest possible through the auto-updater => 1.6.2

**Comment by zvldz** [comment]
I have this switch and it works.
Are you adding a switch via component or via MiHome ?

**Comment by artgru** [comment]
MiHome doesn't support it afaik. before the firmware update I used component to pair the device.
I still have unavailable entities in the configuration. When I click pair, the device gets paired for about 3 seconds, I can even issue a click and gateway removes the device.

**Comment by zvldz** [comment]
Maybe problem in the region.
What region is the gateway connected to?

MiHome mod for android by vevs supports.
https://www.kapiba.ru/2017/11/mi-home.html

**Comment by artgru** [comment]
I'm on sg at the moment. Yep Im using vevs version of MiHome.
Should I change the region?

**Comment by zvldz** [comment]
try cn region

**Comment by artgru** [comment]
Okay, changing to CN helped. Didn't know I cannot pair the device in another region. I thought pairing through component should work regardless of the selected region.
