### ISSUE TITLE
BLE Thermometer cannot be added in Automation as Device trigger

### ISSUE THREAD

**Issue by Chupaka** [AlexxIT/XiaomiGateway3#555]
Xiaomi Mi Temperature and Humidity Monitor 2 (LYWSD03MMC) connected via Xiaomi Gateway 3.

When I try to create an automation and pick this device in "Trigger type: Device", the Trigger line shows "Unknown trigger"
![image](https://user-images.githubusercontent.com/3432808/145695317-f1a950de-3bda-485c-a9e0-c796b9060bcd.png)
And in Logs, I see the following error:
```
Dec 11 23:55:40 ooboontoo hass[2180659]:                                                  2021-12-11 23:55:40 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139917053182016] Error handling message: Unknown error
Dec 11 23:55:40 ooboontoo hass[2180659]: Traceback (most recent call last):
Dec 11 23:55:40 ooboontoo hass[2180659]:   File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
Dec 11 23:55:40 ooboontoo hass[2180659]:     await func(hass, connection, msg)
Dec 11 23:55:40 ooboontoo hass[2180659]:   File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/components/device_automation/__init__.py", line 239, in with_error_handling
Dec 11 23:55:40 ooboontoo hass[2180659]:     await func(hass, connection, msg)
Dec 11 23:55:40 ooboontoo hass[2180659]:   File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/components/device_automation/__init__.py", line 293, in websocket_device_automation_list_triggers
Dec 11 23:55:40 ooboontoo hass[2180659]:     triggers = (await _async_get_device_automations(hass, "trigger", [device_id])).get(
Dec 11 23:55:40 ooboontoo hass[2180659]:   File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/components/device_automation/__init__.py", line 175, in _async_get_device_automations
Dec 11 23:55:40 ooboontoo hass[2180659]:     for domain_results in await asyncio.gather(
Dec 11 23:55:40 ooboontoo hass[2180659]:   File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/components/device_automation/__init__.py", line 136, in _async_get_device_automations_from_domain
Dec 11 23:55:40 ooboontoo hass[2180659]:     return await asyncio.gather(
Dec 11 23:55:40 ooboontoo hass[2180659]:   File "/home/homeassistant/.homeassistant/custom_components/xiaomi_gateway3/device_trigger.py", line 59, in async_get_triggers
Dec 11 23:55:40 ooboontoo hass[2180659]:     buttons = zigbee.get_buttons(device.model)
Dec 11 23:55:40 ooboontoo hass[2180659]:   File "/home/homeassistant/.homeassistant/custom_components/xiaomi_gateway3/core/zigbee.py", line 646, in get_buttons
Dec 11 23:55:40 ooboontoo hass[2180659]:     zigbee_model, _ = device_model.split(' ', 1)
Dec 11 23:55:40 ooboontoo hass[2180659]: ValueError: not enough values to unpack (expected 2, got 1)
```
That device is connected via BLE, not Zigbee...

**Comment by AlexxIT** [comment]
Fixed in latest release
