### ISSUE TITLE
can't turn on Mode ZHA or zigbee2mqtt

### ISSUE THREAD

**Issue by Sorien** [AlexxIT/XiaomiGateway3#571]
can't turn on Mode ZHA or zigbee2mqtt [ADV] 

![image](https://user-images.githubusercontent.com/1270275/146671502-ac6c2c93-ac56-46d5-8e85-93e32bb776ea.png)

Home Assistant 2021.12.3,  Xiaomi Gateway 3: 1.6.5

```
Traceback (most recent call last):
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 215, in post
    return await super().post(request, flow_id)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/var/snap/home-assistant-snap/452/custom_components/xiaomi_gateway3/config_flow.py", line 224, in async_step_user
    if not await utils.update_zigbee_firmware(
  File "/var/snap/home-assistant-snap/452/custom_components/xiaomi_gateway3/core/utils.py", line 261, in update_zigbee_firmware
    await async_process_requirements(hass, DOMAIN, ['xmodem==0.4.6'])
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/requirements.py", line 164, in async_process_requirements
    await _async_process_requirements(
  File "/snap/home-assistant-snap/452/lib/python3.9/site-packages/homeassistant/requirements.py", line 196, in _async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for xiaomi_gateway3 not found: ['xmodem==0.4.6'].
```
I was using ZAH to control non Xiaomi Zigbee devices, but after recent update from some old home assistant version can't turn it on anymore

**Comment by Sorien** [comment]
reinstall of Xiaomi Gateway 3 integration solved that problem, :/ ... sorry for the noise
