### ISSUE TITLE
Can't install via Config - Integration

### ISSUE THREAD

**Issue by sshalyminov** [AlexxIT/XiaomiGateway3#58]
Can't install via Config - Integration. On name press dialogue with integrations list just re-appears. 
Here is error in server's log:

```
Logger: aiohttp.server
Source: custom_components/xiaomi_gateway3/config_flow.py:51
First occurred: 22:15:49 (1 occurrences)
Last logged: 22:15:49

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 131, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 204, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/xiaomi_gateway3/config_flow.py", line 51, in async_step_user
    if 'devices' in self.hass.data[DOMAIN]:
KeyError: 'xiaomi_gateway3'
```

**Comment by Zuz666** [comment]
Yep, have the same issue but different error:
```
020-10-12 00:21:32 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration xiaomi_gateway3: No module named 'asyncio.exceptions'
```
Primary interrogation not deleted before attempt.

asyncio.exceptions on python-3.7.7 (HassWP) not present.

**Comment by AlexxIT** [comment]
Fixed in **v0.6.1**

**Comment by Zuz666** [comment]
@AlexxIT yes, works fine but you need update requirements to python 3.8 (in 3.7 no module named 'asyncio.exceptions').

**Comment by sshalyminov** [comment]
0.6.1 works fine for me

**Comment by 000al000** [comment]
0.6.1 not working on python 3.7

**Comment by Zuz666** [comment]
> 0.6.1 not working on python 3.7
On 3.7.7 works fine.

**Comment by zvldz** [comment]
> > 0.6.1 not working on python 3.7
> > On 3.7.7 works fine.

https://www.home-assistant.io/blog/#python-37-deprecated
