### ISSUE TITLE
Setup failed for xiaomi_gateway3

### ISSUE THREAD

**Issue by maxifly** [AlexxIT/XiaomiGateway3#620]
After update HA and this integration on last versions (2022.2.3 and v1.6.5) I have error in log when restart HA server:

"Setup failed for xiaomi_gateway3: Integration not found."

**Comment by AlexxIT** [comment]
This is not integration problem

**Comment by maxifly** [comment]
after update integration to v2.0.1 error was gone

**Comment by EvgenySkn** [comment]
@AlexxIT I have the same problem after updating till 2.1.0 version of this integration. On the version 2.0.9 or 2.0.10 everything is OK. HassWP v 2021.12.10. Can you fix it?

```
Logger: homeassistant.setup
Source: C:\HassWP_2021.12.10\python-3.8.10\lib\site-packages\homeassistant\setup.py:186
First occurred: 09:57:29 (1 occurrences)
Last logged: 09:57:29

Setup failed for xiaomi_gateway3: unknown error
Traceback (most recent call last):
  File "C:\HassWP_2021.12.10\python-3.8.10\lib\site-packages\homeassistant\setup.py", line 181, in _async_setup_component
    component = integration.get_component()
  File "C:\HassWP_2021.12.10\python-3.8.10\lib\site-packages\hass_win\__main__.py", line 119, in wrapper
    return func(integration)
  File "C:\HassWP_2021.12.10\python-3.8.10\lib\site-packages\homeassistant\loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "C:\HassWP_2021.12.10\python-3.8.10\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HassWP_2021.12.10\config\custom_components\xiaomi_gateway3\__init__.py", line 18, in <module>
    from . import system_health
  File "C:\HassWP_2021.12.10\config\custom_components\xiaomi_gateway3\system_health.py", line 26, in <module>
    async def system_health_info(hass: HomeAssistant) -> dict[str, Any]:
TypeError: 'type' object is not subscriptable
```

**Comment by AlexxIT** [comment]
Try master version
