### ISSUE TITLE
update the latest code ERROR

### ISSUE THREAD

**Issue by maybeloveu** [AlexxIT/XiaomiGateway3#641]
`192.168.3.52 | Processing MQTT: log/miio b'\x1b[0;32m2022:02:10:17:25:56.585 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"_async.ble_event","params":{"dev":{"did":"blt.3.18kee73qclg00","mac":"54:EF:44:E6:A2:A7","pdid":2701},"evt":[{"eid":15,"edata":"000100"}],"frmCnt":6,"gwts":1644485156},"id":19652} length:190 bytes\x1b[0m'
192.168.3.52 | Processing MQTT: log/miio b'\x1b[0;32m2022:02:10:17:25:59.154 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"_async.ble_event","params":{"dev":{"did":"blt.3.18kee73qclg00","mac":"54:EF:44:E6:A2:A7","pdid":2701},"evt":[{"eid":4119,"edata":"00000000"}],"frmCnt":7,"gwts":1644485159},"id":19653} length:194 bytes\x1b[0m'
192.168.3.52 | Processing MQTT: log/miio b'\x1b[0;32m2022:02:10:17:26:02.704 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"_async.ble_event","params":{"dev":{"did":"blt.3.18kee73qclg00","mac":"54:EF:44:E6:A2:A7","pdid":2701},"evt":[{"eid":4123,"edata":"00000000"}],"frmCnt":8,"gwts":1644485162},"id":19654} length:194 bytes\x1b[0m'
192.168.3.52 | Processing MQTT: log/miio b'\x1b[0;32m2022:02:10:17:26:14.654 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"properties_changed","params":[{"did":"1046237301","siid":2,"piid":2,"tid":128,"value":0}],"id":19658} length:112 bytes\x1b[0m'
192.168.3.52 | Processing MQTT: log/miio b'\x1b[0;32m2022:02:10:17:26:31.774 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"_async.ble_event","params":{"dev":{"did":"blt.3.18kee73qclg00","mac":"54:EF:44:E6:A2:A7","pdid":2701},"evt":[{"eid":4123,"edata":"1e000000"}],"frmCnt":10,"gwts":1644485191},"id":19663} length:195 bytes\x1b[0m'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 149, in mqtt_message
    await self.dispatcher_send(SIGNAL_MQTT_PUB, msg=msg)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/base.py", line 108, in dispatcher_send
    await handler(**kwargs)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/ble.py", line 53, in ble_mqtt_publish
    for data in utils.decode_miio_json(
NameError: name 'utils' is not defined`

**Comment by maybeloveu** [comment]
#642
