### ISSUE TITLE
lumi params decode failure

### ISSUE THREAD

**Issue by qiaoqiao1235** [AlexxIT/XiaomiGateway3#687]
```
2022-03-02 11:04:56 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.50.100 | Processing MQTT: zigbee/send b'{"cmd":"report","id":2000000007,"did":"lumi.0","time":1646190296294,"rssi":0,"zseq":0,"params":[{"res_name":"8.0.2155","value":1}],"dev_src":"0"}'
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 150, in mqtt_message
await self.dispatcher_send(SIGNAL_MQTT_PUB, msg=msg)
File "/config/custom_components/xiaomi_gateway3/core/gateway/base.py", line 109, in dispatcher_send
await handler(**kwargs)
File "/config/custom_components/xiaomi_gateway3/core/gateway/lumi.py", line 61, in lumi_mqtt_publish
await self.lumi_process_lumi(msg.json)
File "/config/custom_components/xiaomi_gateway3/core/gateway/lumi.py", line 108, in lumi_process_lumi
payload = device.decode_lumi(data[k])
File "/config/custom_components/xiaomi_gateway3/core/device.py", line 332, in decode_lumi
conv.decode(self, payload, v)
File "/config/custom_components/xiaomi_gateway3/core/converters/base.py", line 212, in decode
value = json.loads(value)
File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not int
```

**Comment by AlexxIT** [comment]
Fixed in master version. Will be in next release
