### ISSUE TITLE
Can't update to 2022.3.3 (from 2022.3.1)

### ISSUE THREAD

**Issue by Pandabeer40** [AlexxIT/XiaomiGateway3#698]
here is the code from supervisory:
```
22-03-09 21:30:01 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 229, in update
    await _update(version)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 207, in _update
    await self.instance.update(
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
asyncio.exceptions.TimeoutError
22-03-09 21:30:01 WARNING (MainThread) [supervisor.utils.codenotary] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded"
```

```
22-03-09 21:33:42 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 229, in update
    await _update(version)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 207, in _update
    await self.instance.update(
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
asyncio.exceptions.TimeoutError
22-03-09 21:33:52 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
```

What is going wrong?

**Comment by Pandabeer40** [comment]
sorry - wrong page
