### ISSUE TITLE
Issue on connecting to gateway

### ISSUE THREAD

**Issue by auliarshad** [AlexxIT/XiaomiGateway3#708]
Today I had a power outage, when my server back up online gateways started not producing any data.
When I tried to reinstall the integration (remove from hacs, restart, add again), the gateway shows no entities. Log shows there is error :

![image](https://user-images.githubusercontent.com/42366729/158551523-18f2bceb-fab2-4ad3-967c-f5f72f2c50fc.png)

```
Logger: custom_components.xiaomi_gateway3.core.gateway
Source: custom_components/xiaomi_gateway3/core/shell/__init__.py:30
Integration: Xiaomi Gateway 3 ([documentation](https://github.com/AlexxIT/XiaomiGateway3), [issues](https://github.com/AlexxIT/XiaomiGateway3/issues))
First occurred: 13:58:24 (2 occurrences)
Last logged: 13:59:27

192.168.123.19 | Can't prepare gateway
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 162, in prepare_gateway
    sh = await shell.connect(self.host)
  File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 30, in connect
    resp: bytes = await asyncio.wait_for(coro, 3)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

XiaomiGateway3 version `2.0.7`
Gateway version `1.5.0_0102`

Kindly help, thank you 🙏

**Comment by auliarshad** [comment]
Closing this since found out that previously I set HA IP to static, not sure how this impacting discovery to the gateway but after I set to DHCP it can detect the gateway again. 🙏
