### ISSUE TITLE
BLE / BLE mesh not working on 0.7-0.7.1 (may be device depended problem)

### ISSUE THREAD

**Issue by Zuz666** [AlexxIT/XiaomiGateway3#74]
After update to version https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v0.7.1 got error:

```
2020-10-19 12:46:08 ERROR (Thread-4) [miio.miioprotocol] Got error when receiving: timed out
2020-10-19 12:46:08 ERROR (Thread-4) [custom_components.xiaomi_gateway3.gateway3] Bluetooth loop error: No response from the device
Traceback (most recent call last):
  File "C:\p\HassWP\config\deps\Python37\site-packages\miio\miioprotocol.py", line 192, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\p\HassWP\config\deps\Python37\site-packages\miio\miioprotocol.py", line 192, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\p\HassWP\config\deps\Python37\site-packages\miio\miioprotocol.py", line 192, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\p\HassWP\config\deps\Python37\site-packages\miio\miioprotocol.py", line 192, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\p\HassWP\config\custom_components\xiaomi_gateway3\gateway3.py", line 710, in run
    self.get_devices(telnet)
  File "C:\p\HassWP\config\custom_components\xiaomi_gateway3\gateway3.py", line 773, in get_devices
    resp = self.gw.miio.send('get_properties', payload)
  File "C:\p\HassWP\config\deps\Python37\site-packages\miio\device.py", line 147, in send
    command, parameters, retry_count, extra_parameters=extra_parameters
  File "C:\p\HassWP\config\deps\Python37\site-packages\miio\miioprotocol.py", line 236, in send
    extra_parameters=extra_parameters,
  File "C:\p\HassWP\config\deps\Python37\site-packages\miio\miioprotocol.py", line 236, in send
    extra_parameters=extra_parameters,
  File "C:\p\HassWP\config\deps\Python37\site-packages\miio\miioprotocol.py", line 236, in send
    extra_parameters=extra_parameters,
  File "C:\p\HassWP\config\deps\Python37\site-packages\miio\miioprotocol.py", line 240, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
```

On previous versions (checked some version ago with debug bluetooth) no error like this.

On packets capturing I don't see any timeouts or packet drop. I understand packet flow and protocol, and I can understand what's going on to make this conclusion.

Extract from packets flow:
```

1.
Data: \r\r\n
Data: rlxlinux login: 

2.
Data: admin\r\n

3.
Data: admin\r\n
Data: Lumi Linux version 3.0\r\n
.... Full banner...

4.
Data: cat /data/miio/mible_local.db | base64\r\n

5. 
Data: cat /data/miio/mible_local.db | base64\r\n

6.


Many many packets like this:
Data: U1FMaXRlIGZvcm1hdCAzABAAAQEAQCAgAAATPwAAABMAAAAAAAAAAAAAAAsAAAAEAAAAAAAAAAAA\r\n


Some of them:
Data: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n

```

150+
...
Data: MDAwMDNlNDAwMDAwMDAwMTAwMA==\r\n
Data: # 

**Environment:**
lumi.gateway.mgl03 / firmware version: 1.4.6_0030
Home Assistant 0.116.4 / python-3.7.7 / HassWP

Rebooting the device and full power off / on cycle does not solve the problem.
Just connecting to gateway via telnet works fine.

**Comment by AlexxIT** [comment]
Same problem was when the user in Mi Home had old Mesh devices. Which are actually gone.

**Comment by Zuz666** [comment]
@AlexxIT thanks, but I dont have any old Mesh devices (as I understand it, it's some old entries in the gateway database).
Have one Yeelight Mesh Hub (turned off now) and one mesh BLE group (non standard devices which may have a value).
I checked the code and I'm sure that the problem is not in telnet connection. The database of BLE devices is read correctly.

On 'get_properties' miio.send we got error:
```python
        # 3 attempts to get actual data
        for _ in range(3):
            resp = self.gw.miio.send('get_properties', payload)
            if all(p['code'] == 0 for p in resp):
                break
            time.sleep(1)
```
On miio debug level payload looks like this:
```
2020-10-19 19:18:57 DEBUG (Thread-4) [miio.miioprotocol] 192.168.1.108:54321 >>: {'id': 690605, 'method': 'get_properties', 'params': [{'did': '1040169839', 'siid': 2, 'piid': 1}, {'did': '1040169839', 'siid': 2, 'piid': 2}, {'did': '1040169839', 'siid': 2, 'piid': 3}, {'did': '1040173158', 'siid': 2, 'piid': 1}, {'did': '1040173158', 'siid': 2, 'piid': 2}, {'did': '1040173158', 'siid': 2, 'piid': 3}, {'did': '1040172421', 'siid': 2, 'piid': 1}, {'did': '1040172421', 'siid': 2, 'piid': 2}, {'did': '1040172421', 'siid': 2, 'piid': 3}, {'did': '1041530390', 'siid': 2, 'piid': 1}, {'did': '1041530390', 'siid': 2, 'piid': 2}, {'did': '1041530390', 'siid': 2, 'piid': 3}, {'did': '1041275565', 'siid': 2, 'piid': 1}, {'did': '1041275565', 'siid': 2, 'piid': 2}, {'did': '1041275565', 'siid': 2, 'piid': 3}, {'did': '1040168859', 'siid': 2, 'piid': 1}, {'did': '1040168859', 'siid': 2, 'piid': 2}, {'did': '1040168859', 'siid': 2, 'piid': 3}, {'did': '1041177230', 'siid': 2, 'piid': 1}, {'did': '1041177230', 'siid': 2, 'piid': 2}, {'did': '1041177230', 'siid': 2, 'piid': 3}, {'did': '1041181216', 'siid': 2, 'piid': 1}, {'did': '1041181216', 'siid': 2, 'piid': 2}, {'did': '1041181216', 'siid': 2, 'piid': 3}]}
```

Where 8 device entities and i have 8 active BLE Mesh devices. Two of them in  BLE Mesh group.
I'll try deleting this group and check the result.

**Comment by Zuz666** [comment]
@AlexxIT not it's not solve the problem. After removing BLE Mesh light group no error but integration is not work. After gateway was rebooted the error is back.

**Comment by Zuz666** [comment]
@AlexxIT whe i run command like this 
```
miiocli.exe gateway --ip 192.168.1.108 --token xxxxxxxxxxxxxxxxxxxxxxxx raw_command get_properties "[{'did': '1040172421', 'siid': 2, 'piid': 1}]"
```
it works fine.

When use more params (2-3 works fine) it's failed and miIO stop working until device reboot (gateway stop response to all requests only handshake works).

**Comment by Zuz666** [comment]
@AlexxIT ok, i just rewrite code to do things one by one and it works, but....

```diff
index bf363a6..57c5f96 100644
--- a/custom_components/xiaomi_gateway3/gateway3.py
+++ b/custom_components/xiaomi_gateway3/gateway3.py
@@ -762,21 +762,17 @@ class GatewayBLE(Thread):
 
             self.gw.devices[did] = device
 
-            payload += [{'did': did, 'siid': 2, 'piid': p}
+            payload = [{'did': did, 'siid': 2, 'piid': p}
                         for p in range(1, 4)]
-
-        if not payload:
-            return
-
-        # 3 attempts to get actual data
-        for _ in range(3):
-            resp = self.gw.miio.send('get_properties', payload)
-            if all(p['code'] == 0 for p in resp):
-                break
-            time.sleep(1)
-
-        self.gw.process_mesh_data(resp)
-
+            if payload:
+              # 3 attempts to get actual data
+              for _ in range(3):
+                  resp = self.gw.miio.send('get_properties', payload)
+                  if all(p['code'] == 0 for p in resp):
+                      break
+                  time.sleep(1)
+        
+              self.gw.process_mesh_data(resp)
 
 def is_gw3(host: str, token: str) -> Optional[str]:
     try:
```

**Comment by Zuz666** [comment]
Just checked code again, in this case: ```if payload:``` not needed...

**Comment by AlexxIT** [comment]
@Zuz666 I've already rewritten this part, but not finished yet for production.

**Comment by Zuz666** [comment]
@AlexxIT sounds good! )

**Comment by Zuz666** [comment]
@AlexxIT works fine in https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v0.7.2
