### ISSUE TITLE
Error unloading entry Gateway Upstairs for light

### ISSUE THREAD

**Issue by admiralalec** [AlexxIT/XiaomiGateway3#742]
After a short while the Gateway integration crashes - devices become unavailable. 

Hass log entry below: 

```
Error unloading entry Gateway Upstairs for light

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 554, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 174, in async_unload_entry
    await platform.async_reset()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 628, in async_reset
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in async_remove
    await self.async_will_remove_from_hass()
  File "/config/custom_components/xiaomi_gateway3/light.py", line 161, in async_will_remove_from_hass
    child.entities.pop(self.attr)
KeyError: 'group'
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.1.0
