### ISSUE TITLE
Still issue after update HA to core-2022.4.7

### ISSUE THREAD

**Issue by Zewe77** [AlexxIT/XiaomiGateway3#743]
I am running the latest integration and FW 1.5.0_0102 and everything works in 4.6 but stops when updating to 4.7
the issue I can find is in the HA log during startup but can't figure out why?

2022-05-03 10:19:06 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform xiaomi_gateway3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 799, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 454, in state
    assert native_unit_of_measurement
AssertionError

have added the debug logs but don't get anything from them?
can someone smarter than me please shed some light on this.
Thank you!

**Comment by Zewe77** [comment]
It is solved....
after update from supervisor from 2022.04 to 2022.05 and a restart it works!

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
