### ISSUE TITLE
Entity cannot be added a second time to an entity platform

### ISSUE THREAD

**Issue by yangye1n** [AlexxIT/XiaomiGateway3#764]
In recent days, some devices connected to the Xiaomi multi-mode gateway through ZigBee have reported the above errors. Please help to find out the reason.

Every time homeassistant restarts, the devices (such as temperature and humidity sensors and door magnetic sensors) connected to Xiaomi multi-mode gateway through BLE are displayed as unavailable. I wonder whether it is possible to record the status of the sensors before homeassistant restarts and assign values after restart?

My English is not very good, the expression may not be very clear and accurate, please understand!

Looking forward to your reply and solution. Thank you so much!

**Comment by Viper7000** [comment]
I had some problems with my BLE devices about a month ago. After the reboot, the devices are unavailable. Then I kind of deleted all the devices and registered again. I noticed that most of the devices have changed the token! Out of 10 devices, 8 received a new token. It looks like Xiaomi changed the tokens. Only 2 devices connected to Xiaomi last had the same token.
I hope this will be useful to you

**Comment by JachinY** [comment]
> 大约一个月前，我的 BLE 设备出现了一些问题。重启后，设备不可用。然后我删除了所有设备并重新注册。我注意到大多数设备都更改了令牌！在 10 台设备中，有 8 台收到了新令牌。看起来小米改变了代币。最后连接到小米的只有 2 台设备具有相同的令牌。 我希望这对你有用

Actually, when state of ble devices changed, it will shows new state on HA, but it will always show unavailable/unknown until state changed after HA restart

**Comment by AlexxIT** [comment]
Are you using supported gateway firmware?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant

**Comment by sephrioth** [comment]
I  recently bought a new gateway, the previous one is the multimode gateway (1.5.4_xxxx) and the new one is multimode gateway 2 (1.0.3_xxxx) , then I added the new one to HA.  

The issue is all entities in multimode gateway 2 turned to unavailable in a few minutes, or if I try reload the integration, the entities became unavailable  immediately. Then I tried  to remove the new one from HA, but the problem then occurred in old gateway.

Here is the sample error logs.

2023-12-27 16:28:01 | stdout | homeassistant.exceptions.HomeAssistantError: Entity 'sensor.balcony_humidity_gw3' cannot be added a second time to an entity platform [0m
-- | -- | --
2023-12-27 16:28:01 | stdout | raise HomeAssistantError(
2023-12-27 16:28:01 | stdout | File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in add_to_platform_start
2023-12-27 16:28:01 | stdout | super().add_to_platform_start(hass, platform, parallel_updates)
2023-12-27 16:28:01 | stdout | File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 215, in add_to_platform_start
2023-12-27 16:28:01 | stdout | entity.add_to_platform_start(
2023-12-27 16:28:01 | stdout | File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 565, in _async_add_entity
2023-12-27 16:28:01 | stdout | await asyncio.gather(*tasks)
2023-12-27 16:28:01 | stdout | File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
2023-12-27 16:28:01 | stdout | Traceback (most recent call last):
2023-12-27 16:28:01 | stdout | [31m2023-12-28 00:28:01.565 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
2023-12-27 16:28:01 | stdout | homeassistant.exceptions.HomeAssistantError: Entity 'sensor.balcony_temperature_gw3' cannot be added a second time to an entity platform [0m


After a HA restart, the entities are back but will be gone in few minutes.

**Comment by EvgenyBash** [comment]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:533
Integration: Сенсор (documentation, issues)
First occurred: 9 февраля 2024 г. в 19:26:38 (40 occurrences)
Last logged: 19:47:02

Error adding entities for domain sensor with platform xiaomi_gateway3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 589, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 240, in add_to_platform_start
    super().add_to_platform_start(hass, platform, parallel_updates)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1293, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity 'sensor.a4c138b9eecb_temperature' cannot be added a second time to an entity platform

**Comment by shawn996** [comment]
#1090 

> Logger: homeassistant.components.binary_sensor
> Source: helpers/entity_platform.py:533
> Integration: 二元传感器 ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
> First occurred: 19:36:31 (6 occurrences)
> Last logged: 19:36:32
> 
> Error adding entities for domain binary_sensor with platform xiaomi_gateway3
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 589, in _async_add_entity
>     entity.add_to_platform_start(
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1293, in add_to_platform_start
>     raise HomeAssistantError(
> homeassistant.exceptions.HomeAssistantError: Entity 'binary_sensor.xxxxx_gateway' cannot be added a second time to an entity platform

In the normal state, I disabled the entity first and then enabled it. At this time, the gateway and all entities on it are unavailable, and you will see the log above.

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.0
