### ISSUE TITLE
Main loop error

### ISSUE THREAD

**Issue by JachinY** [AlexxIT/XiaomiGateway3#767]
此错误来自自定义集成。

```
Logger: custom_components.xiaomi_gateway3.core.gateway
Source: custom_components/xiaomi_gateway3/core/gateway/__init__.py:77 
Integration: Xiaomi Gateway 3 (documentation, issues) 
First occurred: 14:55:51 (3 occurrences) 
Last logged: 14:55:54

192.168.0.109 | Main loop error
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 92, in run_forever
    not await self.enable_telnet():
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 77, in enable_telnet
    raw = json.loads(self.telnet_cmd)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 44 (char 43)
```

**Comment by donatelloth** [comment]
Same issue:

Logger: custom_components.xiaomi_gateway3.core.gateway
Source: custom_components/xiaomi_gateway3/core/gateway/__init__.py:77 
Integration: Xiaomi Gateway 3 ([documentation](https://github.com/AlexxIT/XiaomiGateway3), [issues](https://github.com/AlexxIT/XiaomiGateway3/issues)) 
First occurred: 22 августа 2022 г., 07:08:58 (18835198 occurrences) 
Last logged: 21:36:45

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 92, in run_forever
    not await self.enable_telnet():
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 77, in enable_telnet
    raw = json.loads(self.telnet_cmd)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

**Comment by asumras** [comment]
2022-10-21 12:36:38.197 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.10.215 | Main loop error
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 93, in run_forever
    not await self.enable_telnet():
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 78, in enable_telnet
    raw = json.loads(self.telnet_cmd)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AlexxIT** [comment]
@asumras you have wrong open telnet command in settings

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
