### ISSUE TITLE
Can't login to Micloud

### ISSUE THREAD

**Issue by serhat-ozkara** [AlexxIT/XiaomiGateway3#799]
I'm getting the following:

`Can't request MIoT API /home/device_list
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/xiaomi_cloud.py", line 181, in request
    resp = json.loads(decrypt_rc4(signed_nonce, resp))
  File "/config/custom_components/xiaomi_gateway3/core/xiaomi_cloud.py", line 276, in decrypt_rc4
    crypt(base64.b64decode(data))
  File "/usr/local/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding`

**Comment by AlexxIT** [comment]
Just wrong answer from cloud. Can't do anything with it. I can only add the ignore code.
