### ISSUE TITLE
Support Aqara A100 locks (Feature Req)

### ISSUE THREAD

**Issue by rafaelreis-r** [AlexxIT/XiaomiGateway3#808]
Hey @AlexxIT! First of all, amazing work you've done with this repo. 

I'm on a quest to integrate Aqara A100 locks to Home Assistant somehow. 

I first started to work with Zigbee2Mqtt devs to see if we could add it there. It turns out there is some encrypted communication going on between Aqara hubs coordinators and the lock, so we reached a stall. Very interesting issue thread loaded with sniffs and pcap analysis [here](https://github.com/Koenkk/zigbee2mqtt/issues/13087). I kindly ask you to take a look if you can.

Next, I tried to downgrade fw and root my G3 Camera hub to use [niceboygithub/AqaraGateway](https://github.com/niceboygithub/AqaraGateway) which is derived from your work. It was tricky but I got it (here is the [thread](https://github.com/niceboygithub/AqaraCameraHubfw/issues/15) in case you're interested)

I did get it working. However, despite having the lock paired to the hub, as well as a regular Aqara button, only the button shows up in the HA entities. The lock does not show up. I'm using telnet for the integration. 

Would you have any input regarding how can I approach this quest further? I'm a competent sysadmin, engineer, but zigbee and embedded devices / firmware reverse engineering are a bit out of my reach. 

Thanks!

**Comment by AlexxIT** [comment]
Well. Now you have G3 and Integration from Niceboy. But only one button exposed from lock?

**Comment by rafaelreis-r** [comment]
Oh, Sorry @AlexxIT I might have not explained myself enough. 

I've paired both the https://www.aqara.com/en/product/smart-door-lock-a100-zigbee and a regular known device, an [Aqara Mini Switch - WXKG12LM](https://www.zigbee2mqtt.io/devices/WXKG12LM.html). 

Output from `/data/zigbee # cat device.info` over telnet shows 2 devices paired. 
```
{"devInfo":[{"mac":"0x54ef4410004c5112","shortId":"0x63f4","manuCode":"0x115f","model":"aqara.lock.acn001","did":"lumi.54ef4410004c5112","devType":0,"appVer":1,"hardVer":0,"devID":65520,"status":0,"model_ver":1,"preLeave":0},{"mac":"0x158d00067925ee","shortId":"0x7d91","manuCode":"0x115f","model":"lumi.remote.b1acn01","did":"lumi.158d00067925ee","devType":0,"appVer":2,"hardVer":0,"devID":0,"status":1,"model_ver":2,"preLeave":0}]}
```
Only the switch shows up in the integration. The lock, although paired, does not. 

![image](https://user-images.githubusercontent.com/57492577/186970037-fe012dc7-d60c-4c98-8a64-99ec6ff678cc.png)


I was wondering if you could shed a light on how to get support for the A100 over integration. I have various Zigbee resources available (sniffer, coordinators, etc), due to the [reverse engineering attempts I did with Z2M devs](https://github.com/Koenkk/zigbee2mqtt/issues/13087)

**Comment by AlexxIT** [comment]
I don't research G3 yet

**Comment by niceboygithub** [comment]
@rafaelreis-r 

Can you try the master branch of [AqaraGateway](https://github.com/niceboygithub/AqaraGateway)?

**Comment by rafaelreis-r** [comment]
> @rafaelreis-r
> 
> Can you try the master branch of [AqaraGateway](https://github.com/niceboygithub/AqaraGateway)?

Just did. Checked out master branch.
Deleted the Integration
Restarted HA
Readded the Integration
Connected to G3 Hub (telnet)

No change. It does not show the lock. 

Where can I find logs? I've enabled MQTT and debug logs but nothing was logged to main HA logger.

**Comment by niceboygithub** [comment]
Your model is "aqara.lock.acn001"

you can add the blew to [here](https://github.com/niceboygithub/AqaraGateway/blob/9c3ff9547dbaed73f76ba554b46eacf5e18e5713/custom_components/aqara_gateway/core/utils.py#L608)
```
    'aqara.lock.acn001': ["Aqara", "Door Lock A100", "ZNMS02ES"],
```
You shall got basic support of this lock.

**Comment by rafaelreis-r** [comment]
@niceboygithub 

Got an Error:

```
2022-09-13 23:45:40.805 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/config/custom_components/aqara_gateway/core/gateway.py", line 138, in run
    self.setup_devices(devices)
  File "/config/custom_components/aqara_gateway/core/gateway.py", line 342, in setup_devices
    self.setups[domain](self, device, attr)
  File "/config/custom_components/aqara_gateway/sensor.py", line 82, in setup
    add_entities([GatewayLockSensor(gateway, device, attr)])
  File "/config/custom_components/aqara_gateway/sensor.py", line 345, in __init__
    self._features = DEVICE_MAPPINGS[self.device['model']]
KeyError: 'aqara.lock.acn001'
```

**Comment by niceboygithub** [comment]
Please paste your modification.

**Comment by rafaelreis-r** [comment]
![image](https://user-images.githubusercontent.com/57492577/190048002-5b42a37b-9e21-4c2d-bc86-d6ac0d731337.png)

Full file:
[utils.py.zip](https://github.com/AlexxIT/XiaomiGateway3/files/9562269/utils.py.zip)

**Comment by niceboygithub** [comment]
The easy modification.

```
}, {
    'aqara.lock.eicn01': ["Aqara", "Door Lock A100", "ZNMS02ES"],
    'aqara.lock.acn001': ["Aqara", "Door Lock A100", "ZNMS02ES"],
    'params': [
```

**Comment by rafaelreis-r** [comment]
> The easy modification.
> 
> ```
> }, {
>     'aqara.lock.eicn01': ["Aqara", "Door Lock A100", "ZNMS02ES"],
>     'aqara.lock.acn001': ["Aqara", "Door Lock A100", "ZNMS02ES"],
>     'params': [
> ```

It doesn't work, because lock_data.py does not have a DEVICE_MAPPINGS definition for either of the locks:

https://github.com/niceboygithub/AqaraGateway/blob/9c3ff9547dbaed73f76ba554b46eacf5e18e5713/custom_components/aqara_gateway/core/lock_data.py#L9-L23

**Comment by rafaelreis-r** [comment]
I've added to lock_data.py:

```
DEVICE_MAPPINGS = {
    "lumi.lock.aq1": SUPPORT_ALARM,
    "lumi.lock.acn02": SUPPORT_ALARM | SUPPORT_DOORBELL,
    "lumi.lock.acn03": SUPPORT_ALARM | SUPPORT_DOORBELL,
    "aqara.lock.wbzac1": (
        WITH_LI_BATTERY | SUPPORT_ALARM |
        SUPPORT_DOORBELL | SUPPORT_WIFI | SUPPORT_CAMERA),
    "aqara.lock.bzacn3": (
        SUPPORT_ALARM | SUPPORT_DOORBELL),
    "aqara.lock.bzacn4": (
        SUPPORT_ALARM | SUPPORT_DOORBELL),
    "aqara.lock.dacn03": (
        WITH_LI_BATTERY | SUPPORT_ALARM |
        SUPPORT_DOORBELL | SUPPORT_WIFI | SUPPORT_CAMERA),
    "aqara.lock.acn001": (
        SUPPORT_ALARM | SUPPORT_DOORBELL)
}
```




Lock shows but no communication to it. Not many entities.

![image](https://user-images.githubusercontent.com/57492577/190234336-be2263f2-f5b3-4d25-bebc-c5afcb1d7c9c.png)

**Comment by niceboygithub** [comment]
You can enable , mqtt logs.
With lock activities, you shall get lots of logs. Please paste the logs.

like this
```
2022-09-15 07:22:49  DEBUG  gateway  10.0.1.27: MQTT on_message: zigbee/send {"cmd":"report","id":58717,"did":"lumi.158d0002497cf6","time":1663197769079,"rssi":-57,"zseq":106,"params":[{"res_name":"4.1.85","value":0}],"dev_src":"0"}
```

**Comment by rafaelreis-r** [comment]
@niceboygithub Could you please clarify?

I beleive I should enable mqtt logs in the G3 hub, right?
I see that the binary is in  `4004     1 root     S     2220  1.8   1  0.0 /data/bin/mosquitto -d`

Is there a mosquitto.conf somewhere? Or a script that calls the binary? Please let me know so I can adjust accordinly.

**Comment by niceboygithub** [comment]
> @niceboygithub Could you please clarify?
> 
> I beleive I should enable mqtt logs in the G3 hub, right? I see that the binary is in `4004 1 root S 2220 1.8 1 0.0 /data/bin/mosquitto -d`
> 
> Is there a mosquitto.conf somewhere? Or a script that calls the binary? Please let me know so I can adjust accordinly.

From Alex great work. it is very easy to got mqtt log
Please use [method 1](https://github.com/AlexxIT/XiaomiGateway3#debug-mode)

**Comment by rafaelreis-r** [comment]
Hey @niceboygithub 

I have a very long and rich log. It includes:

- Unpairing
- Repairing
- Adding User
- Various actions (lock, unlock, inside, outside, with fingerprint, with homekit, with passcode, with key, from inside, from outside etc etc). I only don't have NFC to test.

I collected the debug logs + Aqara app logs so you can correlate the name of the actions to the codes in mqtt logs. 

[mqtt log.zip](https://github.com/AlexxIT/XiaomiGateway3/files/9576459/mqtt.log.zip)
[Aqara Actions log.zip](https://github.com/AlexxIT/XiaomiGateway3/files/9576461/Aqara.Actions.log.zip)

**Comment by niceboygithub** [comment]
> Hey @niceboygithub
> 
> I have a very long and rich log. It includes:
> 
> * Unpairing
> * Repairing
> * Adding User
> * Various actions (lock, unlock, inside, outside, with fingerprint, with homekit, with passcode, with key, from inside, from outside etc etc). I only don't have NFC to test.
> 
> I collected the debug logs + Aqara app logs so you can correlate the name of the actions to the codes in mqtt logs.
> 
> [mqtt log.zip](https://github.com/AlexxIT/XiaomiGateway3/files/9576459/mqtt.log.zip) [Aqara Actions log.zip](https://github.com/AlexxIT/XiaomiGateway3/files/9576461/Aqara.Actions.log.zip)
> 
> Edit: A few more actions and codes: [more codes.zip](https://github.com/AlexxIT/XiaomiGateway3/files/9576873/more.codes.zip)

I try my best to analyze the logs.
It is not easy to analyze offline. 
For example, when you unlock by fringeprint, this action contains several activities, unlock, open door, close door, door not close etc.

![image](https://user-images.githubusercontent.com/74046071/190585643-994fe977-f430-4cbe-a24e-4902e8bffc6a.png)

```
```

**Comment by rafaelreis-r** [comment]
@niceboygithub Let me know if I can help in any way. Maybe slowing down the actions. 

I can also provide a complete wireshark pcap sniff of the zigbee communications if it helps in any way.

**Comment by niceboygithub** [comment]
The slow down actions will help a lots.

And every actions can be five minutes apart.

**Comment by FrAllard** [comment]
I'm looking into buying one of the lock too. I'm wondering if you end up getting it to work in z2m?

**Comment by waterdrop01** [comment]
I encourage anyone interested into solving this issue to report it on the Aqara support page => https://static-resource.aqara.com/html/feedback.html, 

Asking them **to share the encryption key**. Here is a message example:

![A100 z2m support](https://user-images.githubusercontent.com/47316824/193529337-358b3b9f-6c9e-4304-9d2a-356ce97f892d.png)

```
Dear Aqara team,

Looking at the comments in this youtube video (https://www.youtube.com/watch?v=LBAfbBE9-Bo), you can see that A LOT of people WILL NOT BUY the Aqara A100 because it is NOT SUPPORTED by zigbee2mqtt.

The issue is that Aqara A100 firmware is using en encryption key to communicate over zigbee (see details about the issue here => https://github.com/Koenkk/zigbee2mqtt/issues/13087) and WITHOUT this encryption key, it's nearly impossible to support the A100 into zigbee2mqtt.

Could you please consider working out a solution to add support for the A100 into zigbee2mqtt? (like sharing the key with z2m devs)

Having an open system will definitely boost your sales ;)

Thanks!
```

**Comment by niceboygithub** [comment]
Perfect. You can create PR to AqaraGateway integration.

**Comment by ilyoon123** [comment]
@rafaelreis-r works! Big thanks!
Don't forget to just add the lock to lock_data.py

**Comment by rsieiro** [comment]
@rafaelreis-r is the A100 lock working well on HA now with your Aqara gateway? Based on your latest message it does look like it, but I'm thinking about buying one and wanted to double check if it's fully working now. Thanks!

**Comment by rafaelreis-r** [comment]
Hey @rsieiro it is stable and working fine with the following entities:

![image](https://user-images.githubusercontent.com/57492577/200921745-038a040f-b133-43cd-87d7-339f0a0bf67e.png)


There is a lot more available to be supported though, but I'm at my technical limit. Wish I could do more. 

I also didn't do the PR for that same reason. My git skills are limited to `git clone`.

**Comment by rsieiro** [comment]
Awesome! Just ordered one. I'll do a bit of research once it arrives, maybe I can find additional useful entities :)

**Comment by sulliwane** [comment]
@rafaelreis-r could you help me clarify the following points?

1- do you use AlexxIT or niceboygithub integration  in HA to add your Aqara hub?

2- if you use niceboygithub integration, did you have to manually flash the hub fw before being able to add it to HA?

3- if you use niceboygithub integration, did you have to go through MiHome mode/app to get a Token, and then back to Aqara mode to add it to HA through "Aqara Gateway Integration"?

4- finally, how do you pair the lock to the hub, using mihome or aqara home? and after adding the hub to HA or before?

Thanks a lot for your help!!

**Comment by sulliwane** [comment]
Hey @rafaelreis-r, your feedback on the above questions would be very much appreciated 😀

**Comment by AlexxIT** [comment]
@sulliwane Aqara A100 doesn't supported by Xiaomi gateway, so he using niceboygithub's integration.

**Comment by rafaelreis-r** [comment]
> 

1 - niceboy
2 - yes, to the supported fw version
3 - no. It uses telnet
4 - Aqara home. It doesn't matter when you add it to HA.

**Comment by weising26** [comment]
HI @niceboygithub 
I also have a Aqara A100 Lock with G3 but my device model looks diff
Output from /data/zigbee # cat device.info over telnet shows 

`{"devInfo":[{"mac":"0x54ef44100044aa66","shortId":"0x036b","manuCode":"0x115f","model":"aqara.lock.agl002","did":"lumi.54ef44100044aa66","devType":0,"appVer":1,"hardVer":0,"devID":65520,"status":0,"model_ver":1,"preLeave":0}]}/data/zigbee #`

**Comment by niceboygithub** [comment]
Try add

``
'aqara.lock.agl002': ["Aqara", "Door Lock A100", "ZNMS02ES"],
``

**Comment by weising26** [comment]
@niceboygithub  ya i added the same as above and everything working with the steps above
![image](https://user-images.githubusercontent.com/11695377/209683225-e5200527-9721-493c-ae1e-5116f8d64cec.png)

**Comment by Ampig** [comment]
Hi guys, bit of a newbie to Zigbee and such. I have an A100 and am keen on getting it into HA.

- Do I need a rooted Aqara hub to do so?
- Is there support for an _Away Mode_ sensor?

**Comment by weising26** [comment]
@Ampig  

You need an aqara G3 camera hub for A100 to get into HA. Away mode sensor works with https://github.com/niceboygithub/AqaraGateway integration.

**Comment by Ampig** [comment]
> aqara G3 camera hub

Thanks for the info @weising26!

Just to clarify...

- Does it have to be that specific hub? Or can any Aqara hub work?
- Does the hub have to be rooted?

Thank you.

**Comment by weising26** [comment]
i only found this aqara G3 camera hub working with enabling telnet by https://github.com/Wh1terat/aQRootG3

**Comment by Rgn589** [comment]
Do you know if this integration works similar in d100 smart locks as well?

**Comment by waterdrop01** [comment]
@rafaelreis-r @niceboygithub 

1. I've succesfully installed https://github.com/niceboygithub/AqaraGateway
2. Put Aqara Hub E1 in Mijia mode, added to my Mijia account, [retrieved the token](https://github.com/piotrmachowski/xiaomi-cloud-tokens-extractor), 
3. Input the "Host IP" + "Mijia Token" into the AqaraGateway integration popup page => Successfull.

Now how am I supposed to pair the Hub E1 to my Aqara A100 doorlock?

Thanks for your help!

**Comment by rafaelreis-r** [comment]
Since there is no pairing button on the A100, you have to trigger the pairing with the official Aqara app. 

Details in the Pairing section here: https://github.com/Koenkk/zigbee2mqtt/issues/13087#issue-1299761012

**Comment by sulliwane** [comment]
thanks @rafaelreis-r for your help! I'm a bit lost though...

👉 I thought that the A100 would eventually be controlled by HA _through_ the Aqara E1 HUB.

What you are actually saying is that I can **connect to the A100 directly using z2m**? (The Aqara Hub being only used to trigger the pairing).

If yes, then I don't understand the point of installing this integration https://github.com/niceboygithub/AqaraGateway (see screenshots below)
![Screenshot from 2023-07-29 02-20-26](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/41be5dad-39c8-4dde-8ef7-665baa679b6f)
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/a1361884-f3e2-4d6a-847e-1dbd9aa1a142)

**Comment by waterdrop01** [comment]
thanks @rafaelreis-r for your help! I'm a bit lost though...

👉 I thought that the A100 would eventually be controlled by HA _through_ the Aqara E1 HUB.

What you are actually saying is that I can **connect to the A100 directly using z2m**? (The Aqara Hub being only used to trigger the pairing).

If yes, then I don't understand the point of installing this integration https://github.com/niceboygithub/AqaraGateway (see screenshots below)
![Screenshot from 2023-07-29 02-20-26](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/41be5dad-39c8-4dde-8ef7-665baa679b6f)
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/a1361884-f3e2-4d6a-847e-1dbd9aa1a142)

**Comment by waterdrop01** [comment]
Hey @rafaelreis-r, I would really appreciate if you could clarify the above...I'm a bit lost ^^ Thanks

**Comment by waterdrop01** [comment]
Ok, so for those like me who needed clarification:

- no zigbee2mqtt integration. HA connects to the A100 Door Lock through Aqara Hub (using the https://github.com/niceboygithub/AqaraGateway integration).
- Once you've got all the above 1,2,3 steps OK, it means that telnet is now enabled.
- However, the device is still in Mijia Mode. So you can try to connect to it using Aqara APP, it will detect it's in Mijia home and propose you to switch to Aqara mode.
- Once done, you can bind the door lock to the HUB.
- Once done, in HA I've removed the entity in the Aqara integration. And added it again, without specifying a token (just the IP) because telnet is enabled. (You can test using the CLI with command "telnet 192.168.1.XX" and then "root" username and empty password).
- And I now have two devices!

![Screenshot from 2023-08-04 23-58-45](https://github.com/AlexxIT/XiaomiGateway3/assets/47316824/b59bb551-929c-49a3-9968-98d4359296a3)
![Screenshot from 2023-08-04 23-57-21](https://github.com/AlexxIT/XiaomiGateway3/assets/47316824/bce3d753-848a-4a4c-bebb-df5239e9851f)

By actionning the door lock, you will get a value for Key ID, Lock and Lock event.

Using the "Lock event", you will be able to detect the "away from home" mode!

**Comment by afghifariii** [comment]
HI @waterdrop01 did you use the A100 Pro (CN Version) or the International Version? And could you confirm that the lock can be controlled via Home assistant (e.g. to lock and unlock)?

**Comment by sulliwane** [comment]
@afghifariii I use the CN version. 

No the lock can't be locked/unlocked by Home Assistant. Here is what it looks like in HA:
![Screenshot from 2023-09-12 09-14-19](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/e7491511-112b-4606-b39c-aa75750de74e)
![Screenshot from 2023-09-12 09-11-44](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/c2eea3b3-176f-40ef-a907-bd8fd3d2bca1)
In my setup, pressing the "away from home" button on the lock will switch off all lamps and activate the camera mode "away from home". This is what the automation looks like:
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/aa6cfd9f-5268-4d80-8660-498ee95e8fe9)

Regarding remotely locking/unlocking, my undertanding (but needs to verify) is that because there is a Aqara Hub, using the Aqara application (Android for me), then I can generate a one time password:
That's my E1 Hub (I enabled Telnet by first switching it to Mijia mode by pressing the buttons, [then followed this guide to enable Telnet](https://github.com/piotrmachowski/xiaomi-cloud-tokens-extractor), then switched back to Aqara mode pressing the buttons)
![Screenshot_2023-09-12-09-13-15-14_ce4e68f61617016ad670723b24b4b711](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/b069c6ec-4426-4028-8aa2-311a3cfb0565)

In Aqara App, I added my E1 hub + associated A100 lock to the hub:
![Screenshot_2023-09-12-09-12-45-17_ce4e68f61617016ad670723b24b4b711](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/82bdfdb6-0908-454e-af65-1eb60cbf5649)
By pressing the "one time password" button, even if away from home (without being directly connected to the lock using Bluetooth) then I can generate a pin code and give it to someone remotely:
![Screenshot_2023-09-12-09-12-54-85_ce4e68f61617016ad670723b24b4b711](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/84651b6a-1798-4a64-80f6-742f9c8ad4e1)

Hope this answers your questions :)

**Comment by afghifariii** [comment]
@sulliwane Hi, thanks for the detailed explanation. It seems if I want to control the lock remotely I need to have the Zigbee or International version by creating virtual switch and export it to homekit, then create an automation in homekit. I guess it is what it is. no other door lock that suit my needs more than the A100 or D100 hahaha

**Comment by amodelaweb** [comment]
> @afghifariii I use the CN version.
> 
> No the lock can't be locked/unlocked by Home Assistant. Here is what it looks like in HA: ![Screenshot from 2023-09-12 09-14-19](https://user-images.githubusercontent.com/1733686/267244101-e7491511-112b-4606-b39c-aa75750de74e.png) ![Screenshot from 2023-09-12 09-11-44](https://user-images.githubusercontent.com/1733686/267244151-c2eea3b3-176f-40ef-a907-bd8fd3d2bca1.png) In my setup, pressing the "away from home" button on the lock will switch off all lamps and activate the camera mode "away from home". This is what the automation looks like: ![image](https://user-images.githubusercontent.com/1733686/267244577-aa6cfd9f-5268-4d80-8660-498ee95e8fe9.png)
> 
> Regarding remotely locking/unlocking, my undertanding (but needs to verify) is that because there is a Aqara Hub, using the Aqara application (Android for me), then I can generate a one time password: That's my E1 Hub (I enabled Telnet by first switching it to Mijia mode by pressing the buttons, [then followed this guide to enable Telnet](https://github.com/piotrmachowski/xiaomi-cloud-tokens-extractor), then switched back to Aqara mode pressing the buttons) ![Screenshot_2023-09-12-09-13-15-14_ce4e68f61617016ad670723b24b4b711](https://user-images.githubusercontent.com/1733686/267244980-b069c6ec-4426-4028-8aa2-311a3cfb0565.jpg)
> 
> In Aqara App, I added my E1 hub + associated A100 lock to the hub: ![Screenshot_2023-09-12-09-12-45-17_ce4e68f61617016ad670723b24b4b711](https://user-images.githubusercontent.com/1733686/267244923-82bdfdb6-0908-454e-af65-1eb60cbf5649.jpg) By pressing the "one time password" button, even if away from home (without being directly connected to the lock using Bluetooth) then I can generate a pin code and give it to someone remotely: ![Screenshot_2023-09-12-09-12-54-85_ce4e68f61617016ad670723b24b4b711](https://user-images.githubusercontent.com/1733686/267244952-84651b6a-1798-4a64-80f6-742f9c8ad4e1.jpg)
> 
> Hope this answers your questions :)

Do you know if you can create this one time pass-codes from the HA integration ? or  any way we can use that function to automatically create one  time passwords without relying on the aqara app ?

**Comment by sulliwane** [comment]
@amodelaweb not to my knowledge. 

I wouldn't be able to explain why this feature is not integrated into HA though but people way more qualified than me may have an explanation (thinking of @AlexxIT , @rafaelreis-r or @niceboygithub :)

**Comment by niaosuan** [comment]
> @afghifariii I use the CN version.
> 
> No the lock can't be locked/unlocked by Home Assistant. Here is what it looks like in HA: ![Screenshot from 2023-09-12 09-14-19](https://user-images.githubusercontent.com/1733686/267244101-e7491511-112b-4606-b39c-aa75750de74e.png) ![Screenshot from 2023-09-12 09-11-44](https://user-images.githubusercontent.com/1733686/267244151-c2eea3b3-176f-40ef-a907-bd8fd3d2bca1.png) In my setup, pressing the "away from home" button on the lock will switch off all lamps and activate the camera mode "away from home". This is what the automation looks like: ![image](https://user-images.githubusercontent.com/1733686/267244577-aa6cfd9f-5268-4d80-8660-498ee95e8fe9.png)
> 
> Regarding remotely locking/unlocking, my undertanding (but needs to verify) is that because there is a Aqara Hub, using the Aqara application (Android for me), then I can generate a one time password: That's my E1 Hub (I enabled Telnet by first switching it to Mijia mode by pressing the buttons, [then followed this guide to enable Telnet](https://github.com/piotrmachowski/xiaomi-cloud-tokens-extractor), then switched back to Aqara mode pressing the buttons) ![Screenshot_2023-09-12-09-13-15-14_ce4e68f61617016ad670723b24b4b711](https://user-images.githubusercontent.com/1733686/267244980-b069c6ec-4426-4028-8aa2-311a3cfb0565.jpg)
> 
> In Aqara App, I added my E1 hub + associated A100 lock to the hub: ![Screenshot_2023-09-12-09-12-45-17_ce4e68f61617016ad670723b24b4b711](https://user-images.githubusercontent.com/1733686/267244923-82bdfdb6-0908-454e-af65-1eb60cbf5649.jpg) By pressing the "one time password" button, even if away from home (without being directly connected to the lock using Bluetooth) then I can generate a pin code and give it to someone remotely: ![Screenshot_2023-09-12-09-12-54-85_ce4e68f61617016ad670723b24b4b711](https://user-images.githubusercontent.com/1733686/267244952-84651b6a-1798-4a64-80f6-742f9c8ad4e1.jpg)
> 
> Hope this answers your questions :)

Thanks for info, was thinking which gateway and lock to buy. Do you use it on Mi Home ap as compared to Aqara?

**Comment by sulliwane** [comment]
@niaosuan Hey 尿酸，press 10 times in a row the button on the E1 aqara hub to switch between Aqara mode and Mijia mode.

When in Mijia mode, needs to use Mijia App. When in Aqara mode, need to use Aqara App.

Correct, it's actually this integration in HA that will take care of enabling Telnet on the E1 hub: https://github.com/niceboygithub/AqaraGateway

But for E1, the integration will need to have the token as an input in order to process and enable telnet. So first need to extract the token, and feed it into the integration setup.

I personally use Aqara mode + Aqara App. The integration AqaraGateway works with the hub when the hub is in Aqara mode I think (not 100% sure).

**Comment by sprint1849** [comment]
Hi, I have been following this thread.

I have successfuly set up Aqara A100 Pro with E1 Hub using niceboy's Aqara Gateway integration.

It's all fun and game until I block internet to the gateway and you restart the gateway or there is power interruption.

The setup is perfect for me, however, this is my only problem. I need my setup to be offline.

Is there any way how to do this?
