### ISSUE TITLE
Can't login to Mi Cloud

### ISSUE THREAD

**Issue by Cxxxxxp** [AlexxIT/XiaomiGateway3#819]

**Comment by Cxxxxxp** [comment]
此错误来自自定义集成。

Logger: custom_components.xiaomi_gateway3.core.xiaomi_cloud
Source: custom_components/xiaomi_gateway3/core/xiaomi_cloud.py:77
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 22:09:27 (4 occurrences)
Last logged: 22:46:34

Can't login to Mi Cloud: Cannot connect to host account.xiaomi.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/xiaomi_cloud.py", line 57, in login
    payload = await self._login_step1()
  File "/config/custom_components/xiaomi_gateway3/core/xiaomi_cloud.py", line 77, in _login_step1
    r = await self.session.get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host account.xiaomi.com:443 ssl:default [Try again]

**Comment by ghulmarduk** [comment]
same here, region Europe / Germany

**Comment by TrustedFloppa** [comment]
This may be wrong password or login try reseting gateway to factory settings and try again

**Comment by ghulmarduk** [comment]
> This may be wrong password or login try reseting gateway to factory settings and try again

that did´nt do it

**Comment by AlexxIT** [comment]
I can't do anything when your HA can't connect to xiaomi cloud. Just internet or network setup problems...

**Cannot connect to host account.xiaomi.com**
