### ISSUE TITLE
An error occurred after the lumi.curtain.hmcn04 ran for a few minutes

### ISSUE THREAD

**Issue by Soolita** [AlexxIT/XiaomiGateway3#864]
```
Logger: homeassistant.components.cover
Source: custom_components/xiaomi_gateway3/cover.py:49
Integration: 卷帘 (documentation, issues)
First occurred: 09:12:36 (4 occurrences)
Last logged: 09:20:00

Error adding entities for domain cover with platform xiaomi_gateway3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 788, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/xiaomi_gateway3/core/entity.py", line 182, in async_added_to_hass
    self.async_restore_last_state(state.state, state.attributes)
  File "/config/custom_components/xiaomi_gateway3/cover.py", line 49, in async_restore_last_state
    "position": attrs[ATTR_CURRENT_POSITION]
KeyError: 'current_position'
```

![image](https://user-images.githubusercontent.com/18568963/202344917-83b78f82-2776-4717-8f2e-0ff5289fb443.png)

**Comment by mo1seev** [comment]
Hi, @AlexxIT !

Can you add support for this device, please?

Its [Aqara Curtain Driver E1](https://www.zigbee2mqtt.io/devices/ZNCLBL01LM.html#xiaomi-znclbl01lm) (lumi.curtain.agl001)

**Comment by AlexxIT** [comment]
@mo1seev you need to collect device logs

**Comment by mo1seev** [comment]
@AlexxIT no problem. How i can do it only for this device?
