### ISSUE TITLE
Can't find any devices under Aqara E1 Hub

### ISSUE THREAD

**Issue by CheukFaiho** [AlexxIT/XiaomiGateway3#876]
I have a Aqara E1 Hub, It was working fine until yesterday. In order to replace the socket at home, I turn off the power in my house, so the gateway also turn off. But when the power came back and the gateway reboot, all device shows 'no response'. I deleted the Aqara E1 hub and added it again to xiaomi gateway 3 integration, it can success add into, but no devices under the hub.

<img width="282" alt="截屏2022-11-29 14 28 40" src="https://user-images.githubusercontent.com/35355832/204455411-e4bdec75-afe5-43ba-9515-dc2a03fe9f7f.png">

However, I can see all the devices under this hub in MiHome App. I checked the log file, and it shows some error:

```
"integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "issue_tracker": "https://github.com/AlexxIT/XiaomiGateway3/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http"
    ],
    "requirements": [
      "zigpy>=0.33.0"
    ],
    "version": "2.1.2",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "4894b05",
    "options": {
      "host": "***",
      "token": "***",
      "telnet_cmd": "{\"method\":\"set_ip_info\",\"params\":{\"ssid\":\"\\\"\\\"\",\"pswd\":\"123123 ; /bin/riu_w 101e 53 3012; telnetd\"}}",
      "ble": true,
      "stats": false,
      "debug": [],
      "buzzer": false,
      "memory": false,
      "zha": false
    },
    "errors": [
      {
        "name": "aiohttp.server",
        "message": [
          "Error handling request"
        ],
        "level": "ERROR",
        "source": [
          "custom_components/xiaomi_gateway3/core/utils.py",
          169
        ],
        "timestamp": 1669701980.203265,
        "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py\", line 435, in _handle_request\n    resp = await request_handler(request)\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py\", line 504, in _handle\n    resp = await handler(request)\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py\", line 117, in impl\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/security_filter.py\", line 60, in security_filter_middleware\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/forwarded.py\", line 100, in forwarded_middleware\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/request_context.py\", line 28, in request_context_middleware\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/ban.py\", line 82, in ban_middleware\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/auth.py\", line 236, in auth_middleware\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/view.py\", line 136, in handle\n    result = await result\n  File \"/usr/src/homeassistant/homeassistant/components/config/config_entries.py\", line 180, in post\n    return await super().post(request, flow_id)\n  File \"/usr/src/homeassistant/homeassistant/components/http/data_validator.py\", line 73, in wrapper\n    result = await method(view, request, data, *args, **kwargs)\n  File \"/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py\", line 110, in post\n    result = await self._flow_mgr.async_configure(flow_id, data)\n  File \"/usr/src/homeassistant/homeassistant/data_entry_flow.py\", line 280, in async_configure\n    result = await self._async_handle_step(\n  File \"/usr/src/homeassistant/homeassistant/data_entry_flow.py\", line 367, in _async_handle_step\n    result: FlowResult = await getattr(flow, method)(user_input)\n  File \"/config/custom_components/xiaomi_gateway3/config_flow.py\", line 102, in async_step_token\n    error = await utils.check_gateway(**user_input)\n  File \"/config/custom_components/xiaomi_gateway3/core/utils.py\", line 169, in check_gateway\n    raw = json.loads(telnet_cmd)\n  File \"/usr/local/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/local/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/local/lib/python3.10/json/decoder.py\", line 353, in raw_decode\n    obj, end = self.scan_once(s, idx)\njson.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 44 (char 43)\n",
        "count": 1,
        "first_occurred": 1669701980.203265
      },
      {
        "name": "custom_components.xiaomi_gateway3.core.gateway",
        "message": [
          "192.168.2.106 | Can't prepare gateway"
        ],
        "level": "ERROR",
        "source": [
          "custom_components/xiaomi_gateway3/core/shell/__init__.py",
          44
        ],
        "timestamp": 1669702890.8978662,
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py\", line 168, in prepare_gateway\n    sh = await session.login()\n  File \"/config/custom_components/xiaomi_gateway3/core/shell/__init__.py\", line 44, in login\n    raise Exception(f\"Unknown response: {resp}\")\nException: Unknown response: b'\\xff\\xfd\\x01\\xff\\xfd\\x1f\\xff\\xfb\\x01\\xff\\xfb\\x03\\r\\r\\nAqara_Hub_E1-CAFF login: '\n",
        "count": 17,
        "first_occurred": 1669702033.5130937
      }
    ],
    "devices": {}
  }
}
```

Is something I missed or make a mistake in somewhere?

**Comment by CheukFaiho** [comment]
After I reinstall the integration,  the log file still got some error, but now just one:

```
  "integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "issue_tracker": "/api/xiaomi_gateway3/19b2e832-b4bb-4e11-8cef-01416c69c180",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http"
    ],
    "requirements": [
      "zigpy>=0.42.0"
    ],
    "version": "3.0a1",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "c9820c5",
    "options": {
      "host": "***",
      "token": "***",
      "telnet_cmd": "{\"method\":\"set_ip_info\",\"params\":{\"ssid\":\"\\\"\\\"\",\"pswd\":\"123123 ; /bin/riu_w 101e 53 3012; telnetd\"}}",
      "ble": true,
      "stats": false,
      "debug": [
        "zigbee",
        "true"
      ],
      "memory": false,
      "zha": false
    },
    "errors": [
      {
        "name": "custom_components.xiaomi_gateway3.core.gateway",
        "message": [
          "192.168.2.106 | Can't prepare gateway"
        ],
        "level": "ERROR",
        "source": [
          "custom_components/xiaomi_gateway3/core/shell/__init__.py",
          52
        ],
        "timestamp": 1669704058.36799,
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py\", line 174, in prepare_gateway\n    async with shell.Session(self.host) as sh:\n  File \"/config/custom_components/xiaomi_gateway3/core/shell/__init__.py\", line 29, in __aenter__\n    return await self.login()\n  File \"/config/custom_components/xiaomi_gateway3/core/shell/__init__.py\", line 52, in login\n    raise Exception(f\"Unknown response: {resp}\")\nException: Unknown response: b'\\xff\\xfd\\x01\\xff\\xfd\\x1f\\xff\\xfb\\x01\\xff\\xfb\\x03\\r\\r\\nAqara_Hub_E1-CAFF login: '\n",
        "count": 2,
        "first_occurred": 1669704049.7138143
      }
    ],
    "devices": {}
  }
}
```

**Comment by AlexxIT** [comment]
Try master version of this integration. I think you have wrong telnet cmd. Right cmd build-in to latest master version. You need to leave this field empty.

**Comment by CheukFaiho** [comment]
> Try master version of this integration. I think you have wrong telnet cmd. Right cmd build-in to latest master version. You need to leave this field empty.

Hmmm, after I use the newest version and installed it manually instead of HACS, all devices came back. Thanks very much!

**Comment by CheukFaiho** [comment]
The question came up again. These time I using the master version of this integration, and let the open telnet cmd empty. The log show 'Can't prepare gateway', but I can see all the devices in MiHome app.

```
2022-12-03 10:01:45 [D] SysInfo: {'installation_type': 'Home Assistant OS', 'version': '2022.11.5', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.10.7', 'docker': True, 'arch': 'x86_64', 'timezone': 'Asia/Shanghai', 'os_name': 'Linux', 'os_version': '5.15.74', 'user': 'root', 'supervisor': '2022.11.2', 'host_os': 'Home Assistant OS 9.3', 'docker_version': '20.10.18', 'chassis': 'vm', 'xiaomi_gateway3_version': '3.0a1 (c9820c5)'}
2022-12-03 10:01:46 [D] Loaded from cache 24 devices
2022-12-03 10:01:47 [E] 192.168.2.102 | Can't prepare gateway|  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 174, in prepare_gateway|    async with shell.Session(self.host) as sh:|Exception: Unknown response: b'\xff\xfd\x01\xff\xfd\x1f\xff\xfb\x01\xff\xfb\x03\r\r\nAqara_Hub_E1-CAFF login: '|
2022-12-03 10:01:47 [D] Loaded from MiCloud 24 devices
2022-12-03 10:02:18 [E] 192.168.2.102 | Can't prepare gateway|  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 174, in prepare_gateway|    async with shell.Session(self.host) as sh:|Exception: Unknown response: b'\xff\xfd\x01\xff\xfd\x1f\xff\xfb\x01\xff\xfb\x03\r\r\nAqara_Hub_E1-CAFF login: '|
2022-12-03 10:02:23 [E] 192.168.2.102 | Can't prepare gateway|  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 174, in prepare_gateway|    async with shell.Session(self.host) as sh:|Exception: Unknown response: b'\xff\xfd\x01\xff\xfd\x1f\xff\xfb\x01\xff\xfb\x03\r\r\nAqara_Hub_E1-CAFF login: '|
2022-12-03 10:03:23 [E] 192.168.2.102 | Can't prepare gateway|  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 174, in prepare_gateway|    async with shell.Session(self.host) as sh:|Exception: Unknown response: b'\xff\xfd\x01\xff\xfd\x1f\xff\xfb\x01\xff\xfb\x03\r\r\nAqara_Hub_E1-CAFF login: '|
2022-12-03 10:04:23 [E] 192.168.2.102 | Can't prepare gateway|  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 174, in prepare_gateway|    async with shell.Session(self.host) as sh:|Exception: Unknown response: b'\xff\xfd\x01\xff\xfd\x1f\xff\xfb\x01\xff\xfb\x03\r\r\nAqara_Hub_E1-CAFF login: '|
2022-12-03 10:05:23 [E] 192.168.2.102 | Can't prepare gateway|  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 174, in prepare_gateway|    async with shell.Session(self.host) as sh:|Exception: Unknown response: b'\xff\xfd\x01\xff\xfd\x1f\xff\xfb\x01\xff\xfb\x03\r\r\nAqara_Hub_E1-CAFF login: '|
```

<img width="430" alt="截屏2022-12-03 10 07 29" src="https://user-images.githubusercontent.com/35355832/205417446-59f382ac-5951-4f26-b5de-714254fbe607.png">
