### ISSUE TITLE
Help me to investiga "192.168.9.12 | Can't prepare gateway" Problem

### ISSUE THREAD

**Issue by CaesarC** [AlexxIT/XiaomiGateway3#877]
XiaomiGateway3 version 2.1.2
Gateway version 1.5.0_0102(downgrade from 1.5.4)

I have already check the network config  and fine some issues，but it still happen

WiFi set to 20MHz、same LAN: https://github.com/AlexxIT/XiaomiGateway3#network-configuration
reboot : https://github.com/AlexxIT/XiaomiGateway3/issues/737
DHCP: https://github.com/AlexxIT/XiaomiGateway3/issues/708

<img width="1100" alt="企业微信20221129-163728@2x" src="https://user-images.githubusercontent.com/7133914/204481932-ff28582e-b9e7-4556-bfb0-3ee7e343dbb5.png">

```
2022-11-29 16:49:10,794 192.168.9.12 | Can't prepare gateway
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 167, in prepare_gateway
    async with shell.Session(self.host) as session:
  File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 26, in __aenter__
    self.reader, self.writer = await asyncio.wait_for(self.coro, 5)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

<img width="436" alt="企业微信20221129-165114@2x" src="https://user-images.githubusercontent.com/7133914/204482768-b8314feb-354d-4032-8155-3f8eb4be4e9d.png">

**Comment by MisterTowma** [comment]
I have same issue ...
You have found solution ?

**Comment by CaesarC** [comment]
> I have same issue ... You have found solution ?

It's still a Network issue，in my case ，it was the vlan ACL which will block the same network traffic
