### ISSUE TITLE
Aqara Motion Sensor E1(lumi.motion.acn001) cannot update status on Xiaomi Multimode Gateway 2

### ISSUE THREAD

**Issue by Joee-D** [AlexxIT/XiaomiGateway3#878]
[XiaomiGateway3](https://github.com/AlexxIT/XiaomiGateway3) Branch Master
***
LOG:
```
2022-11-29 21:34:49.841 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.1.10 | Processing MQTT: zigbee/send b'{"cmd":"report","id":2000000890,"did":"lumi.54ef44100065d28c","dev_src":"0","time":1669728889566,"rssi":-94,"mi_spec":[{"siid":2,"eiid":1,"**arguments":[{"piid":1,"value":3}]**}]}'
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 163, in mqtt_message
await self.dispatcher_send(SIGNAL_MQTT_PUB, msg=msg)
File "/config/custom_components/xiaomi_gateway3/core/gateway/base.py", line 111, in dispatcher_send
await handler(**kwargs)
File "/config/custom_components/xiaomi_gateway3/core/gateway/lumi.py", line 61, in lumi_mqtt_publish
await self.lumi_process_lumi(msg.json)
File "/config/custom_components/xiaomi_gateway3/core/gateway/lumi.py", line 108, in lumi_process_lumi
payload = device.decode_lumi(data[k])
File "/config/custom_components/xiaomi_gateway3/core/device.py", line 355, in decode_lumi
conv.decode(self, payload, v)
File "/config/custom_components/xiaomi_gateway3/core/converters/base.py", line 84, in decode
payload.update(device.decode_lumi(value))
File "/config/custom_components/xiaomi_gateway3/core/device.py", line 344, in decode_lumi
prop = f"{param['siid']}.p.{param['piid']}"
KeyError: 'siid'
```
***
I try to analyze the problem, in the test code test_conv_lumi.py:

      def test_sensor_motion_e1():
          device = XDevice(ZIGBEE, "lumi.motion.acn001", ZDID, ZMAC, ZNWK)
          assert device.info.name == "Aqara Motion Sensor E1"
          device.setup_converters()
      
          p = device.decode_lumi([{
              "siid": 2, "eiid": 1,
              "arguments": [{"siid": 2, "piid": 1, "value": 9}]
          }])
          assert p == {"illuminance": 9, "motion": True}
      
          p = device.decode_lumi([
              {"siid": 2, "piid": 1, "value": 10, "code": 0}
          ])
          assert p == {"illuminance": 10}

the argument format is  "arguments": [{**"siid": 2**, "piid": 1, "value": 9}], but the device report is arguments":[{"piid":1,"value":3}], there is no 'siid' param

**Comment by AlexxIT** [comment]
Can you show response example?

**Comment by Joee-D** [comment]
pull request merged， so close this issue
