### ISSUE TITLE
Error during setup of component xiaomi_gateway3

### ISSUE THREAD

**Issue by lhlxx2010** [AlexxIT/XiaomiGateway3#892]
I have been using gateway3 very well until I changed to a new host, and it has not been loaded. The specific log is as follows. I can not find relevant information from the Internet. Can you help me?

```
Logger: homeassistant.setup
Source: util/json.py:45
First occurred: 00:36:17 (1 occurrences)
Last logged: 00:36:17

Error during setup of component xiaomi_gateway3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
orjson.JSONDecodeError: input length is 0: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 72, in async_setup
    await utils.load_devices(hass, config.get(CONF_DEVICES))
  File "/config/custom_components/xiaomi_gateway3/core/utils.py", line 112, in load_devices
    devices = await store.async_load()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 116, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 125, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 143, in _async_load_data
    data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 45, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: input length is 0: line 1 column 1 (char 0)
```

**Comment by AlexxIT** [comment]
Try to remove folder `/config/.storage/xiaomi_gateway3/`. You have corrupted files there. They will be restored from cloud on next restart.

**Comment by lhlxx2010** [comment]
> 

Thanks, it work fine now, !!!
