### ISSUE TITLE
Unexpected exception importing platform custom_components.xiaomi_gateway3.climate

### ISSUE THREAD

**Issue by SAOPP** [AlexxIT/XiaomiGateway3#899]
Hi! Got this at one of my instances after upgrade to HA `2023.1.0b0`, I understand that the Home Assistant version has beta status, but maybe this will help to avoid this in the stable branch right now?

```
Logger: homeassistant.loader
Source: custom_components/xiaomi_gateway3/climate.py:39
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 00:53:27 (1 occurrences)
Last logged: 00:53:27

Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 744, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 761, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 32, in <module>
    class XiaomiClimate(XEntity, ClimateEntity):
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 39, in XiaomiClimate
    _attr_temperature_unit = TEMP_CELSIUS
NameError: name 'TEMP_CELSIUS' is not defined
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.0-alpha.1

**Comment by jeremysherriff** [comment]
@AlexxIT this error appears to still be present in v3.0-alpha1. Do you want some logs or debug output, or are you good?
