### ISSUE TITLE
Error adding entities for domain cover with platform xiaomi_gateway3

### ISSUE THREAD

**Issue by gordio** [AlexxIT/XiaomiGateway3#928]
Device: Aqara Curtain Controller  

Logger: homeassistant.components.cover
Source: custom_components/xiaomi_gateway3/cover.py:49

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 803, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/xiaomi_gateway3/core/entity.py", line 182, in async_added_to_hass
    self.async_restore_last_state(state.state, state.attributes)
  File "/config/custom_components/xiaomi_gateway3/cover.py", line 49, in async_restore_last_state
    "position": attrs[ATTR_CURRENT_POSITION]
KeyError: 'current_position'
```

**Comment by gordio** [comment]
I'm installed latest master and restart - now works.
