### ISSUE TITLE
V3 alpha-1 - new errors in log

### ISSUE THREAD

**Issue by bobofruit1970** [AlexxIT/XiaomiGateway3#933]
This V3 alpha version of integration works for me for 1-2 days without any errors.
After this period of time I always get errors in log. I have never seen such errors from my gateway V3. 

Two important things. I do not know if it is important:
1. I use statistics table to monitor my ZigBee devices.
2. I block at router traffic from gateway to the internet so gateway can not connect to MIO China servers.

I always did above two points on V2.1.2 and previous versions and never did not get such errors like I get now on V3.0 alpha 1

My errors:
![image](https://user-images.githubusercontent.com/67933104/213357920-dfe22d5e-bb2b-4efd-9f32-b39656e9f277.png)

Log shows:
```
2023-01-18 19:25:43.287 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.2.51 | Can't update gateway stats
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/streams.py", line 47, in open_connection
transport, _ = await loop.create_connection(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
return await fut
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
return fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw.py", line 112, in gw3_update_serial_stats
async with shell.Session(self.host) as sh:
File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 28, in __aenter__
await self.connect()
File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 35, in connect
self.reader, self.writer = await asyncio.wait_for(self.coro, 5)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-01-18 19:26:09.372 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.mini_miio] 192.168.2.51 | Device offline
2023-01-18 19:26:49.932 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.mini_miio] 192.168.2.51 | Device offline
2023-01-18 19:27:30.493 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.mini_miio] 192.168.2.51 | Device offline
2023-01-18 19:28:11.510 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.mini_miio] 192.168.2.51 | Device offline
2023-01-18 19:28:52.525 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.mini_miio] 192.168.2.51 | Device offline
2023-01-18 19:29:33.543 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.mini_miio] 192.168.2.51 | Device offline
2023-01-18 19:30:14.562 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.mini_miio] 192.168.2.51 | Device offline
2023-01-18 19:43:13.563 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.mini_miio] 192.168.2.51 | Device offline
2023-01-18 19:43:56.794 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.2.51 | Can't prepare gateway
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/streams.py", line 617, in readuntil
await self._wait_for_data('readuntil')
File "/usr/local/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
await self._waiter
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
return fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 183, in prepare_gateway
return await self.gw3_prepare_gateway(sh)
File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw.py", line 54, in gw3_prepare_gateway
msg = await sh.run_openmiio_agent()
File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 107, in run_openmiio_agent
ok = await self.check_openmiio_agent()
File "/config/custom_components/xiaomi_gateway3/core/shell/shell_mgw.py", line 105, in check_openmiio_agent
return await self.check_bin("openmiio_agent", MD5_AGENT, URL_AGENT)
File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 71, in check_bin
if md5 in await self.exec(cmd):
File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 34, in exec
raw = await asyncio.wait_for(coro, timeout=timeout)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-01-18 19:51:40.254 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.2.51 | Can't prepare gateway
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/streams.py", line 617, in readuntil
await self._wait_for_data('readuntil')
File "/usr/local/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
await self._waiter
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
return fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 174, in prepare_gateway
async with shell.Session(self.host) as sh:
File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 29, in __aenter__
return await self.login()
File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 43, in login
resp: bytes = await asyncio.wait_for(coro, 3)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

After restart of HA integration will work for next 1-2 days will work without any errors/warnings. After 1-2 days I will find the same errors/warnings.

Nothing has changed in my network. 
Only one thing has changed. New version of XiaomiGateway3 integration V3.0 alpha-1 installed.

**Comment by bobofruit1970** [comment]
When I try to disable statistics I get error

![image](https://user-images.githubusercontent.com/67933104/213390071-4e2d7f52-b073-4e9e-90e0-9ec9e682613e.png)

**Comment by bobofruit1970** [comment]
Acording to DOC there should be command to remove zigbee device but thre is not such command.

![image](https://user-images.githubusercontent.com/67933104/213414623-09a8eb65-69fd-45b1-bc94-d5b771960bd4.png)

1. I have removed device by long press button. 
2. Added device again.
3. Enabled Statistics table
4. Disabled statistics table and the same error appeared in log. 
 
"homeassistant.exceptions.HomeAssistantError: Entity sensor.0x00158d00022357a3_zigbee async_remove called twice"

Is there way to delete this Entity?

**Comment by DJTerentjev** [comment]
![image](https://user-images.githubusercontent.com/1267473/213428038-95f72234-7bd3-4fe4-be4f-6d3307db61ae.png)
