### ISSUE TITLE
ZeroDivisionError occurs when updating light with color_temp=0

### ISSUE THREAD

**Issue by hellkun** [AlexxIT/XiaomiGateway3#95]
First of all, I'd like to thank AlexxIT for making this great component. The issue is about  a BLE mesh switch controller I recently bought, identified as a light, debug log:
```
Setup Mesh device {'did': '1060213968', 'mac': '5CE50CE70D73', 'model': 2007, 'type': 'bluetooth', 'device_name': 'Mesh', 'device_model': 2007}
1060213968 poll mesh <= {'light': False, 'brightness': 771, 'color_temp': 0}
```

And the I've seen a few errors in HA logs:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_gateway3/light.py", line 142, in update
    color.color_temperature_kelvin_to_mired(data['color_temp'])
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 515, in color_temperature_kelvin_to_mired
    return math.floor(1000000 / kelvin_temperature)
ZeroDivisionError: division by zero
```

I think it's also necessary to check the value of data['color_temp'] before calling color_temperature_kelvin_to_mired.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
