### ISSUE TITLE
v3.0.1 switch to zigbee2mqtt mode

### ISSUE THREAD

**Issue by stopword** [AlexxIT/XiaomiGateway3#953]
I can't see Mode [PRO] option here:
![Képernyőkép 2023-01-27 233917](https://user-images.githubusercontent.com/15060957/215219698-57267728-2174-4693-91a8-f2d202ce192f.png)
v.3.0.1 installed
Is there other way to switch to zigbee2mqtt mode?

**Comment by stopword** [comment]
Ok, I see it's from dropdown menu. But now I get this:
`Logger: custom_components.xiaomi_gateway3.core.ezsp
Source: custom_components/xiaomi_gateway3/core/ezsp.py:104
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 08:12:48 (1 occurrences)
Last logged: 08:12:48

192.168.50.153 [FWUP] Can't update firmware
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 52, in update_zigbee_firmware
    cur_fw = await read_firmware(host)
  File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 104, in read_firmware
    await asyncio.wait_for(ezsp._probe(), timeout=10)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 74, in _probe
    await self.connect(use_thread=False)
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 118, in connect
    self._gw = await bellows.uart.connect(self._config, self, use_thread=use_thread)
  File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 397, in connect
    protocol, _ = await _connect(config, application)
  File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 372, in _connect
    baudrate=config[CONF_DEVICE_BAUDRATE],
KeyError: 'baudrate'`
Any idea how can I fix it?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/issues/934
