### ISSUE TITLE
I see that the latest update supports HS1BB, but it is still unavailable after I test it.

### ISSUE THREAD

**Issue by lovedreamland** [AlexxIT/XiaomiGateway3#956]
Multi-Mode Gateway 1+1.5.4_0090
The device can be displayed, but the data will not be updated.

**Comment by AlexxIT** [comment]
It maybe problem with 1.5.4. You need to collect basic debug logs

**Comment by lovedreamland** [comment]
2023-01-29 15:19:35,138 10.10.10.253 [MQTT] log/z3 b''
2023-01-29 15:19:35,140 10.10.10.253 [MQTT] log/z3 b'T2B694B06:RX len 5, ep 01, clus 0x000A (Time) FC 10 seq 18 cmd 00 payload[00 00 ]'
2023-01-29 15:19:35,142 10.10.10.253 [MQTT] log/z3 b'READ_ATTR: clus 000A'
2023-01-29 15:19:35,143 10.10.10.253 [MQTT] log/z3 b'OTA READ: ep:01 cid:000A attid:0000 msk:40 mfcode:0000'
2023-01-29 15:19:35,145 10.10.10.253 [MQTT] log/z3 b'READ: clus 000A, attr 0000, dataLen: 04, OK'
2023-01-29 15:19:35,147 10.10.10.253 [MQTT] gw/0C4314FFFE59E5F0/MessagePreSentCallback b'{"eui64":"0x00158D00035BF130","destinationEndpoint":"0x01","clusterId":"0x000A","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x00","APSPlayload":"0x181801000000E2064B692B"}'
2023-01-29 15:19:35,522 10.10.10.253 [MQTT] miio/report b'{"id":748066907,"method":"properties_changed","params":[{"did":"1004333389","siid":2,"piid":5,"tid":190,"value":715.000000}],"type":16}'
2023-01-29 15:19:35,569 10.10.10.253 [MQTT] miio/report_ack b'{"id":748066907,"result":"ok"}'
2023-01-29 15:19:36,071 10.10.10.253 [MQTT] miio/report b'{"id":1656519908,"method":"properties_changed","params":[{"did":"1094373961","siid":2,"piid":3,"tid":59,"value":6}],"type":16}'
2023-01-29 15:19:36,130 10.10.10.253 [MQTT] miio/report_ack b'{"id":1656519908,"result":"ok"}'
2023-01-29 15:19:37,940 10.10.10.253 [MQTT] miio/report b'{"id":897816909,"method":"event_occured","params":{"did":"blt.3.1b9409h585o01","siid":2,"eiid":1008,"tid":240,"arguments":[{"piid":1005,"value":23.000000}]},"type":6}'
2023-01-29 15:19:37,941 10.10.10.253 | Processing MQTT: miio/report b'{"id":897816909,"method":"event_occured","params":{"did":"blt.3.1b9409h585o01","siid":2,"eiid":1008,"tid":240,"arguments":[{"piid":1005,"value":23.000000}]},"type":6}'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 168, in mqtt_message
    await self.dispatcher_send(SIGNAL_MQTT_PUB, msg=msg)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/base.py", line 111, in dispatcher_send
    await handler(**kwargs)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/miot.py", line 18, in miot_mqtt_publish
    await self.miot_process_event(msg.json["params"])
  File "/config/custom_components/xiaomi_gateway3/core/gateway/miot.py", line 42, in miot_process_event
    device.update(payload)
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 437, in update
    entity.async_set_state(value)
  File "/config/custom_components/xiaomi_gateway3/binary_sensor.py", line 113, in async_set_state
    assert data[self.attr] is True
AssertionError

I looked up the logs. Do you think these are useful

**Comment by AlexxIT** [comment]
Thanks. Very helpful. I'll fix this

**Comment by AlexxIT** [comment]
Fixed in latest master version. Will be in next release

**Comment by lovedreamland** [comment]
Tested, no problem, now it's normal.
