### ISSUE TITLE
Zigbee flash EZSP still not working

### ISSUE THREAD

**Issue by stopword** [AlexxIT/XiaomiGateway3#966]
Modell: ZNDMWG03LM
Fw: 1.5.0_0102 #20210816 (mod)
HA:
Home Assistant 2023.2.0
Supervisor 2023.01.1
Operating System 9.5
HW:
Home Assistant Blue / Hardkernel Odroid-N2

After select "Zigbee flash EZSP" command it can't update firmware:
```
Logger: custom_components.xiaomi_gateway3.core.ezsp
Source: custom_components/xiaomi_gateway3/core/ezsp.py:104
Integration: Xiaomi Gateway 3 ([documentation](https://github.com/AlexxIT/XiaomiGateway3), [issues](https://github.com/AlexxIT/XiaomiGateway3/issues))
First occurred: 11:13:21 (1 occurrences)
Last logged: 11:13:21

192.168.50.153 [FWUP] Can't update firmware
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 52, in update_zigbee_firmware
    cur_fw = await read_firmware(host)
  File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 104, in read_firmware
    await asyncio.wait_for(ezsp._probe(), timeout=10)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 74, in _probe
    await self.connect(use_thread=False)
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 118, in connect
    self._gw = await bellows.uart.connect(self._config, self, use_thread=use_thread)
  File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 404, in connect
    protocol, _ = await _connect(config, application)
  File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 375, in _connect
    transport, protocol = await zigpy.serial.create_serial_connection(
  File "/usr/local/lib/python3.10/site-packages/zigpy/serial.py", line 36, in create_serial_connection
    transport, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.50.153', 8889)
```
Any idea?

**Comment by AlexxIT** [comment]
#934
