### ISSUE TITLE
Stop receiving values from LYWSD03MMC after ~6-8 hours 

### ISSUE THREAD

**Issue by monsterflo** [AlexxIT/XiaomiGateway3#972]
Hello, 
on Home Assistant 2023.2.2 with v3.1.0 of the integration Home Assistant constantly loses contact to the LYWSD03MMC (Temp/Humidity) sensors after approx. 6 to 8 hours. Restarting Home Assistant solves the issue for another 6-8 hours.
Logs are empty. 

Any solution is appreciated.

REgards
Florian

**Comment by AlexxIT** [comment]
You need to collect component debug logs

**Comment by monsterflo** [comment]
Good evening. Here is everything linked to the xiaomi3 addon:

2023-02-06 15:17:18.793 DEBUG (MainThread) [custom_components.xiaomi_gateway3] Loaded from cache 17 devices
2023-02-06 15:17:29.399 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.xiaomi_cloud] Timeout while requesting MIoT api /v2/home/device_list_page
2023-02-06 15:17:29.402 DEBUG (MainThread) [custom_components.xiaomi_gateway3] Login to MiCloud for f.bach@web.de
2023-02-06 15:17:29.627 DEBUG (MainThread) [custom_components.xiaomi_gateway3.core.xiaomi_cloud] MiCloud step1
2023-02-06 15:17:29.769 DEBUG (MainThread) [custom_components.xiaomi_gateway3.core.xiaomi_cloud] MiCloud step2
2023-02-06 15:17:30.057 DEBUG (MainThread) [custom_components.xiaomi_gateway3.core.xiaomi_cloud] MiCloud step3
2023-02-06 15:17:31.505 DEBUG (MainThread) [custom_components.xiaomi_gateway3] Loaded from MiCloud 17 devices

2023-02-06 19:27:36.647 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.0.44 | Can't prepare gateway
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 177, in prepare_gateway
async with shell.Session(self.host) as sh:
File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 29, in __aenter__
await self.connect()
File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 36, in connect
self.reader, self.writer = await asyncio.wait_for(self.coro, 5)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
return fut.result()
File "/usr/local/lib/python3.10/asyncio/streams.py", line 47, in open_connection
transport, _ = await loop.create_connection(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
return await fut
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.44', 23)

The hub and all linked sensors are reachable from the Xiaomi Android-App

Regards
Florian

**Comment by AlexxIT** [comment]
Looks like your hub not reachable from Home Assistant

**Comment by tothak** [comment]
Hi,

I have the same issue.

Regards,
Ákos

**Comment by vmannoor** [comment]
I've the same issue. I face the same connectivity issues with xiaomi LYWSD03MMC sensors as well as qingping sensors (door, motion & light sensors)

**Comment by TischenkoArseny** [comment]
I have the same issue, rollback to 3.0.1 resolve problem.

**Comment by AlexxIT** [comment]
Still nothing useful from you to solve the problem

**Comment by TischenkoArseny** [comment]
What information can I provide to solve the problem?

**Comment by vmannoor** [comment]
> I have the same issue, rollback to 3.0.1 resolve problem.

I also rolled back to 3.0.1, seems like it solved the issue.  It's only been 3 hours, so I'll keep monitoring.

**Comment by dth97410** [comment]
I have the same problem for a few days...the data from the sensors do not go back to the home assistant "unavailable" when I reload or restart the integration it works again for a few hours then nothing.

**Comment by vmannoor** [comment]
> Still nothing useful from you to solve the problem

I updated again to 3.1.0, trying to help you so that you can help us). This is what I got from the log file. 
```
2023-02-08 15:43:08.148 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.kitchen_illuminance has device class illuminance, state class measurement and unit lx thus indicating it has a numeric value; however, it has the non-numeric value: unavailable (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-02-08 15:43:08.154 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.kitchen_motion_battery has device class battery, state class measurement and unit % thus indicating it has a numeric value; however, it has the non-numeric value: unavailable (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-02-08 15:43:08.157 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.582d34605599_idle_time has device class None, state class measurement and unit s thus indicating it has a numeric value; however, it has the non-numeric value: unavailable (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-02-08 15:44:39.467 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.toilet_illuminance has device class illuminance, state class measurement and unit lx thus indicating it has a numeric value; however, it has the non-numeric value: unavailable (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-02-08 15:44:39.475 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.toilet_motion_battery has device class battery, state class measurement and unit % thus indicating it has a numeric value; however, it has the non-numeric value: unavailable (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-02-08 15:44:51.198 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.bedroom_illuminance has device class illuminance, state class measurement and unit lx thus indicating it has a numeric value; however, it has the non-numeric value: unavailable (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-02-08 15:44:51.202 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.bedroom_motion_battery has device class battery, state class measurement and unit % thus indicating it has a numeric value; however, it has the non-numeric value: unavailable (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-02-08 15:44:51.206 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.bedroom_motion_idle_time has device class None, state class measurement and unit s thus indicating it has a numeric value; however, it has the non-numeric value: unavailable (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```
I enabled debug logs in the integration configuration. Where else I should look to provide you more useful inputs?

**Comment by tothak** [comment]
Well, I downgraded to 3.0.1 6 hours ago, and now it went offline again, so maybe it's not the integration, but something else....

**Comment by TischenkoArseny** [comment]
I also update back to 3.1.0, enable debug for component and wait for problem. Now all my ble sensors became unvailable, but no any information at this time in log, only this part in 2 hours after update component
2023-02-08 14:26:34.920 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.10.157 | Can't update gateway stats
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw.py", line 111, in gw3_update_serial_stats
    async with shell.Session(self.host) as sh:
  File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 30, in __aenter__
    return await self.login()
  File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 44, in login
    resp: bytes = await asyncio.wait_for(coro, 3)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 614, in readuntil
    raise exceptions.IncompleteReadError(chunk, None)
asyncio.exceptions.IncompleteReadError: 12 bytes read on a total of undefined expected bytes

**Comment by vmannoor** [comment]
my log has similar error warning from other another open issue: https://github.com/AlexxIT/XiaomiGateway3/issues/971#issue-1571396490.

**Comment by vmannoor** [comment]
I rolled back to 3.0.0, stable for the last 12+ hours.

**Comment by AlexxIT** [comment]
@vmannoor thanks for logs. All this BLE devices unavailable?

**Comment by vmannoor** [comment]
> @vmannoor thanks for logs. All this BLE devices unavailable?
> 
> `it has the non-numeric value: unavailable` fixed in master version. You can check if it helps you.

Yes, all the sensors go unavailable. But now I'm on 3.0.0 for the last 2 days and everything works perfectly.

**Comment by monsterflo** [comment]
Hello,
i rolled back to 3.0.0 but the "error" remains.
No values from the sensors after a few hours. The hub is reachable in the Xiaomi app.

Here is my log:
```

2023-02-11 22:19:38.493 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.mini_miio] 192.168.0.44 | Device offline
2023-02-11 22:20:08.932 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.0.44 | Can't prepare gateway
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 177, in prepare_gateway
async with shell.Session(self.host) as sh:
File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 29, in __aenter__
await self.connect()
File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 36, in connect
self.reader, self.writer = await asyncio.wait_for(self.coro, 5)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
return fut.result()
File "/usr/local/lib/python3.10/asyncio/streams.py", line 47, in open_connection
transport, _ = await loop.create_connection(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
return await fut
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.44', 23)
2023-02-11 22:49:30.303 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
```

Regards
Florian

**Comment by dth97410** [comment]
Hello, still no solution found for this bug? I have all my sensors unavailable.

**Comment by AlexxIT** [comment]
@monsterflo I hope problem will be resolved in next release

**Comment by ADMiNZ** [comment]
Same problem. Status is always Unknown (zigbee JTYJ-GD-01LM/BW (lumi.sensor_smoke)
Honeywell)
