### ISSUE TITLE
sensors become unavailable.

### ISSUE THREAD

**Issue by dth97410** [AlexxIT/XiaomiGateway3#990]
Hello, the problem of sensors becoming unavailable persists. I am desperate because most of my sensors work with the gateway.
Here is my log:
Logger: custom_components.xiaomi_gateway3.core.gateway
Source: custom_components/xiaomi_gateway3/core/converters/stats.py:119
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 19 février 2023 à 21:24:10 (1 occurrences)
Last logged: 19 février 2023 à 21:24:10

192.168.31.180 | Can't update gateway stats
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw.py", line 113, in gw3_update_serial_stats
    payload = self.device.decode(GATEWAY, {"serial": serial.decode()})
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 329, in decode
    conv.decode(self, payload, value)
  File "/config/custom_components/xiaomi_gateway3/core/converters/stats.py", line 119, in decode
    for k, v in RE_SERIAL.findall(lines[3]):
IndexError: list index out of range

integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "issue_tracker": "/api/xiaomi_gateway3/151bf836-7df4-45dc-9025-1685ca109be9",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http"
    ],
    "requirements": [
      "zigpy>=0.42.0"
    ],
    "version": "3.1.0",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "c33660c",
    "options": {
      "host": "***",
      "token": "***",
      "ble": true,
      "stats": true,
      "debug": [
        "zigbee"
      ],
      "memory": false
    },
    "errors": [
      {
        "name": "custom_components.xiaomi_gateway3.core.gateway",
        "message": [
          "192.168.31.180 | Can't update gateway stats"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/xiaomi_gateway3/core/converters/stats.py",
          119
        ],
        "timestamp": 1676827450.1842244,
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw.py\", line 113, in gw3_update_serial_stats\n    payload = self.device.decode(GATEWAY, {\"serial\": serial.decode()})\n  File \"/config/custom_components/xiaomi_gateway3/core/device.py\", line 329, in decode\n    conv.decode(self, payload, value)\n  File \"/config/custom_components/xiaomi_gateway3/core/converters/stats.py\", line 119, in decode\n    for k, v in RE_SERIAL.findall(lines[3]):\nIndexError: list index out of range\n",
        "count": 1,
        "first_occurred": 1676827450.1842244
      }
    ],
    "device": {
      "type": "ble",
      "model": 426,
      "fw_ver": null,
      "available": false,
      "decode_time": 36034,
      "entities": {
        "temperature": {
          "state": "unavailable",
          "value": 23.8
        },
        "humidity": {
          "state": "unavailable",
          "value": 75.3
        },
        "battery": {
          "state": "unavailable",
          "value": 77
        },
        "ble": {
          "state": "2023-02-19T17:21:56+00:00",
          "value": "2023-02-19T17:21:56.051842+00:00"
        }
      },
      "gateways": [
        "7811dc93ef92"
      ],
      "stats": {
        "mac": "4c65a8d04c8d",
        "available": true,
        "msg_received": 63,
        "last_msg": "TempHum"
      },
      "unique_id": "4c65a8d04c8d"
    },
    "logger": []
  }
}

**Comment by sclgroup** [comment]
Hi, I had a same issue right after upgraded to 3.1.0 - my zigbee sensors stopped working  in home assistant and MiHome app too ! When home assistant stopped, sensors came back in MiHome. BLE sensors sometime worked, sometime not.
I did a rollback to 2.1.2 but nothing changed.
I checked my gateways via telnet and deleted   "openmiio_agent.json" and "openmiio_agent" right after that everything came back  and working fine (with v2.1.2).
I hope this helps.
![gwfault](https://user-images.githubusercontent.com/77414730/221350218-95a2fbf4-b615-4678-a564-0901562d0743.PNG)

**Comment by joaomalaquias** [comment]
> 

Hello.
Could you help me doing the same thing please?

How can i do rollback to 2.1.2 and check my gateways via telnet and deleted "openmiio_agent.json" and "openmiio_agent" ?

Thanks

**Comment by sclgroup** [comment]
Go Settings>System>Backups and choose last working version, click on it and restore:

![restore](https://user-images.githubusercontent.com/77414730/222217968-76393994-fec7-439e-93a2-25d6955b9912.PNG)

.. and after that  go HACS>Search "Xiaomi Gateway" click on tree dots on right side and choose "redownload" in the popup choose the right version and download

![redownload](https://user-images.githubusercontent.com/77414730/222219355-cf14dc96-1954-43a2-916d-64529974936b.PNG)

If you can to telnet to the gateway "telnet ipaddress_of_your_gateway" username admin and no password.
If you are in type "rm /data/opemmiio_agent.json" and "rm /data/opemmiio_agent" as you can see on screenshot in my previous comment.

Restart HA when it ask you to do it.

**Comment by joaomalaquias** [comment]
> Go Settings>System>Backups and choose last working version, click on it and restore:
> 
> ![restore](https://user-images.githubusercontent.com/77414730/222217968-76393994-fec7-439e-93a2-25d6955b9912.PNG)
> 
> .. and after that go HACS>Search "Xiaomi Gateway" click on tree dots on right side and choose "redownload" in the popup choose the right version and download
> 
> ![redownload](https://user-images.githubusercontent.com/77414730/222219355-cf14dc96-1954-43a2-916d-64529974936b.PNG)
> 
> If you can to telnet to the gateway "telnet ipaddress_of_your_gateway" username admin and no password. If you are in type "rm /data/opemmiio_agent.json" and "rm /data/opemmiio_agent" as you can see on screenshot in my previous comment.
> 
> Restart HA when it ask you to do it.
> 
> BTW, since then I did upgrade gateway's firmware to version 1.5._0090 (latest) and upgraded integration to 3.1 (just integration) again in HA and everything working fine !!

Many Thanks,

My version is 1.4.6_0043, and say its up to date :/
I will test this and give feedback later :)

**Comment by sclgroup** [comment]
> > Go Settings>System>Backups and choose last working version, click on it and restore:
> > ![restore](https://user-images.githubusercontent.com/77414730/222217968-76393994-fec7-439e-93a2-25d6955b9912.PNG)
> > .. and after that go HACS>Search "Xiaomi Gateway" click on tree dots on right side and choose "redownload" in the popup choose the right version and download
> > ![redownload](https://user-images.githubusercontent.com/77414730/222219355-cf14dc96-1954-43a2-916d-64529974936b.PNG)
> > If you can to telnet to the gateway "telnet ipaddress_of_your_gateway" username admin and no password. If you are in type "rm /data/opemmiio_agent.json" and "rm /data/opemmiio_agent" as you can see on screenshot in my previous comment.
> > Restart HA when it ask you to do it.
> > BTW, since then I did upgrade gateway's firmware to version 1.5._0090 (latest) and upgraded integration to 3.1 (just integration) again in HA and everything working fine !!
> 
> Many Thanks,
> 
> My version is 1.4.6_0043, and say its up to date :/ I will test this and give feedback later :)

You are in Europe... I followed this https://github.com/zvldz/mgl03_fw/tree/main/firmware

**Comment by Darkdragon14** [comment]
Thanks @sclgroup, indeed, after upgrade manually my gateway with the version 1.5._0090, the addon work fine with Home Assistant

**Comment by sclgroup** [comment]
:-)

**Comment by Wh1terat** [comment]
This has been running for a couple of years now without issue until this last update.
Facing the same problem since updating 2 days ago to plugin ver 3.1.0 and Hass 2023.3.2.

I've tried:
Updating my mgl03 from v1.5.0_0102 to v1.5.4_0090
Downgrading the plugin back to v3.0.1

Syslog is just getting absolutely hammered with these messages:
```Mar 12 19:22:59 rlxlinux user.info syslog[1813]: [19924]: [I] IDMClient: IDMClient::Init
Mar 12 19:22:59 rlxlinux user.info syslog[1813]: [19924]: [I] IDMBinderBase: Init
Mar 12 19:22:59 rlxlinux user.info syslog[1813]: [19924]: [I] RuntimeService: Bind...0x4b31e8
Mar 12 19:22:59 rlxlinux user.info syslog[1813]: [19924]: [I] RuntimeService: RuntimeService::ConnectRuntimeCallback------------------
Mar 12 19:22:59 rlxlinux user.debug syslog[1813]: [19924]: [D] transmgr: ConnectServer
Mar 12 19:22:59 rlxlinux user.debug syslog[1813]: [1837]: [D] transmgr: ConnectServer invoked
Mar 12 19:22:59 rlxlinux user.debug syslog[1813]: [1837]: [D] transmgr: on_svr_conn_cb:-146
Mar 12 19:22:59 rlxlinux user.info syslog[1813]: [1837]: [I] RuntimeService: OnTransportErr,status=-146
Mar 12 19:22:59 rlxlinux user.info syslog[1813]: [1837]: [I] RuntimeService: OnRuntimeDisconnected-------------
Mar 12 19:22:59 rlxlinux user.info syslog[1813]: [1837]: [I] IDMBinderBase: OnRuntimeDisconnected
Mar 12 19:22:59 rlxlinux user.err syslog[1813]: [1837]: [E] transmgr: new pipe connection error.:ECONNREFUSED
Mar 12 19:22:59 rlxlinux user.info syslog[1813]: [app]idm_client: OnProcessDisconnected```

Is this an openmiio bug and downgrading the plugin hasn't actually downgraded the openmiio included on the hub?

**Comment by sclgroup** [comment]
I can't judge it, however since then I did an another instance of HA - latest version both HA and integration and everything works flawlessly.
Try to delete openmiio files manually via telnet...

**Comment by dth97410** [comment]
I don't understand how to delete the open miio. I can change the firmware via the putty program but I can't access the file like you.

**Comment by sclgroup** [comment]
.... login to gateway using putty, and enter command below:

ls -l /data

... if openmiio_agent is installed  jo have to see

openmiio_agent
openmiio_agent.json

than enter commands:

rm /data/openmiio_agent.json
rm /data/openmiio_agent

thats all.

**Comment by Wh1terat** [comment]
So downgrading the plugin didn't downgrade the openmiio agent installed (which shouldn't happen).
Removing openmiio does force it to download the correct version for that plugin version.

However still no joy, it's still utterly unusable:

<img width="1527" alt="Screenshot 2023-03-14 at 17 32 38" src="https://user-images.githubusercontent.com/1288525/225089779-5f15f57e-7929-4541-9010-9c64b891ddd8.png">

At this point I'm at a bit of a loss, short of factory resetting the hub and starting again.

Should be noted I *only* use the hub for BLE devices, my zigbee stuff is setup elsewhere.

**Comment by dth97410** [comment]
Why isn't there an update from AlexxIT to fix this problem?

**Comment by Wh1terat** [comment]
Mystery solved!

Despite having had it disabled since I purchased it, the ble gateway function magically has been turned on on my qingping air monitor lite.

I rarely open the Xiaomi app or perform firmware updates (If it's not broken, why fix it?) so can only assume that this change has been pushed by Xiaomi without my permission.

**Comment by AlexxIT** [comment]
@dth97410 I have never seen this error before. Does it occur regularly to this day?

**Comment by dth97410** [comment]
> @dth97410 I have never seen this error before. Does it occur regularly to this day?

Yes, this has been happening to me since January... if I restart the hub or reload the integration, it works for less than an hour and nothing happens...

**Comment by dth97410** [comment]
> @dth97410 I have never seen this error before. Does it occur regularly to this day?

Hi the latest version solved my problem! Everything is working properly so far thank you very much for your work!
